### ISSUE TITLE
Photos permissions not working on IOS 7

### ISSUE THREAD

**Issue by smarongiu** [jamesmontemagno/PermissionsPlugin#10]
## Bug

Version Number of Plugin: 1.1.7
Device Tested On: iPhone 4 (with iOS 7.1.1 and 7.1.2)
Simulator Tested On: -
### Expected Behavior

If permission was granted, PermissionStatus result should be "Granted", otherwise it should ask for permission.
### Actual Behavior

PermissionStatus is "Unknow" => no popup asking for permission, application flow is stalled on the request task.
### Steps to reproduce the Behavior

Build&Run PermissionSample app on a device with iOS 7 (without granted permissions for the app), click on "Photos"
=> popup : Result "Unknow", click on "Ok"
=> app is stalled, no popup to ask for permissions

**Comment by jamesmontemagno** [comment]
Closing since I only support 8+ now
