### ISSUE TITLE
Doesn't work with latest version of CurrentActivity plugin

### ISSUE THREAD

**Issue by madareklaw** [jamesmontemagno/PermissionsPlugin#100]
## Bug Information

Version Number of Plugin: 2.2.1
Device Tested On: Samsung S7 Android 7.0
Simulator Tested On: N/A
Version of VS: Professional 2017 V15.7.1
Version of Xamarin: V4.10.0.442
Versions of other things you are using:
Plugin.CurrentActivity V2.1.0.1
### Steps to reproduce the Behavior
Attempt to request permissions 
### Expected Behavior
popup with a user prompt to accept these permissions
### Actual Behavior
does nothing
### Code snippet
 ```
var arr = new Permission[] { Permission.Storage, Permission.Location };
var results = await CrossPermissions.Current.RequestPermissionsAsync(arr);
```
### Notes
This plugin has been working fine until i updated the currentActivity plugin to its latest version (2.1.0.1). After updating the plugin would not prompt the user to grant permissions. When i downgrade the currentActivity back to version 1.0.1 it works fine.

**Comment by jamesmontemagno** [comment]
You need: https://www.nuget.org/packages/Plugin.Permissions/3.0.0.9-beta
