### ISSUE TITLE
Getting downgrading message in VS 2017 project error window

### ISSUE THREAD

**Issue by davefxy** [jamesmontemagno/PermissionsPlugin#101]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.
When selecting the plugin in the Manage NuGetpackages dialog, where the version info and dependencies used to display is now blank. I am now getting the following message in the VS  project error window that has been using this plugin:
Warning	NU1605	Detected package downgrade: Plugin.Permissions from 3.0.0.8 to 2.2.1. Reference the package directly from the project to select a different version. 
 RouteWeatherApp.Android -> Xam.Plugin.Geolocator 4.5.0.1 -> Plugin.Permissions (>= 3.0.0.8) 
 RouteWeatherApp.Android -> Plugin.Permissions (>= 2.2.1)				

If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

 If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

The Android app seems to run fine. This is the first time I have seen the VS message. No changes have been made to the code. I think this started appearing as I have been upgrading the existing Nuget packages. Xam.Plugins.Setting also has a blank display when selecting it in the Manage Nuget Packages dialog. The plugins are referenced in each target in the single solution.

Version Number of Plugin: V2.2.1
Device Tested On:
Simulator Tested On:
Version of VS:  VS 2017 V15.7.1
Version of Xamarin: v4.10.0.442
Versions of other things you are using:
Xamarin.Forms V3.0.0.482510
### Steps to reproduce the Behavior
Create a Net standard cross-platform project with Android and UWP. Only configured Android to deploy.

**Comment by jamesmontemagno** [comment]
4.5.0.1 no longer exists. Install: 4.5.0.4-beta
