### ISSUE TITLE
The permissions plugin always returns "granted" on android when the permission has been revoked in the app settings. 

### ISSUE THREAD

**Issue by PaulVrugt** [jamesmontemagno/PermissionsPlugin#103]
## Bug Information

The permissions plugin always returns "granted" on android when the permission has been revoked in the app settings. I think this happens starting api version 23. I found the cause using this post:

https://stackoverflow.com/questions/33039188/checkselfpermission-returning-permission-granted-for-revoked-permission-with-tar

Using the PermissionChecker, I got the correct result eventually. (android.support.v4.content.PermissionChecker)

See also: https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/45
They already made a change for api 23 and up

Version Number of Plugin: latest
Device Tested On: Google Nexus 5X with android 8.1
Simulator Tested On: - 
Version of VS: 2017
Version of Xamarin: latest
Versions of other things you are using: -

### Steps to reproduce the Behavior
Create app that uses location, and checks location permission using the permission checker plugin
start the app and verify location can be used
close the app
now go to settings => app => the app
revoke the location permission
start the app again
the app crashes, because it still tries to use location, while permission has been revoked

### Expected Behavior
the app doesn't use location, because permission has been revoked

### Actual Behavior
the app crashes, because it still tries to use location, while permission has been revoked

### Code snippet
await Plugin.Permissions.CrossPermissions.Current.CheckPermissionStatusAsync(Plugin.Permissions.Abstractions.Permission.LocationWhenInUse);

**Comment by PaulVrugt** [comment]
hmm weird. this looks like https://github.com/jamesmontemagno/PermissionsPlugin/pull/69 but I'm still running into it. My app's minversion is 4.4.1, and I build against the latest sdk (8.1)

**Comment by jamesmontemagno** [comment]
If you don't target M+ then it will always return granted because it doesn't use the new permission system.

**Comment by PaulVrugt** [comment]
I don't know what to say..... I wanted to dig deeper to see what the issue was, but when I started my app this morning without changing any code, the permission plugin returned the right result.

I guess this issue can be closed. If it happens again I'll dig deeper and report back, but the issue seems to have solved itself

sorry to have wasted your time

**Comment by Phenek** [comment]
Today the plugin on all permissions are returning Granted for me.
Even if I disabled all in settings. Hope it will stop tomorrow.
