### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by andymacourek** [jamesmontemagno/PermissionsPlugin#104]
## Bug Information

Version Number of Plugin: 2.2.1
Device Tested On: Forms Android API 25
Simulator Tested On:  Android API 25
Version of VS:  2017
Version of Xamarin:  2.51.527436
Versions of other things you are using:

Getting error with 

global::Plugin.CurrentActivity.CrossCurrentActivity.Current.Init(this, bundle);

ICurrentActivity' does not contain a definition for 'Init' and no extension method 'Init' accepting a first argument of type 'ICurrentActivity' could be found (are you missing a using directive or an assembly reference?

**Comment by andymacourek** [comment]
Also, when I tried using the latest version, it would not build.  it gave an error for droid about Plugin,Permissions.Abstractions could not be found.

**Comment by jamesmontemagno** [comment]
If you upgraded to current activity 2.x then you need to use: 3.0.0.12-beta
