### ISSUE TITLE
Install issue with 3.0.0.12-beta and Plugin.Permissions.Abstractions

### ISSUE THREAD

**Issue by andymacourek** [jamesmontemagno/PermissionsPlugin#105]
VIersion Number of Plugin: 3.0.0.12-beta
Device Tested On: Forms Android API 25
Simulator Tested On: Android API 25
Version of VS: 2017
Version of Xamarin: 2.51.527436
Versions of other things you are using:

Getting error with
Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Plugin.Permissions.Abstractions, Version=2.2.1.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'Plugin.Permissions.Abstractions.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	LooksyApp.Android

**Comment by andymacourek** [comment]
I had thought that it might be a case of not having Plugin.CurrentActivity NuGet installed in the Android project.  I installed Plugin.CurrentActivity 2,1,0,2 and I am getting the same error,  I notice that in the beta nuget pacakge you do not have Plugin.Permissions.Abstractions.dl

**Comment by jamesmontemagno** [comment]
This dll no longer exists, do a full clean/rebuild and delete bin/obj

**Comment by thiagokernel** [comment]
I have the same problem. I tried clean / rebuild and delete bin / obj, and the error continues. What to do?

**Comment by torleifs** [comment]
I upgraded the versions of all Plugin.* and xam.plugin.* and then it worked for me.

**Comment by trilm208** [comment]
i have same problems although i clean/rebuild all Plugin.* and Xam.Plugin.*.
Xam.Plugin.Connectivity: 4.0.0.186-beta
Xam.Plugin.Geolocator: 5.0.0.187-beta
Xam.Plugin.Media: 4.0.1.1-beta
Xam.Plugin.Version: 1.0.0
Plugin.Permissions: 3.0.0.12

**Comment by trilm208** [comment]
@jamesmontemagno : I guess Xam.Plugin.Geolocator still use old version of Plugin.Permission.   Please check this dll.

**Comment by juanagu** [comment]
I have the same problem.

**Comment by jamesmontemagno** [comment]
Your issue would be Xam.Plugin.Geolocator: 5.0.0.187-beta as I have not updated this yet. I would recommend sticking with 4.X as I have to re-do 5.X

**Comment by trilm208** [comment]
Nice. It's work. Thanks @jamesmontemagno
