### ISSUE TITLE
[Android] Permissions are granted automatically when debugging applications

### ISSUE THREAD

**Issue by tuyen-vuduc** [jamesmontemagno/PermissionsPlugin#106]
## Bug Information
1. Permissions are automatically granted when running the app
2. Manually disabled permission will result, couldn't request again.

NOTE: running the sample code without modification, it's ok. However, any changes made will result with above cases even if Ctrl (Cmd)+Z.

Version Number of Plugin: 2.2.1
Device Tested On: Android M+
Simulator Tested On: Android M+
Version of VS: Latest, 15.7.1 (VSfM 7.5.1)
Version of Xamarin: Latest
Versions of other things you are using:
- Current Activity Plugin v2.1.0.2
- MvvmCross 6.0.0

### Steps to reproduce the Behavior
Case#1
- Run the sample code [here](https://github.com/NAXAM/mvvmcross-permissionsqs)
- Check app permissions

Case#2
- Disable app permission
- Run the app then try to request permission

### Expected Behavior
Case#1
- No permission is granted by default

Case#2
- Permission request alert must be shown

### Actual Behavior
Case#1
- All registered permissions is granted by default

Case#2
- Permission request alert never shown

### Code snippet
[here](https://github.com/NAXAM/mvvmcross-permissionsqs)

### Screenshots
![screenshot_1527052107](https://user-images.githubusercontent.com/3112460/40404453-21fe73ba-5e82-11e8-99e6-4a7d52f37872.png)

**Comment by jamesmontemagno** [comment]
And when not in debug?

**Comment by tuyen-vuduc** [comment]
Release on LGv20, same issue.

BTW, I couldn't build your plugin code on my Windows.

**Comment by tuyen-vuduc** [comment]
I only set minimum target. Is that the issue?

**Comment by tuyen-vuduc** [comment]
It looks like target sdk is required to set. I only leave it default to latest compiled sdk.

Thank you very much.

BTW, do I need to setup anything to compile this repo? I am having latest VSfM and VS.

**Comment by jamesmontemagno** [comment]
I have it documented in the readme for this, let me know if I can improve that at all. 

This solution only builds in VS2017 currently. It uses newer csproj and multi-targeting ;)

**Comment by tuyen-vuduc** [comment]
I will try again on my VS2017. The note for target sdk isn't in readme.txt or readme.md yet. Plz include.
