### ISSUE TITLE
Android build fails after upgrading to 3.0.0.12

### ISSUE THREAD

**Issue by adienthu** [jamesmontemagno/PermissionsPlugin#107]
## Bug Information
After upgrading to 3.0.0.12 the Android build fails.

Version Number of Plugin: 3.0.0.12
Device Tested On: NA
Simulator Tested On: NA
Version of VS: VS for Mac 7.4.1 (build 48)
Version of Xamarin: Xamarin.Android v8.2.0.16
Versions of other things you are using:
SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 26.0.3

### Steps to reproduce the Behavior

Build Forms Android project.

### Expected Behavior
Build should succeed.

### Actual Behavior
Build fails with the following error:

System.IO.FileNotFoundException: Could not load assembly 'Plugin.Permissions.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?

**Comment by b-theile** [comment]
Same problem here. Did clean project several times. Deleted obj/bin. Nothing helped.
Xamarin version 2.5.1.527436 and 3.0.0.482510. Tested on both. VS 15.7.2

**Comment by jamesmontemagno** [comment]
This DLL has been removed, you can delete it. Ensure that everythings is on the latest version.

**Comment by adienthu** [comment]
By everything do you mean upgrading the Xamarin Forms as well ?

**Comment by jamesmontemagno** [comment]
Nope, just the permissions plugin. This error usually means you have different versions installed in your projects. ensure that you don't have any lingering .Abstractions.dll s around.

**Comment by adienthu** [comment]
I upgraded the Media plugin (Xam.Media.Plugin) and the build is succeeding now. Guess any libraries that depend on Permissions need to be upgraded as well.

**Comment by jamesmontemagno** [comment]
Correct, i released new versions of all of them to align. :)

**Comment by duzenko** [comment]
I guess you should post a dependency table somewhere so that users know plugin version compatibility. I can't upgrade the media plugin because of the rotation bug: 
https://github.com/jamesmontemagno/MediaPlugin/issues/548
