### ISSUE TITLE
Can I check write-only access to photo library  permission in iOS11?

### ISSUE THREAD

**Issue by brian80122** [jamesmontemagno/PermissionsPlugin#108]
First, thanks to provide this perfect plugin.  
While i develop in my work, i have a request to check 'NSPhotoLibraryAddUsageDescription' which is support in iOS 11, but i found there is only "photos" in permissions which is full control, not just write access.  Is there any way to check this permission by plugin?  
more Information:https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW1
<img width="1015" alt="2018-06-15 3 36 31" src="https://user-images.githubusercontent.com/21362148/41456050-e9399518-70b1-11e8-9ea8-05c6b60314fd.png">
thanks!

**Comment by jamesmontemagno** [comment]
It is whichever that you have in there I believe. So the docs say that in iOS 10 + you need to put one of them... but in 11+ they introduced Add. so my assumption is that if you want Add only then you app can only support 11+ and you can only have that permission in there.

I just call apple's request code:  PHPhotoLibrary.RequestAuthorization

**Comment by brian80122** [comment]
I see, I will try and research that you mentioned. Thanks for your replay!
