### ISSUE TITLE
System.MissingMethodException: void Plugin.CurrentActivity.ICurrentActivity.Init(Android.App.Activity,Android.OS.Bundle)

### ISSUE THREAD

**Issue by FreedCapybara** [jamesmontemagno/PermissionsPlugin#109]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: Plugin.Permissions 3.0.0.12, Plugin.CurrentActivity 2.1.0.4
Device Tested On: Galaxy Note 5
Simulator Tested On:
Version of VS: VS2017
Version of Xamarin: 2.5.0.280555
Versions of other things you are using:

### Steps to reproduce the Behavior
Start debugging the app

### Expected Behavior
The app runs on Android

### Actual Behavior
The app crashes with `System.MissingMethodException: void Plugin.CurrentActivity.ICurrentActivity.Init(Android.App.Activity,Android.OS.Bundle)`

### Code snippet
_MainActivity.cs_
```csharp
    public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
    {
        private App _app;
        protected override void OnCreate(Bundle bundle)
        {
            base.OnCreate(bundle);

            global::Xamarin.Forms.Forms.Init(this, bundle);
            global::ZXing.Net.Mobile.Forms.Android.Platform.Init();

            Plugin.CurrentActivity.CrossCurrentActivity.Current.Init(this, bundle);

            // ...

            LoadApplication(_app);
        }

        public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)
        {
            global::ZXing.Net.Mobile.Android.PermissionsHandler.OnRequestPermissionsResult(requestCode, permissions, grantResults);
            PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
            base.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }
    }
```
Somebody else set this up, but here's _MainApplication.cs_
```csharp
   [Application]
    public class MainApplication : Application, Application.IActivityLifecycleCallbacks
    {
        public MainApplication(IntPtr handle, JniHandleOwnership transer)
          : base(handle, transer)
        {
        }

        public override void OnCreate()
        {
            base.OnCreate();
            // CrossCurrentActivity.Current.Init(this); <--- blows up commented or uncommented, and I'm a little fuzzy on whether or not I need this
            RegisterActivityLifecycleCallbacks(this);
        }

        public override void OnTerminate()
        {
            base.OnTerminate();
            UnregisterActivityLifecycleCallbacks(this);
        }

        public void OnActivityCreated(Activity activity, Bundle savedInstanceState)
        {
            CrossCurrentActivity.Current.Activity = activity;
        }

        public void OnActivityDestroyed(Activity activity)
        {
        }

        public void OnActivityPaused(Activity activity)
        {
        }

        public void OnActivityResumed(Activity activity)
        {
            CrossCurrentActivity.Current.Activity = activity;
        }

        public void OnActivitySaveInstanceState(Activity activity, Bundle outState)
        {
        }

        public void OnActivityStarted(Activity activity)
        {
            CrossCurrentActivity.Current.Activity = activity;
        }

        public void OnActivityStopped(Activity activity)
        {
        }
    }
```

**Comment by mrTR24** [comment]
remove  Plugin.CurrentActivity.CrossCurrentActivity.Current.Init(this, bundle);
replace with CrossCurrentActivity.Current.Activity = this in your MainActivity.cs

**Comment by jamesmontemagno** [comment]
Please remove and re-add the nuget as it works in all my apps. Seems like nuget cache issue. You no lnoger need this class either.

**Comment by conceptworld** [comment]
A simple Rebuild All worked in my case.

In addition to this here is additional info.

The problem in my case was that I also had the code RegisterActivityLifecycleCallbacks and UnregisterActivityLifecycleCallbacks etc in MainApplication.cs .

This code is supposed to be there only if you are using 1.0 version of CurrentActivityPlugin. Now that we have upgraded to 2.0  version, we must remove that code and use only what is documented for 2.0 on https://github.com/jamesmontemagno/CurrentActivityPlugin/blob/master/README.md

After which a 'Rebuild All' (important) worked.
