### ISSUE TITLE
Permission location returns granted but is not (Android 6.0)

### ISSUE THREAD

**Issue by PierreCourt** [jamesmontemagno/PermissionsPlugin#11]
## Bug 

Version Number of Plugin: 1.7
Device Tested On: OnePlus x (5.1),  OnePlus 3 (6.0)

### Expected Behavior

In my app, I check for the location permission. On Android 5.1, if I change the permission to false, the status does not return granted. 

### Actual Behavior

However, with an Android 6.0 device, if I have accepted the request for location at the installation, even if I change the permission to false, it returns granted.

**Comment by PierreCourt** [comment]
Duplicate of #3

**Comment by PierreCourt** [comment]
I checked a bit more and I have set the build and the target to api 23 but I still have:
 `Client must have ACCESS_FINE_LOCATION permission to request PRIORITY_HIGH_ACCURACY locations.`
 And I request the permission in the manifest.

**Comment by rohitvipin** [comment]
I had the same issue with Camera on Android 6.0. But setting the SDK version manually to compile version works fine.

**Comment by jamesmontemagno** [comment]
Yes, you must set target & compile with to both 7.0 or 6.0 as documented.

**Comment by jrom20** [comment]
@jamesmontemagno  How do you turn X permission off? Assuming that I'm compiling and targeting an 6 or  above android version? Can you please show me that little piece of code?
