### ISSUE TITLE
Plugin.Permissions does not appear to have an instance of PermissionsImplementation

### ISSUE THREAD

**Issue by jsauve** [jamesmontemagno/PermissionsPlugin#111]
## Bug Information

Version Number of Plugin: 3.0.0.12

Device Tested On: N/A at this time

Simulator Tested On: Oreo 8.0 Android emulator

Version of VS: Visual Studio Community 2017 for Mac, Version 7.5.3 (build 7)

Version of Xamarin:

Xamarin.iOS
Version: 11.12.0.4 (Visual Studio Community)
Hash: 64fece5f
Branch: d15-7
Build date: 2018-05-29 20:00:44-0400

Xamarin.Android
Version: 8.3.3.2 (Visual Studio Community)
Android SDK: /Users/joesauve/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

Versions of other things:
Xamarin.Forms 3.1.0.637273
MvvmCross 5.6.3

### Steps to reproduce the Behavior
1. Add Plugin.Permissions NuGet
2. Add following method to MainActivity.cs, per readme:
```
public override void OnRequestPermissionsResult(int requestCode, string[] permissions, [GeneratedEnum] Android.Content.PM.Permission[] grantResults)
{
    Plugin.Permissions.PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);

    base.OnRequestPermissionsResult(requestCode, permissions, grantResults);
}
```
3. Attempt an Android build
4. Fails due to `Plugin.Permissions` not having an instance of `PermissionsImplementation`
5. Clean Solution
6. Delete all bin & obj folders from solution folder, recursively
7. Clean solution
7. Restore Nugets at the solution level
8. Re-build solution for Android config
9. Go to step 4

I've also re-installed the plugin several times, deleting my Packages folder between each attempt.

### Expected Behavior
`Plugin.Permissions` should have an instance of `PermissionsImplementation`

### Actual Behavior
`Plugin.Permissions` does not appear to have an instance of `PermissionsImplementation`

### Code snippet
```
public override void OnRequestPermissionsResult(int requestCode, string[] permissions, [GeneratedEnum] Android.Content.PM.Permission[] grantResults)
{
    Plugin.Permissions.PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);

    base.OnRequestPermissionsResult(requestCode, permissions, grantResults);
}
```

### Screenshots
![](https://image.ibb.co/irFB8d/Permissions_Implementation_Unavailable.png)

**Comment by jamesmontemagno** [comment]
Make sure you are compiling against a newer Android version, remove and add the nuget. You can check to see where it is trying to find the dll.

**Comment by jsauve** [comment]
Ahhh...shoot. Does this not work for Android 7.0 targets? I'm stuck using a 3rd party lib that keep me from targeting higher than 7.0 for now. :(

**Comment by jamesmontemagno** [comment]
you don't need to change the target, just your compile version, they are different.

**Comment by jamesmontemagno** [comment]
Must compile against: MonoAndroid71

**Comment by jsauve** [comment]
Fantabulous. Thanks James!

**Comment by okkenze** [comment]
jsauve, Please i am having the same challenge. How did you implement the solution given by James? "Must compile against: MonoAndroid71"

**Comment by francis2** [comment]
Am having same issue and I tried everything above. Still won't find the reference. Plugin.Permissions is not found.

Is target framework and target android version = pie 9.0 supported?

**Comment by jamesmontemagno** [comment]
See: https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/android-api-levels?tabs=windows
