### ISSUE TITLE
If the libary is broken on the windows plattform?

### ISSUE THREAD

**Issue by paule96** [jamesmontemagno/PermissionsPlugin#113]
Disclaimer:
I don't know if this is a question or a bug. 😄 

## Bug Information

Version Number of Plugin: 3.0.0.12
Device Tested On: Windows Desktop UWP App with Xamerin Forms
Simulator Tested On: no simulator because I test this on the windows UWP plattform
Version of VS: 15.7.5
Version of Xamarin: 
- Xamarin Forms: 3.1.0.637273
- Xamarin.Forms.Maps: 3.1.0.637273

### Steps to reproduce the Behavior
1. Create a Xamerin Forms App. (for iOS, Android and UWP)
2. Install Xamarin.Forms.Maps in the project
3. Install the Permission Plugin in the projekt
3. Do all steps to add a new Map Content Page, see code snippets (I currently do this only for UWP (you don't need all plattforms to reproduce this)
5. add the page to ne navigation of the app
6. Set the rights in the manifest of the apps
7. run the UWP app
8. now navigate to the mapspage in your app
9. now the app promted you to give you the permissions for location. (note: see in the debugger output. this is at the line with ```var status = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Location);``` because the line "Debug.WriteLine("year we would check!");"  is the last line in the output window)
10. Now answer with "No". 
11. The next Debugging output is very strange:
```
year we would check! Status: Denied
this only do anythink on android...
now we ask the user 
year we got a answer!
status granted!!!!
```

### Expected Behavior
- The line ```await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Location);``` only check the status
- The line ```await CrossPermissions.Current.RequestPermissionsAsync(Permission.Location);``` ask the user
- The line ```status == PermissionStatus.Granted``` is true if the status allow to access the location
### Actual Behavior
- The line ```await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Location);``` ask the user
- The line ```await CrossPermissions.Current.RequestPermissionsAsync(Permission.Location);``` do nothing or I don't get it 🙉 
- The line ```status == PermissionStatus.Granted``` is true if the status disallow to access the location

### Code snippet

MapsPage.xaml:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:maps="clr-namespace:Xamarin.Forms.Maps;assembly=Xamarin.Forms.Maps"
             x:Class="FirstTry.Views.MapsPage">
    <ContentPage.Content>
        <StackLayout>
            <Label Text="Welcome to Xamarin.Forms!"
                VerticalOptions="Center"
                HorizontalOptions="CenterAndExpand" />
            <maps:Map
                    x:Name="MyMap"
                    IsShowingUser="false"
                    MapType="Hybrid" />
        </StackLayout>
    </ContentPage.Content>
</ContentPage>
```

MapsPage.cs

```csharp
using Plugin.Permissions;
using Plugin.Permissions.Abstractions;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Xamarin.Forms;
using Xamarin.Forms.Xaml;

namespace FirstTry.Views
{
    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class MapsPage : ContentPage
    {
        public MapsPage()
        {
            InitializeComponent();
        }

        protected override void OnAppearing()
        {
            base.OnAppearing();
            Task.Run(ShowTheCurrentUser);
        }

        public async Task ShowTheCurrentUser()
        {
            MyMap.IsShowingUser = await HaveLocationPermissions();
        }

        public async Task<bool> HaveLocationPermissions()
        {
            Debug.WriteLine("year we would check!");
            try
            {
                var status = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Location);
                Debug.WriteLine($"year we would check! Status: {status.ToString()}");
                if (status != PermissionStatus.Granted)
                {
                    Debug.WriteLine($"this only do anythink on android...");
                    if (await CrossPermissions.Current.ShouldShowRequestPermissionRationaleAsync(Permission.Location))
                    {
                        await DisplayAlert("Need location", "Gunna need that location", "OK");
                    }
                    Debug.WriteLine($"now we ask the user ");
                    var results = await CrossPermissions.Current.RequestPermissionsAsync(Permission.Location);
                    Debug.WriteLine($"year we got a answer!");
                    //Best practice to always check that the key exists
                    if (results.ContainsKey(Permission.Location))
                        status = results[Permission.Location];
                }

                if (status == PermissionStatus.Granted)
                {
                    Debug.WriteLine($"status granted!!!!");
                    return true;
                    //var results = await CrossGeolocator.Current.GetPositionAsync(10000);
                    //LabelGeolocation.Text = "Lat: " + results.Latitude + " Long: " + results.Longitude;
                }
                else if (status != PermissionStatus.Unknown)
                {
                    Debug.WriteLine($"status unkown.");
                    await DisplayAlert("Location Denied", "Can not continue, try again.", "OK");
                }
            }
            catch (Exception ex)
            {
                await DisplayAlert("Check permissions failed", $"Can not check permissions for location. Error: {ex.Message}", "OK");
            }
            return false;
        }
    }
}
```

**Comment by paule96** [comment]
Maybe this are two issues:
1. The Method CrossPermissions.Current.CheckPermissionStatusAsync only should check permissions
2. PermissionStatus.Granted is not the truth on UWP plattform <- Maybe we change this title. 😄

**Comment by paule96** [comment]
Oh to the first issue I think I found the answer in the code.

in the file [Permissions.uwp.cs](https://github.com/jamesmontemagno/PermissionsPlugin/blob/master/src/Plugin.Permissions/Permissions.uwp.cs) in line 93 you call the method ``` await Geolocator.RequestAccessAsync();``` 


I think this go to the system and pop the dialog that ask for the permission. But this is currently placed in the method ```CheckPermissionStatusAsync```.


I have look in the documentation and it looks like a UWP app ask for the permission if you call any Method on the ```Geolocator``` class.
But here we have another problem. If the user answer no for the the only way to change this is to link in the settings of the OS. 

So it looks like we must implement something like this:

1. Try to find out if we run the permissions question for the first time.
2.1. If it not and we don't get access open the OS settings at the right place
2.2. If it the first time call something on the ```Geolocator``` class. Maybe ```RequestAccessAsync``` again.

**Comment by paule96** [comment]
Okay I have found the bug. It is in the method ```RequestPermissionsAsync``` in the file [Permissions.uwp.cs](https://github.com/jamesmontemagno/PermissionsPlugin/blob/master/src/Plugin.Permissions/Permissions.uwp.cs).


This return a dictionary in this all entry return ```PermissionStatus.Granted```. So we get allways granted without ask the system. I have help me with the replacement of the lines:
```csharp
 var results = await CrossPermissions.Current.RequestPermissionsAsync(Permission.Location);
                    Debug.WriteLine($"year we got a answer!");
                    //Best practice to always check that the key exists
                    if (results.ContainsKey(Permission.Location))
                        status = results[Permission.Location];
```

to this lines:


```csharp
status = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Location);
```

**Comment by theincredibleschnigges** [comment]
Will this be fixed in a future version?

**Comment by jamesmontemagno** [comment]
There is no API to check if permission has been granted, you can only request. It is what it is.

**Comment by JKennedy24** [comment]
> There is no API to check if permission has been granted, you can only request. It is what it is.

oh wow this if the first I have learnt of this. I guess this should be somewhere in the notes or `CheckPermission` should throw a not implemented on uwp?
