### ISSUE TITLE
calendar permission

### ISSUE THREAD

**Issue by wima75** [jamesmontemagno/PermissionsPlugin#115]
is there a workaround for the calendar permission problem in ios?

**Comment by tenneyb** [comment]
Wima75 are you running into an issue submitting to Apple App store, mine keeps getting rejected with the following? (and yes I have that key/string in my info.plist)
"Missing Purpose String in Info.plist File. Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSCalendarsUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string.If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more

**Comment by wima75** [comment]
Yes, exactly this problem. I think it is not so good, because my app does not use the calendar. I think some users don't want to install my app because of this permission.

**Comment by jamesmontemagno** [comment]
I have removed Calendar & Reminders from 4.0 which will be available soon.

**Comment by wima75** [comment]
Thank you. In the meantime I downloaded your source code, deleted all the stuff that I don't use and compiled myself ;-)

**Comment by jamesmontemagno** [comment]
:)
