### ISSUE TITLE
Xamarin.Forms Shared Project: Permissions Nuget installs but is not found.

### ISSUE THREAD

**Issue by hubert-associates** [jamesmontemagno/PermissionsPlugin#116]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 
Newest
Device Tested On:
Android
Simulator Tested On:
Version of VS: 
2017 newest
Version of Xamarin: 4.11

Versions of other things you are using:
PM> get-package

Id                                  Versions                                 ProjectName                                                                                                                                
--                                  --------                                 -----------                                                                                                                                
Newtonsoft.Json                     {11.0.2}                                 HxaUtilsStd                                                                                                                                
Xam.Plugin.Connectivity             {4.0.0.190-beta}                         HxaUtilsStd                                                                                                                                
WindowsAzure.Storage                {9.3.1}                                  HxaUtilsStd                                                                                                                                
NETStandard.Library                 {2.0.3}                                  HxaUtilsStd                                                                                                                                
Xamarin.Forms                       {3.2.0.729530-pre2}                      HxaUtilsStd                                                                                                                                
Newtonsoft.Json                     {11.0.2}                                 ClBle1                                                                                                                                     
Plugin.Permissions                  {3.0.0.12}                               ClBle1                                                                                                                                     
Xam.Plugin.Connectivity             {4.0.0.190-beta}                         ClBle1                                                                                                                                     
Plugin.BluetoothLE                  {6.2.0}                                  ClBle1                                                                                                                                     
NETStandard.Library                 {2.0.3}                                  ClBle1                                                                                                                                     
Xamarin.Forms                       {3.2.0.729530-pre2}                      ClBle1                                                                                                                                     
Microsoft.NETCore.UniversalWindo... {6.2.0-Preview1-26502-02}                ClBle1.UWP                                                                                                                                 
Newtonsoft.Json                     {11.0.2}                                 ClBle1.UWP                                                                                                                                 
Plugin.BluetoothLE                  {6.2.0}                                  ClBle1.UWP                                                                                                                                 
Plugin.Permissions                  {3.0.0.12}                               ClBle1.UWP                                                                                                                                 
Xam.Plugin.Connectivity             {4.0.0.190-beta}                         ClBle1.UWP                                                                                                                                 
Xamarin.Forms                       {3.2.0.729530-pre2}                      ClBle1.UWP                                                                                                                                 
Newtonsoft.Json                     {11.0.2}                                 ClBle1.iOS                                                                                                                                 
Plugin.BluetoothLE                  {6.2.0}                                  ClBle1.iOS                                                                                                                                 
Plugin.Permissions                  {3.0.0.12}                               ClBle1.iOS                                                                                                                                 
Xam.Plugin.Connectivity             {4.0.0.190-beta}                         ClBle1.iOS                                                                                                                                 
Xamarin.Forms                       {3.2.0.729530-pre2}                      ClBle1.iOS                                                                                                                                 
Newtonsoft.Json                     {11.0.2}                                 ClBle1.Android                                                                                                                             
Plugin.BluetoothLE                  {6.2.0}                                  ClBle1.Android                                                                                                                             
Plugin.Permissions                  {3.0.0.12}                               ClBle1.Android                                                                                                                             
Xam.Plugin.Connectivity             {4.0.0.190-beta}                         ClBle1.Android                                                                                                                             
Xamarin.Android.Support.Design      {27.0.2.1}                               ClBle1.Android                                                                                                                             
Xamarin.Android.Support.v4          {27.0.2.1}                               ClBle1.Android                                                                                                                             
Xamarin.Android.Support.v7.AppCo... {27.0.2.1}                               ClBle1.Android                                                                                                                             
Xamarin.Android.Support.v7.CardView {27.0.2.1}                               ClBle1.Android                                                                                                                             
Xamarin.Android.Support.v7.Media... {27.0.2.1}                               ClBle1.Android                                                                                                                             
Xamarin.Forms                       {3.2.0.729530-pre2}                      ClBle1.Android                                                                                                                             

### Steps to reproduce the Behavior
Based on your sample in Utils.cs in Portable project, I try to
using Plugin.Permissions;
using Plugin.Permissions.Abstractions;

but they are not found. They are found in other projects. In my Android: MainActivity.cs based on your sample I am not getting any requests for permission, Android 7 phone.

What can I try? Thanks for any tips!

I am trying to resolve this error:

09-05 11:13:14.761 D/BluetoothAdapter(16144): getLeState() returning 12
09-05 11:13:14.761 D/BluetoothAdapter(16144): STATE_ON
09-05 11:13:14.763 D/BluetoothAdapter(16144): getLeState() returning 12
09-05 11:13:14.795 D/BluetoothLeScanner(16144): onClientRegistered() - status=0 clientIf=6
09-05 11:13:14.795 D/BluetoothLeScanner(16144): mClientIf=0
09-05 11:13:14.820 W/Binder  (16144): Binder call failed.
09-05 11:13:14.820 W/Binder  (16144): java.lang.SecurityException: Need ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to get scan results
09-05 11:13:14.820 W/Binder  (16144): 	at android.os.Parcel.readException(Parcel.java:1683)
09-05 11:13:14.820 W/Binder  (16144): 	at android.os.Parcel.readException(Parcel.java:1636)
09-05 11:13:14.820 W/Binder  (16144): 	at android.bluetooth.IBluetoothGatt$Stub$Proxy.startScan(IBluetoothGatt.java:678)
09-05 11:13:14.820 W/Binder  (16144): 	at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper.onClientRegistered(BluetoothLeScanner.java:378)
09-05 11:13:14.820 W/Binder  (16144): 	at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:56)
09-05 11:13:14.820 W/Binder  (16144): 	at android.os.Binder.execTransact(Binder.java:570)
09-05 11:13:14.821 W/System.err(16144): java.lang.SecurityException: Need ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to get scan results
09-05 11:13:14.821 W/System.err(16144): 	at android.os.Parcel.readException(Parcel.java:1683)
09-05 11:13:14.821 W/System.err(16144): 	at android.os.Parcel.readException(Parcel.java:1636)
09-05 11:13:14.821 W/System.err(16144): 	at android.bluetooth.IBluetoothGatt$Stub$Proxy.startScan(IBluetoothGatt.java:678)
09-05 11:13:14.821 W/System.err(16144): 	at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper.onClientRegistered(BluetoothLeScanner.java:378)
09-05 11:13:14.821 W/System.err(16144): 	at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:56)
09-05 11:13:14.821 W/System.err(16144): 	at android.os.Binder.execTransact(Binder.java:570)
09-05 11:13:16.770 I/BluetoothLeScanner(16144): startRegisteration: mLeScanClients={md56e93a61007e9534b9b6779ca67ff3b68.LollipopScanCallback@72412c=android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper@ff190ad}

### Expected Behavior
Get request to enable permission

### Actual Behavior
Plugin not pluggable in shared part and do not get any request in the Android sub project.

### Code snippet
In my Android project MainActivity where the Permission Plugin can be installed and referenced I have:
in OnCreate:
          //https://github.com/jamesmontemagno/PermissionsPlugin
            Plugin.CurrentActivity.CrossCurrentActivity.Current.Init(this, bundle);

and then below:
        public override void OnRequestPermissionsResult(int requestCode, string[] permissions, [GeneratedEnum] Android.Content.PM.Permission[] grantResults)
        {
            PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
            base.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }

And 
### Screenshots

THANKS!

**Comment by jamesmontemagno** [comment]
Did you add the nuget to your Android project?

**Comment by hubert-associates** [comment]
Yes I did. I followed the instructions in your Readme to a T I believe and then I moved to the sample code. weird. Your Connectivity Plugin works fine in this app.

**Comment by jamesmontemagno** [comment]
Do you have a small sample app that I can look at?

**Comment by hubert-associates** [comment]
Thanks. The following works (looks like at least, still testing) but is without your plugin, same issues with your pluggin. Sample. Oh gosh, my app is large and private at the moment. I'll have to see if I can remove the private aspects and make it work at all...

                if (Build.VERSION.SdkInt >= BuildVersionCodes.M)
                {
                    int YOUR_ASSIGNED_REQUEST_CODE = 9;
                    if (Android.Support.V4.Content.ContextCompat.CheckSelfPermission(context, Manifest.Permission.AccessCoarseLocation) == (int)Android.Content.PM.Permission.Granted)
                    {
                        //Permission is granted, execute stuff   
                    }
                    else
                    {
                        Android.Support.V4.App.ActivityCompat.RequestPermissions(_parentContext, new string[] { Manifest.Permission.AccessCoarseLocation }, YOUR_ASSIGNED_REQUEST_CODE);
                    }
                }

**Comment by jamesmontemagno** [comment]
Could you do file > new and let me know....

**Comment by hubert-associates** [comment]
The above seems to work fine so no longer attempting to use the plugin. Thanks!
