### ISSUE TITLE
Invite user again to accept permission through RequestPermissionsAsync()

### ISSUE THREAD

**Issue by Goldstrike** [jamesmontemagno/PermissionsPlugin#119]
Hello,

I would like to know if there is a way to prompt user again when he has denied the permission a first time?

In our app, the user could accept or deny the geolocation related to a declaration through a switch.

So we call RequestPermissionsAsync() during the first declaration, but if the user doesn't allow geolocation, we would like that he can get the prompt again, if he changes the switch status.

Is it possible, or only through the app settings?

**Comment by jamesmontemagno** [comment]
It is possible on Android, but not on iOS as you only get one chance.

**Comment by Goldstrike** [comment]
Thanks for your feedback James. In add, it seems that on Android it depends on the version: with the 5.1, you only get one chance too.
