### ISSUE TITLE
Support Fragment.html.OnRequestPermissionsResult

### ISSUE THREAD

**Issue by kjeremy** [jamesmontemagno/PermissionsPlugin#12]
## Feature Request:

I use permissions per fragment instead of by activity.  It would be useful to support permissions per fragment as well as per activity.

**Comment by jamesmontemagno** [comment]
I think that the activity hosting the fragments should be able to handle it? Else can you create a small repo for me and I can see what could be done as that is a tricky one.

**Comment by jamesmontemagno** [comment]
I just tested this out in the sample. If your fragment calls to request permission using the library it will be routed to the parent activity to handle. So no real need at all for this feature how I see it.
