### ISSUE TITLE
App minimizes after permission granted/denied dialog close

### ISSUE THREAD

**Issue by mnesser** [jamesmontemagno/PermissionsPlugin#121]
Issue:
Using Xamarin android.
After prompting the user for permissions, the app “minimizes”/ goes to background. 

From an activity, I call helper class to check / ask for permissions.
When the user clicks allow / deny the dialog closes and the app minimizes. 
Also sometimes, the permission prompt dialog appears “behind” the running app.

Any suggestions?

code used for checking.. 
```
private async Task<bool> GetCheckLocationPermissions()
{
	try
	{
		var status = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Location);
		if (status != PermissionStatus.Granted)
		{
			var results = await CrossPermissions.Current.RequestPermissionsAsync(Permission.Location);
			if (results.ContainsKey(Permission.Location))
				status = results[Permission.Location];
		}

		if (status == PermissionStatus.Granted)
			return true;
		if (status != PermissionStatus.Unknown)
			return false;
	}
	catch (Exception ex)
	{
		return false;
	}

	return false;
}
```

Update: same issue on the "native" Activity.RequestPermissions().

**Comment by jamesmontemagno** [comment]
I have no issues with this and can't reproduce.
