### ISSUE TITLE
RequestPermissionsAsync just returns the current permission status (iOS - location permission)

### ISSUE THREAD

**Issue by wnbittle** [jamesmontemagno/PermissionsPlugin#124]
On iOS I've noticed that if I deny the location permission that is prompted by RequestPermissionsAsync that subsequent calls of this method with the same permissions no longer "prompt" the user, but instead just return the current status of the permission.  On android the behavior is what I would expect, regardless of the decision the user made regarding the permission before, RequestPermissionsAsync will always prompt the user to allow or deny.

In my case I'm only using the Location permission, so other permissions may not have this problem.

Am I misunderstanding the API's function, or is this the behavior of iOS, or is this a legit bug?

## Bug Information

Version Number of Plugin: 3.0.0.12
Device Tested On: iOS Simulator (MacBook Pro)
Simulator Tested On: iPhone 8 iOS 11.4
Version of VS: 2017 (15.8.6)
Version of Xamarin:
Versions of other things you are using:

### Steps to reproduce the Behavior
1. (on iOS) Request for the location permission
2. Deny the permission via the prompt UI
3. Request for the permission again

### Expected Behavior
Regardless if the user has denied or allowed the permission, I would expect the RequestPermissionAsync method to prompt the user (since we can get the current status of the permission via CheckPermissionStatusAsync.

### Actual Behavior
No user notification is presented and the current permission status (denied) is returned.

### Code snippet
I believe [this is the problem] in my particular case.  I didn't investigate other permissions for this issue.(https://github.com/jamesmontemagno/PermissionsPlugin/blob/master/src/Plugin.Permissions/Permissions.ios.cs#L210)

**Comment by jcmanke** [comment]
That is iOS behavior. It will only present the system dialog to the user one time. If they denied you the permission, you will need to prompt them to change the permission from the Settings app, all subsequent attempts in-app will simply return the current setting.

**Comment by jamesmontemagno** [comment]
^ yup!
