### ISSUE TITLE
RequestPermissionsAsync crash on iOS for cossplatform Xamarin.Forms app

### ISSUE THREAD

**Issue by akshay-aress** [jamesmontemagno/PermissionsPlugin#125]
## Bug Information

Version Number of Plugin: 3.0.0.12
Device Tested On:  iphone 6s (iOS 11.4)
Simulator Tested On:  none
Version of VS: VS community 7.6
Version of Xamarin: Xamarin.Forms 3.2.0.729530-pre
Versions of other things you are using: Xamarin.iOS 11.14.0.13

### Steps to reproduce the Behavior
- Install app
- try to access the camera 
- permission popup will be shown deny camera permission 
- and then try code given in code snippet

### Expected Behavior
The app should not crash after calling RequestPermissionsAsync, it must show request permission popup and then allow a user to select permission option

### Actual Behavior
The app is crashing after calling RequestPermissionsAsync
### Code snippet

var status = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Camera);
if (status == PermissionStatus.Denied)
 {
       if (await CrossPermissions.Current.ShouldShowRequestPermissionRationaleAsync(Permission.Camera))
         {
               await DisplayAlert("Need camera", "camera", "OK");
         }

         var results = await CrossPermissions.Current.RequestPermissionsAsync(Permission.Camera);
         status = results[Permission.Camera];
}

**Comment by hagronnestad** [comment]
I can confirm this issue. My app crashes when calling `RequestPermissionsAsync`. It seems like the plugin also always returns `PermissionStatus.Unknown` when using `CheckPermissionStatusAsync` on iOS.

Log:
```
2018-10-11 15:58:54.760 App.iOS[1082:135356] critical: 	1   libsystem_platform.dylib            0x00000001bebaaa20 <redacted> + 56
2018-10-11 15:58:54.760 App.iOS[1082:135356] critical: 	2   libsystem_kernel.dylib              0x00000001beb2d838 <redacted> + 100
2018-10-11 15:58:54.760 App.iOS[1082:135356] critical: 	3   libsystem_kernel.dylib              0x00000001beb2d868 fcntl + 0
2018-10-11 15:58:54.760 App.iOS[1082:135356] critical: 	4   TCC                                 0x00000001c1df0b80 <redacted> + 0
2018-10-11 15:58:54.760 App.iOS[1082:135356] critical: 	5   TCC                                 0x00000001c1df0ab4 <redacted> + 0
2018-10-11 15:58:54.760 App.iOS[1082:135356] critical: 	6   TCC                                 0x00000001c1df4c5c <redacted> + 276
2018-10-11 15:58:54.760 App.iOS[1082:135356] critical: 	7   libxpc.dylib                        0x00000001bebfe514 <redacted> + 60
2018-10-11 15:58:54.761 App.iOS[1082:135356] critical: 	8   libxpc.dylib                        0x00000001bebf1b3c <redacted> + 88
2018-10-11 15:58:54.761 App.iOS[1082:135356] critical: 	9   libdispatch.dylib                   0x00000001be9d8504 <redacted> + 16
2018-10-11 15:58:54.761 App.iOS[1082:135356] critical: 	10  libdispatch.dylib                   0x00000001be9908c4 <redacted> + 320
2018-10-11 15:58:54.761 App.iOS[1082:135356] critical: 	11  libdispatch.dylib                   0x00000001be988874 <redacted> + 1288
2018-10-11 15:58:54.761 App.iOS[1082:135356] critical: 	12  libsystem_pthread.dylib             0x00000001bebba100 _pthread_wqthread + 328
2018-10-11 15:58:54.761 App.iOS[1082:135356] critical: 	13  libsystem_pthread.dylib             0x00000001bebbcd00 start_wqthread + 4
2018-10-11 15:58:54.761 App.iOS[1082:135356] critical: 
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
```

**Comment by hagronnestad** [comment]
In my case it was the `Permission.MediaLibrary` permission that caused the `SIGABRT` error. I see that this permissions has been removed in the latest commit (90ca6ccee22b2e4feb42917fcc99b22bb33d4ce7). Would it be possible to update the Nuget-package?

**Comment by akshay-aress** [comment]
I am facing this issue with Permission.Camrea

**Comment by akshay-aress** [comment]
Yes, all settings are done as per the instructions given in the readme

**Comment by IlyaLehchylin** [comment]
Same, crash on RequestPermissionsAsync without possibility to catch the error. Tested Camera and Microphone permissions.

Version Number of Plugin: 4.0.1-beta, 3.0.0.12
Device Tested On: iPhone SE
Version of VS: VS Community for Mac, 7.6.9 (build 22)
Version of Xamarin: Xamarin.Forms 3.2.0.637442-pre1

**Comment by ericmaia** [comment]
I am also getting this problem (or a similar one) with the Camera permissions on Xamarin.iOS. If the permissions have been Denied, then the RequestPermissionsAsync does not return and the app hangs or crashes. I do not have this problem with the Photos permission.

**Comment by MichaelLant** [comment]
I am facing the same issue. I can retrieve all permissions that I have tried, but I cannot retrieve permissions with for the camera. The problem exists on iOS, but everything seems to work correctly for Android. To be clear, I have added the required plist permissions per this article: https://blog.xamarin.com/plugin-permission-changes-ios-11/

**Comment by MichaelLant** [comment]
Further to the above, here are the keys I am using the Info.plist:
  <key>NSCameraUsageDescription</key>
  <string>This app needs access to the camera to take photos.</string>

  <key>NSPhotoLibraryAddUsageDescription</key>
  <string>This app needs access to save photos to your library.</string>
  
  <key>NSPhotoLibraryUsageDescription</key>
  <string>This app needs access to read photos from your library.</string>

  <key>NSBluetoothPeripheralUsageDescription</key>
  <string>This app needs access to read photos from your library.</string>
  
  <key>NSMicrophoneUsageDescription</key>
  <string>This app needs microphone for video</string>

**Comment by MichaelLant** [comment]
Update...

So here is a way that I have discovered that makes it work. The failure was on 

`await CrossMedia.Current.Initialize();`

It failed on iOS only. However, if on iOS, I force Intilalize() to run on the UI thread, it works. Here is an example:

`            switch (Device.RuntimePlatform)
            {

                /* The following is a workaround for CrossMedia.Current.Initialize() 
                 * When using iOS, the Initialize call must be forced to the UI thread.
                 * Failing to do so will cause the call to silently fail and boot the
                 * processing flow out to the calling method. This is an undocumented hack. */
                case Device.Android:
                    {
                        await CrossMedia.Current.Initialize();
                        IsCameraEnabled = await CheckPermissionStatusAsync(Permission.Camera);
                        break;
                    }
                case Device.iOS:
                    {
                        Device.BeginInvokeOnMainThread(async() =>
                        {
                            await CrossMedia.Current.Initialize();
                            IsCameraEnabled = await CheckPermissionStatusAsync(Permission.Camera);
                           
                        });
                        break;
                    }
            }
`

This was a last-ditch effort before I abandoned the entire CrossMedia approach and looked for another solution.

Hopefully this will help others.

**Comment by liu12010** [comment]
I met the same problem but requesting Location Permission :(
but totally success when request the camera permission.
I had added 
Location When In Use Usage Description and also Location Always Usage Description.
It still can't go through the 
`await CrossPermissions.Current.RequestPermissionsAsync(new[] { Permission.Location });`
Are there any solution or suggestion?

**Comment by akshay-aress** [comment]
Thanks Michael, Your suggestion will help us all, but now I have updated Xamarin.Forms version of My application to 3.4.0 and now I am not able to reproduce this issue any more with my App. May be this issue was related to Xamarin.Forms so I will suggest to upgrade Xamarin.Forms version to 3.4 and try whether it solves this issue in your respective projects. If you have any other stable solution for getting device permission please share it with us

**Comment by MichaelLant** [comment]
Hi Akshay,

Thanks for the feedback. I am using Xamarin Forms 4.0.0.94569-pre3, so I am already ahead of the 3.4.0 release that you are suggesting. It could be that whatever was the problem that was resolved in 3.4.0 was reintroduced in 4.0.

**Comment by akshay-aress** [comment]
Great, closing this issue as I am not able to reproduce this anymore, thank you guys for your support.

**Comment by jerryqburst** [comment]
update plist with following
` <key>NSLocationWhenInUseUsageDescription</key>
    <string>This app needs access location when open.</string>
    <key>NSLocationAlwaysUsageDescription</key>
    <string>This app needs access to your location.</string>
    <key>NSLocationUsageDescription</key>
    <string>This app needs access to your location.</string>
    <key>NSLocationAlwaysAndWhenInUsageDescription</key>
    <string>This app needs access to your location.</string> 
    <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
    <string>This app needs access to your location.</string>`

**Comment by MarcAlx** [comment]
What helped me solving this issue (in 3.0.0.12) :

- Ensure that the Permission I request matches Info.plist (read Permission description)
- (very odd one) Remove break point on `CrossPermissions.Current.RequestPermissionsAsync` as stepping with debugger (iOS real device + Visual studio macOS up to date) causes this bug. (You can still use break points before this call or after status is returned).

Other info : 
- I was using Xam.Plugin.Media, so I removed reference to this plugin as Xam.Plugin.Media already bundled it. (not sure if it solved anything, but worth mentioning it)
- My code is in runned on MainThread via `Device.BeginInvokeOnMainThread` its more related to my needs than to this problem.

PS I was working with Location permission.

**Comment by Eltee-Taiwo** [comment]
Thanks a lot @MarcAlx . Using break points and stepping through my code is what was breaking it :/
