### ISSUE TITLE
Permission Enum in Version 4.0.1 Beta is not Backwards compatible

### ISSUE THREAD

**Issue by inforithmics** [jamesmontemagno/PermissionsPlugin#126]
I updated the Permission.Plugin to the newest Beta Version 4.0.1 Beta in a Project that uses Xam.Plugin.Media than when I wanted to Take a picture a Permission.Contacts Permission was requested instead of a Permission.Camera Permission.

I downgraded the Permission.Plugin to 3.0.0.12 and taking a picture worked again.

I think because in the newer Version some Enums where removed, the enum values changed. And so instead of Camera it requests Contacts.

## Bug Information

Version Number of Plugin: 4.0.1-Beta
Device Tested On: Samsung SM-T580
Simulator Tested On:
Version of VS: Visual Studio 2017 15.8.8
Version of Xamarin: 3.3.0.912540
Versions of other things you are using: 
Xam.Plugin.Media 4.0.1.5

### Steps to reproduce the Behavior
1. Create Xamarin Forms project with Permission.plugin and Xam.Plugin.Media
2. Update Permission.Plugin to beta version
### Expected Behavior
Permission for using Camera is requested. 
### Actual Behavior
Permission for using Contacts is requested.
### Code snippet
```
var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
{
        SaveToAlbum = true,
        CompressionQuality = quality,
        CustomPhotoSize = 50,
        PhotoSize = PhotoSize.MaxWidthHeight,
        MaxWidthHeight = 2000,
        DefaultCamera = CameraDevice.Rear,
}).ConfigureAwait(true);
```

**Comment by jamesmontemagno** [comment]
This is known currently and I am going to adjust some thing in the next release. Please don't use it yet.

**Comment by jamesmontemagno** [comment]
Fixing in next beta
