### ISSUE TITLE
Can not resolve reference Plugin.Permissions

### ISSUE THREAD

**Issue by aparsaeeyan** [jamesmontemagno/PermissionsPlugin#130]
I get this error when use of Plugin.Permissions in xamarin.forms:

Can not resolve reference: `Plugin.Permissions`, referenced by `Resaman`. Please add a NuGet package or assembly reference for `Plugin.Permissions`, or remove the reference to `Resaman`.	Resaman.Android			

but I added plugin.permission in all Projects (Forms, android, ios)

**Comment by acaliaro** [comment]
closed and reopened the projects seems to solve the problem
