### ISSUE TITLE
ios locator track does not appear in settings

### ISSUE THREAD

**Issue by matanist** [jamesmontemagno/PermissionsPlugin#131]
## Bug Information
I've added the following to the infoplist file for location permissions.
   ```
 <key>NSLocationAlwaysUsageDescription</key>
    	<string>Permission Location</string>
    	<key>NSLocationWhenInUseUsageDescription</key>
    	<string>Permission</string>
```
But the emulator also does not appear in the settings

Like Image (Link) https://ibb.co/4jrHzxM
I'm using Plugin.Permission. 
What am I missing out on?

Version Number of Plugin: 3.0.0.12

Simulator Tested On: Android (OK)
iOS (Fail)
Version of VS: Visual Studio 2017 Enterprise 
Version of Xamarin:  3.4.0.1029999

### Expected Behavior
Location permissions in ios settings

**Comment by jamesmontemagno** [comment]
I believe only after you set it? idk it works for me you may have to do it on device.
