### ISSUE TITLE
check & requesting Calendar Permission seems to not work on Android

### ISSUE THREAD

**Issue by KorbinianMossandl** [jamesmontemagno/PermissionsPlugin#133]
## Bug Information

Version Number of Plugin: 4.0.2 beta
Device Tested On: Huawei p10 android 8
Simulator Tested On: 
Version of VS: 15.8.9
Version of Xamarin: 3.3.0.967583
Versions of other things you are using:

### Steps to reproduce the Behavior
try to check or request calander permission on android
### Expected Behavior
correct result and/or permission pop up
### Actual Behavior
wrongly returns Granted for calendar permission while app will crash afterwards claming clandar permission is not granted
### Code snippet
await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Calendar);
await CrossPermissions.Current.RequestPermissionsAsync(Permission.Calendar);

**Comment by KorbinianMossandl** [comment]
OK, looking at the commits i found out that you disabled Calendar. would be nice to say so in the readme. reverting to the old version solved it for me.

**Comment by jamesmontemagno** [comment]
Adding back only for Android in 4.X... it is removed for iOS due to apple thinking we are using the APIs so had to remove it here.

See 4.0.3-beta
