### ISSUE TITLE
ShouldShowRequestPermissionRationaleAsync returns false but it should return true

### ISSUE THREAD

**Issue by bluekuen** [jamesmontemagno/PermissionsPlugin#135]
## Bug Information

Version Number of Plugin: v 3.0.0.12
Device Tested On: Android
Simulator Tested On:
Version of VS: professional 15.9.6
Version of Xamarin: 3.5.0.129452
Versions of other things you are using: android 8.0.0

### Steps to reproduce the Behavior
no permissions have been granted.
App starts the first time.

### Expected Behavior
ShouldShowRequestPermissionRationaleAsync returns true because rationale didn't show before.
### Actual Behavior
ShouldShowRequestPermissionRationaleAsync  returns false
### Code snippet
```
if (Device.RuntimePlatform == Device.Android)
                {
                    var status = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Location);
                    if (status != PermissionStatus.Granted)
                    {
                        if (await CrossPermissions.Current.ShouldShowRequestPermissionRationaleAsync(Permission.Location))
                        {
                            await UserDialogs.Instance.AlertAsync(AppResources.LocationForBleScanAndConnectNeededMessage, okText: AppResources.OK);
                        }
                        else
                        {
                            var goToSettings = await UserDialogs.Instance.ConfirmAsync(
                                       AppResources.GoToSettingsQuestion, AppResources.LocationPermissionNeeded, AppResources.OK, AppResources.Cancel);
                            if (goToSettings)
                            {
                                mobileDeviceManager.GoToAppSettings();
                            }
                        }
                        var results = await CrossPermissions.Current.RequestPermissionsAsync(Permission.Location);
                        //Best practice to always check that the key exists
                        if (results.ContainsKey(Permission.Location))
                            status = results[Permission.Location];
                    }
                    if (status != PermissionStatus.Granted)
                    {
                        return;
                    }
                }
```

**Comment by jamesmontemagno** [comment]
Android controls this, and would be after the user declined usually the first time.

**Comment by bluekuen** [comment]
shouldn't it only be false when the permission is granted or when the user checks "don't show again", right?

**Comment by jamesmontemagno** [comment]
https://developer.android.com/reference/android/support/v4/app/ActivityCompat.html#shouldshowrequestpermissionrationale

So it would be:

* First Check: False
* Prompt for permission check
* User deny's permission
* Second Check: True

**Comment by dcbrilho** [comment]
Dear James Montemagno,

Would a second call to RequestPermissionsAsync be enough to prompt again for permissions, before getting a 'true' result on ShouldShowRequestPermissionRationaleAsync? 

On my tests:

CheckPermissionStatusAsync(Permission.Location) -> Denied
ShouldShowRequestPermissionRationaleAsync(Permission.Location) -> false
CheckPermissionStatusAsync(Permission.Location) -> Denied (again)
ShouldShowRequestPermissionRationaleAsync(Permission.Location) -> (again)

What are we missing?

Tests environment:
- LG K10 [new model]
- Android 7.0
- Location permission previously denied with “don’t show again” option checked

Regards,

Daniel Brilho

**Comment by jamesmontemagno** [comment]
Android controls this and i just return it based on it.
