### ISSUE TITLE
Apple rejects our binaries because of references to Location

### ISSUE THREAD

**Issue by unamed000** [jamesmontemagno/PermissionsPlugin#136]
When i submit my app to Apple to validate, i received App Store connect warning about that my app is missing NSLocationAlwaysUsageDescription.

The problem is doesn't use any of these permissions, but because the my app is references to Plugin.Permission and Plugin.Permission is referenced to some of LocationManager of iOS SDK, so they're forcing us to have a string in Info.plist file.

But if we put the string into Info.plist file, our App in AppStore will always show something like : "This app may use your location even when it isn't open, which can decrease device battery life". And this will definitely not making the client happy.

More worse, some of other libraries is referenced to this package unfortunately, so i have to copy and paste these libraries in our app and clone this package.

So my suggestion is we should split the permissions in this package into smaller package for avoiding unnecessary permission references. Something like Plugin.Permission.Core and Plugin.Permission.Camera - Plugin.Permissions.Location for example

**Comment by KalyanXamarin** [comment]
@jamesmontemagno any updates on this?

**Comment by stoff99** [comment]
@jamesmontemagno 
Hi we have the same problem here:

Here the Mail from apple after the binary upload:

Dear Developer,
We identified one or more issues with a recent delivery for your app, "SOME APP NAME". Please correct the following issues, then upload again.Missing Purpose String in Info.plist File - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSCalendarsUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

Though you are not required to fix the following issues, we wanted to make you aware of them:Missing Purpose String in Info.plist File - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

Missing Purpose String in Info.plist File - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationWhenInUseUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

Best regards,The App Store Team 


Which means we need to add:
NSCalendarsUsageDescription
NSLocationAlwaysUsageDescription
NSLocationWhenInUseUsageDescription

??

Thx Stefan

**Comment by stoff99** [comment]
Did somebody tried the Beta 4.0.4 build already?
I can't find here any release / update notes.

**Comment by jamesmontemagno** [comment]
Interesting.... I am back from holiday and will look at it this week. 

If you add all of the Descriptions into the info.plist does it go away?

**Comment by stoff99** [comment]
Hey @jamesmontemagno , welcome back from holiday. Hope you had a good time ;)
Yesterday i played a bit with the store upload. I added just the Calendar description now.

I just saw it today in the mail: For the NSCalendarsUsageDescription they wrote "Please correct the following issues"
For the location they wrote "Though you are not required to fix the following issues, we wanted to make you aware of them".

I have just added the calendar now and the app is in review with the other 2 warnings.
I just know it from the past, Apple can be annoying when you have the usage descriptions for features which you are not using.

I will tell you in some hours or days when the review is done.

Thx a lot for your work,
and greetings from austria.

**Comment by unamed000** [comment]
> Interesting.... I am back from holiday and will look at it this week.
> 
> If you add all of the Descriptions into the info.plist does it go away?

Hi @jamesmontemagno 
The problem is we can't just add everything into Info.plist

If we add all descriptions into Info.plist, then App Store will tell user something like : "ABC app may use your Location when you're not using the app" or something similar than that. Users will feel like they're being spy although our app doesn't use any user's location.
Not to mention that we're references a lot of permissions in the Plugins. And the customers will not be happy about that.

**Comment by stoff99** [comment]
> And if we don't add the descriptions correctly, Apple would be annoying and make the reviewing steps longer than expected.

Thats the real problem! Yes :)

You don't need to add the location description but apple will ask you for sure whats going on here, depends on which reviewer you will get ;)

**Comment by luveti** [comment]
I'm having this issue as well. Maybe wrapping everything up in preprocessor directives and having a bunch of symbols could help?

Changes to code:

```csharp
// ...
#if (INCLUDE_CONTACTS)
PermissionStatus ContactsPermissionStatus
{
    get
    {
        var status = ABAddressBook.GetAuthorizationStatus();
        switch (status)
        {
            case ABAuthorizationStatus.Authorized:
                return PermissionStatus.Granted;
            case ABAuthorizationStatus.Denied:
                return PermissionStatus.Denied;
            case ABAuthorizationStatus.Restricted:
                return PermissionStatus.Restricted;
            default:
                return PermissionStatus.Unknown;
        }
    }
}
#else
PermissionStatus ContactsPermissionStatus = PermissionStatus.Unknown;
#endif
// ...
```

The default nuget package would have all of these added to `Project Settings > Build > Compiler > Define Symbols`. Developers who don't want to include these can just clone the repo and compile it themselves excluding the symbols they don't need.

**Comment by jamesmontemagno** [comment]
Works is in progress on PR #137, it is a huge change. There will be a new API that will need to be adopted for things to be fully linker safe for everyone, however it is not a breaking change for existing apps, but you will need to update to ensure that the linker kicks in on iOS/Android to remove things. Hopefully will have it done an in beta this weekend.

**Comment by josesimas** [comment]
Hi @jamesmontemagno,

Just to add one more data point. Our app uses the location plugin and only requires the location while it is running. It has worked like that for several months. Now, suddenly, the location stopped working with a location not granted error even on the version that is in the app store.
I tried following the advice by Apple (we also got their warning email) but it does not solve the problem. I am looking forward to this change but there may be more underneath it (or I am doing something really dumb somewhere).

**Comment by psharrma** [comment]
Hi @jamesmontemagno ,

Any ETA on when you can merge it and release a new version?

**Comment by jamesmontemagno** [comment]
Now that build is over, i should be able to get it done this week :) I will atleast have it in preview, and update my other libraries to have a dependency on the new API.

**Comment by jamesmontemagno** [comment]
Shipping 5.0 today to beta and updating my plugins that use it

**Comment by conrad90909** [comment]
Thanks for your hard work..but I just tried uploading to the App Store with the version 5.0 beta, and I’m still getting the same outcome James. “Info.plist file should contain a NSLocationAlwaysUsageDescription key“ I’m off to double check nothing else might be causing it in my code, has the fix worked for others??

**Comment by jamesmontemagno** [comment]
I have also updated my Geolocator and Media Plugins to new beta pacakges.

If you use Geolocator you will need that in there as the code uses both of them. If you aren't then you would want to use Xamarin.Essentials as it only uses "WhenInUse"

**Comment by jamesmontemagno** [comment]
Also, i completely changed the API... so read the readme

**Comment by conrad90909** [comment]
Thanks @jamesmontemagno you hit the nail on the head, I'm an idiot... I am using the geolocator plugin!  We also have the Xamarin.Essentials for something else so I might make the effort now and migrate to it for geolocation.

**Comment by jamesmontemagno** [comment]
Will be the easiest migration ever :)

**Comment by conrad90909** [comment]
> Will be the easiest migration ever :)

Yeah, you're right, I also swapped over DeviceInfo, thanks for the great plugins!
