### ISSUE TITLE
PermissionsImplementation does not exist

### ISSUE THREAD

**Issue by salmankaludi** [jamesmontemagno/PermissionsPlugin#138]
Hi,

i have added the plugin in pcl and droid project and when i have added the below code

public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)
        {
            PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }

it is not working throwing the errror PermissionsImplementation does not exists.

Can you please help on this?

Thanks

**Comment by jamesmontemagno** [comment]
What version of android are you compiling against? make sure it is the most recent and remove and re-add it to your android project.

**Comment by salmankaludi** [comment]
I have tried with android 6.0 Marshmallow and Android 8.1 Oreo.

**Comment by jamesmontemagno** [comment]
Closing as it works fine on every project. make sure you install the nugets. You can give me a sample app then i can test it.
