### ISSUE TITLE
CheckPermissionStatus not working Latest xamarin.forms version

### ISSUE THREAD

**Issue by muhammetsahin** [jamesmontemagno/PermissionsPlugin#139]
I'm using Xamarin.Forms version 3.6.0.344457 and Plugin Permission version 3.0.0.12

Here is my code

` if (await P.Current.CheckPermissionStatusAsync(Permission.Camera) == PermissionStatus.Granted)
            {
                return result = await TakePhotoLabel();
            }`

But both ios and android not working.

Before check permission i already request permission and give permission to access camera

![image](https://user-images.githubusercontent.com/2045788/56691684-3b4fa800-66e9-11e9-9102-09a2de203ea8.png)

` var permissionResult = await P.Current.RequestPermissionsAsync(Permission.Camera);`

![R9OV9T3bsh](https://user-images.githubusercontent.com/2045788/56691669-325ed680-66e9-11e9-9160-947d97eff794.gif)

I manually give camera permission it is working.

**Comment by jamesmontemagno** [comment]
Did you initialize everything correct: https://github.com/jamesmontemagno/PermissionsPlugin#android-specific-in-your-baseactivity-or-mainactivity-for-xamarinforms-add-this-code
