### ISSUE TITLE
Android : Where to request permissions?

### ISSUE THREAD

**Issue by omatrot** [jamesmontemagno/PermissionsPlugin#141]
My Xamarin Android app is composed of a splash screen activity, a login activity and a main activity.
I'm wondering where I should ask for permissions?
For me it has to be on application startup outside any custom activity. Am I wrong about this?
I would be tempted to use the plugin in MainApplication.cs. Can I do that? If not should I create a specific activity to request permissions?
Also a sample with external storage access would be a plus.

**Comment by jamesmontemagno** [comment]
That is up to you, I only like to call them before I need them. Some apps display a nice welcome screen to request permissions if they are required.
