### ISSUE TITLE
Notifications permissions

### ISSUE THREAD

**Issue by adrianknight89** [jamesmontemagno/PermissionsPlugin#144]
Looking at the `Permission` enum, I don't see a way to request notifications permission for sending push notifications. Am I missing something or does this feature need to be implemented?

```
    public enum Permission
    {
        Unknown = 0,
        Calendar = 1,
        Camera = 2,
        Contacts = 3,
        Location = 4,
        Microphone = 5,
        Phone = 6,
        Photos = 7,
        Reminders = 8,
        Sensors = 9,
        Sms = 10,
        Storage = 11,
        Speech = 12,
        LocationAlways = 13,
        LocationWhenInUse = 14,
        MediaLibrary = 15
    }
```

**Comment by jamesmontemagno** [comment]
This is a very complex API and only is needed on iOS so I don't intend to add this in at all. You can see how I do it here:

https://github.com/xamarinhq/app-conference/blob/master/src/Conference.iOS/Helpers/PushNotifications.cs
