### ISSUE TITLE
Error XA2002: Can not resolve reference: `Plugin.Permissions.Abstractions`. Please add a NuGet package or assembly reference for `Plugin.Permissions.Abstractions`. (XA2002) 

### ISSUE THREAD

**Issue by khadeeja-alif** [jamesmontemagno/PermissionsPlugin#145]
Version Number of Plugin: 3.0.0.12
Device Tested On: Android & iOS , All Devices
Version of VS:  VS community for mac - version 8.1.4
Version of Xamarin: 
Xamarin.iOS - 12.10.0.157
Xamarin.Android - 9.3.0.23
Xamarin Forms - 3.2.0.839982

### Steps to reproduce the Behavior
On Project Build.

### Expected Behavior
Build Successfully. And Run App.

### Actual Behavior
Gives the following error:
Error XA2002: Can not resolve reference: `Plugin.Permissions.Abstractions`. Please add a NuGet package or assembly reference for `Plugin.Permissions.Abstractions`. (XA2002)

**Comment by xmesaj2** [comment]
I managed to workaround it this way
Add `Plugin.Permissions.Abstractions.csproj` to your solution
Change `TargetFramework` to `4.6` (from `5.0`) and type `Profile119` for `TargetFrameworkVersion` in csproj
Let VS install what it wants
reset the csproj to default config with 5.0
