### ISSUE TITLE
Issue to have the plugin correctly on Android

### ISSUE THREAD

**Issue by pochocosta** [jamesmontemagno/PermissionsPlugin#147]
Issue to have the plugin correctly working on Android

I made the Android Current Activity Setup in my MainActivity. I added the OnRequestPermissionsResult too.

I'm compiling against Android 9 and my in my android manifest I have the following:

android:minSdkVersion="21" 
android:targetSdkVersion="28"

My problem is that when I allow the permision on the app the OnRequestPermissionsResult doesn't fire

**Comment by jamesmontemagno** [comment]
Would need a sample to see what is going on...

**Comment by pochocosta** [comment]
Hi, thanks!
I was able to solve my problem changing the place of the hook to a correct base controller.

I will close the issue.
