### ISSUE TITLE
ShouldShowRequestPermissionRationaleAsync in the new api

### ISSUE THREAD

**Issue by mierzynskim** [jamesmontemagno/PermissionsPlugin#148]
I'd like to ask if there's any reason why `ShouldShowRequestPermissionRationaleAsync` method still takes `Permission` enum as parameter. I think it's not consistent with `RequestPermissionAsync<T>` and `CheckPermissionStatusAsync<T>` declarations.

**Comment by jamesmontemagno** [comment]
Because it doesn't cause linker issues at all because iOS has no concept of this.
