### ISSUE TITLE
Android Location Permission Not Awaiting Response.

### ISSUE THREAD

**Issue by conrad90909** [jamesmontemagno/PermissionsPlugin#149]
Hi James,

I am having some issues with the permissions plugin on Android, specifically version 5 beta.   When using your code exactly as in the readme (see my GitHub sample below, basically your sample code updated to use version 5.0.0) the application doesn't wait for a response to this line:

**status = await CrossPermissions.Current.RequestPermissionAsync<LocationPermission>();**

 The request for location is approved/dissaproved based on your response, so the second time I go try the request everything seems fine, but that line just seems to cause the application to jump out of the active code, there are no exceptions thrown or anything.  The same works perfectly on iOS so it is Android specific.

## Bug Information

Version Number of Plugin: 5.0.0 beta
Device Tested On: Samsung SM-G965F (API 28)
Simulator Tested On: N/Z
Version of VS: Visual Studio Mac (8.1.5 build 9)
Version of Xamarin: Xamarin.Mac Version: 5.10.0.157

### Steps to reproduce the Behavior
Run application in working sample, only works first time assuming you accept the request for location.

### Expected Behavior
Should proceed to next line and check if the permission is now granted before requesting the location and displaying it.

### Actual Behavior
Phone asks for permissions to get location but application jumps out of debugged code with no exceptions or issues thrown, permission is now granted so you can try again and everything will work now.

### Code snippet
https://github.com/conrad90909/PermissionsPlugInIssue-22-July-2019

### Screenshots
N/A

**Comment by Huaba93** [comment]
Same problem here on android.

RequestPermissionAsync never returnes

**Comment by conrad90909** [comment]
@Huaba93... Yeah confirmed this, just playing with the Camera permissions right this minute and it is doing exactly the same thing with that!

**Comment by Huaba93** [comment]
uff...I failed. I refactored my code and removed too much. 

This in MainActitviy is mandatory!

```
        public override void OnRequestPermissionsResult(int requestCode, string[] permissions,
            [GeneratedEnum] Permission[] grantResults)
        {
            PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
            base.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }
```

**Comment by jamesmontemagno** [comment]
@conrad90909 can you trim down your sample as it is the default that I use so I am not even sure what code you are calling

**Comment by conrad90909** [comment]
@jamesmontemagno, trimmed and pushed.  I thought using your sample would help you see the issue easier :)

All I did was take your example update to the beta 5.0 and due to some versioning issues I swapped to use Xamarin Essentials for the geolocation code.  I then implemented anything missing from the latest readme.  It's compiling using Android 9.0 as well. 

I'm also including a link to a video [here](https://youtu.be/8Gjc4B5L2gg) this shows me opening the application and clicking the button.  It requests the location permissions but then the app drops out of the code and does nothing.  I restart the application and push the button, it now has the permission so is allowed so it gets the location.

Many thanks.

**Comment by conrad90909** [comment]
@jamesmontemagno It is specifically this line of code that is having a bad day...

`status = await CrossPermissions.Current.RequestPermissionAsync<LocationPermission>();`

If you breakpoint that and watch what it does it jumps out of the code.

**Comment by Huaba93** [comment]
replace in MainActivity

`Xamarin.Essentials.Platform.OnRequestPermissionsResult(requestCode, permissions, grantResults);`

with

`PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);`

**Comment by conrad90909** [comment]
I looked at that piece of code like 100 times and didn't spot that I'd got Xamarin Essentials at the start of it instead of PermissionsImplementation.....I think I need a holiday!

Thanks for your help @Huaba93 @jamesmontemagno this solves my issue!!

**Comment by khadeeja-alif** [comment]
I have implemented the request permission result method correctly, but I'm still having the issue in my Android Project.
