### ISSUE TITLE
Update README.MD to discuss iOS 10 changes

### ISSUE THREAD

**Issue by madgrizzle** [jamesmontemagno/PermissionsPlugin#15]
I suggest adding an update to the README.md file to let users know that permissions in iOS has changed and developers need to modify the info.plist file to get the plugin to work.  A simple link to your blog post [New iOS 10 Privacy Permission Settings](https://blog.xamarin.com/new-ios-10-privacy-permission-settings/) may be sufficient as it gave me the info I needed when I discovered my app crashing when on RequestPermissionsAsync... and thanks for the plugin.

**Comment by jamesmontemagno** [comment]
Done!
