### ISSUE TITLE
Initial RequestPermissionAsync call gives response before user action.

### ISSUE THREAD

**Issue by khadeeja-alif** [jamesmontemagno/PermissionsPlugin#150]
## Bug Information
Version Number of Plugin: 3.0.0.12
Device Tested On: Android & iOS , All Devices
Version of VS: VS community for mac - version 8.1.4
Version of Xamarin:
Xamarin.iOS - 12.10.0.157
Xamarin.Android - 9.3.0.23
Xamarin Forms - 3.2.0.839982

### Steps to reproduce the Behavior
In the following code (the same one in demo),
```
try
{
	var status = await CrossPermissions.Current.CheckPermissionStatusAsync<LocationPermission>();
	if (status != PermissionStatus.Granted)
	{
		if (await CrossPermissions.Current.ShouldShowRequestPermissionRationaleAsync(Permission.Location))
		{
			await DisplayAlert("Need location", "Gonna need that location", "OK");
		}

		status = await CrossPermissions.Current.RequestPermissionAsync<LocationPermission>();
	}

	if (status == PermissionStatus.Granted)
	{
		//Query permission
	}
	else if (status != PermissionStatus.Unknown)
	{
		//location denied
	}
}
catch (Exception ex)
{
  //Something went wrong
}
```
Initially, the call for RequestPermissionasync gives a response before user action, and the code continues to the next line to check the status. So before the user responds "allow" to the permission request alert, the code continues to the next step and disabled or denied is returned.

### Expected Behavior

await the RequestPermissionasync call, get the user input, then give a response, and based on the response, continue to check the status.

### Actual Behavior

call for RequestPermissionasync gives a response before user action, and the code continues to the next line with the earlier permission status.

**Comment by DieselSoup** [comment]
I have this issue as well

**Comment by conrad90909** [comment]
If you have a sample app I will take a look for you, does your issue effect iOS and Android or just one of those?

**Comment by khadeeja-alif** [comment]
The issue is visible in Android. You can try the demo app in this project

https://github.com/fantacode/PlacePicker/tree/master/sample.

The code for accessing location will be found in this class.
https://github.com/fantacode/PlacePicker/blob/master/PlacePicker/Helpers/GetUserLocation.cs

**Comment by conrad90909** [comment]
Your app hits this line of code before James Code and it doesn't have location permissions yet:

**var lastLocation = await Geolocation.GetLastKnownLocationAsync();**

In your UpdateCamera task in LocationPicker.xaml.cs

That fires the location request not the permissions plugin.  The CheckPermissions code needs to be done before anything might make a location request.  I've been caught out by this myself before I had the show my location on a google maps which didn't have permission when initialising a form. 

Anyway to solve it myself I moved the check permissions code onto your Handle_Clicked in MainPage.xaml.cs and it fixed it for me. I would suggest doing it in the initialise of the LocationPicker page though!

Hope this helps

Cheers

Conrad

**Comment by jamesmontemagno** [comment]
Also, essentials will call in to ask permissions. This is all working great. thanks for validating @conrad90909
