### ISSUE TITLE
Permission plugin always return status as Granted even when Location is OFF

### ISSUE THREAD

**Issue by jhadz81** [jamesmontemagno/PermissionsPlugin#152]
Plugin version:  3.0.0.12
Tested on:  Nexus 6 (Android 8.1)
VS 2019, Xamarin Forms:  3.6.0.539721

The plugin works fine prompting user to allow access to location services the first time they access a map in my app.  However, when I turn off Location Services on the phone, go back to the map in the app and the following code is called...

`var status = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Location);`

Status = PermissionStatus.Granted

It should be PermissionStatus.Disabled.

Any ideas why?

**Comment by conrad90909** [comment]
If you have a sample project I'll take a look for you!

**Comment by liperbr** [comment]
Same problem here...

**Comment by jamesmontemagno** [comment]
So, this is working fine. It is the Permission, not the functionality. Disabled only applies to iOS.
