### ISSUE TITLE
ShouldShowRequestPermissionRationaleAsync is always false

### ISSUE THREAD

**Issue by MCNorthwood** [jamesmontemagno/PermissionsPlugin#153]
## Bug Information

Version Number of Plugin: v5.0.0-beta
Device Tested On: Samsung Galaxy J6 (Android Version 9)
Simulator Tested On: N/A
Version of VS: 2019 - 16.2.3
Version of Xamarin: 4.2.0.709249
Versions of other things you are using: 
Essentials 1.3.0
MvvmHelpers 1.5.0-beta
### Steps to reproduce the Behavior
Call await CrossPermissions.Current.ShouldShowRequestPermissionRationaleAsync(Permission.Camera) and returns false and then continues on to the next page.
### Expected Behavior
Should return true and then request the camera permission 
while also surrounded in a if that checks the status from await CrossPermissions.Current.CheckPermissionStatusAsync<CameraPermission>() which returns denied and then calls
using await CrossPermissions.Current.RequestPermissionAsync<CameraPermission>();
### Actual Behavior
Returns false and skips the permission check, have used the other method, which I only just realised is a deprecated method. I've also checked the Required Permissions and Camera is ticked under the Android Manifest
### Code snippet
```
  PermissionStatus status = await CrossPermissions.Current.CheckPermissionStatusAsync<CameraPermission>();
                var test = await CrossPermissions.Current.ShouldShowRequestPermissionRationaleAsync(Permission.Camera);
                if (status != PermissionStatus.Granted)
                {
                    await CrossPermissions.Current.RequestPermissionAsync<CameraPermission>();
                }
```
### Screenshots

![PermissionsCheck](https://user-images.githubusercontent.com/24660116/63779758-fb8b0e00-c8de-11e9-9ac6-dfe5f17f5a1f.jpg)

**Comment by conrad90909** [comment]
This sounds like the same issue I had, check your Main Activity in the Android project in OnRequestPermissionsResult, you might need to replace

Xamarin.Essentials.Platform.OnRequestPermissionsResult(requestCode, permissions, grantResults);

with

PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);

**Comment by MCNorthwood** [comment]
I did comment out the essentials and tested it and same thing, I had both in there before and now it's just the plugin and it still doesn't work

```
public override void OnRequestPermissionsResult(int requestCode, string[] permissions, [GeneratedEnum] Permission[] grantResults)
        {
            PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
            //Xamarin.Essentials.Platform.OnRequestPermissionsResult(requestCode, permissions, grantResults);

            base.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }
```

**Comment by conrad90909** [comment]
If you can give a working sample I will take a more in-depth look and see what's going wrong with it!

**Comment by MCNorthwood** [comment]
The code is not very different to what you made in yours which is a replica of what James put as an example, along with the relevant additions in the MainActivity.


```
PermissionStatus status = await CrossPermissions.Current.CheckPermissionStatusAsync<CameraPermission>();
if (status != PermissionStatus.Granted)
{
    if (await CrossPermissions.Current.ShouldShowRequestPermissionRationaleAsync(Permission.Camera))
    {
        await DisplayAlert("Need Camera Permission", "Need camera permission to continue", "OK");
    }

    status = await CrossPermissions.Current.RequestPermissionAsync<CameraPermission>();
}

if (status == PermissionStatus.Granted)
{
    await Navigation.PushAsync(AppraisalManager.VehicleList);
}
else if(status != PermissionStatus.Unknown)
{
    await DisplayAlert("No Permissions", "Can not continue, try again", "OK");
}
```

I've just tested on an older Device, a Huawei Honor 7, running Android 6, so after the High Level permissions were introduced and that hits the display alert for Need Camera Permission, an emulator running Android 6 and Android 8 doesn't hit it either, it'll be quite a bit later or even tomorrow before I'll be able to get a working example to see if it's something else I'm working with that might be breaking it

**Comment by kjundev** [comment]
Put the code below in the MainActivity.cs 

Plugin.CurrentActivity.CrossCurrentActivity.Current.Init(this, savedInstanceState);

**Comment by jamesmontemagno** [comment]
It will only return true after the user has selected to decline at least once or twice.

**Comment by jamesmontemagno** [comment]
[App23.zip](https://github.com/jamesmontemagno/PermissionsPlugin/files/3692189/App23.zip)
Just validated it is workign fine.

Run the sample:
* Click button, decline permission
* Click button, needs rationale is true now.
