### ISSUE TITLE
iOS 13.0 Location permission "Allow Once" is not implemented yet

### ISSUE THREAD

**Issue by jpeters5392** [jamesmontemagno/PermissionsPlugin#155]
The iOS 13.0 preview introduced a new `Allow Once` option for location permissions and this plugin does not yet have support for that.  https://www.apple.com/ios/ios-13-preview/features/.    We are actively working on making our app compatible with 13.0 changes so we might be able to put up a PR for this in the near future if it does not get fixed by somebody else first.

**Comment by jamesmontemagno** [comment]
Open to a PR for sure, need to do checks around iOS 13, I don't have it up and running on my machines currently as the GMs just dropped.

**Comment by jpeters5392** [comment]
My team looked into this a bit more and it looks like iOS abstracts it away, where if they choose `AllowOnce` your app will get the typical permission, but then when their session ends it will call your location manager delegate to update the permission to revoked again.  So there may not actually be any changes needed here.  I'll go ahead and close this out.
