### ISSUE TITLE
Android ANSWER_PHONE_CALLS permission is missing

### ISSUE THREAD

**Issue by VahidShir** [jamesmontemagno/PermissionsPlugin#156]
I'm using the latest stable version (i.e 3.0.0.12). I have a scenario in which I end incoming phone calls based on some logic. In order to do that the **"ANSWER_PHONE_CALLS" or (Manifest.Permission.AnswerPhoneCalls)** permission must be requested and granted by user. But as I searched through Android's **PermissionsImplementation.cs** class of your library that permission doesn't exist and is not handled at all.

**Comment by VahidShir** [comment]
Although if any other permissions in the same group of  the mentioned permission is already granted, then this permission will be granted too, based on Android's mechanism.
But the problem arises when we din't declare permissions from same group!

**Comment by jamesmontemagno** [comment]
This was new and only introduced in API 26. Easy enough to add in there.

**Comment by VahidShir** [comment]
That's right. Will you plan to include that permission (and probably similar new permissions if any) to your library?

**Comment by jamesmontemagno** [comment]
I am not updating or adding more features now that Xamarin.Essentials offers Permissions and is extensible as well.
