### ISSUE TITLE
Android 10 introduces new permission ACCESS_BACKGROUND_LOCATION

### ISSUE THREAD

**Issue by scottiebrady** [jamesmontemagno/PermissionsPlugin#157]
With the introduction of Android 10 (API Level 29), the user now has more control over location services, and restrict the app to just foreground access.
https://developer.android.com/training/location/receive-location-updates#request-background-location

Guessing once the Android 10 SDK is available, the Android implementation will need to be updated to support new 'Android.Manifest.Permission.AccessBackgroundLocation'.
https://developer.android.com/reference/android/Manifest.permission.html#ACCESS_BACKGROUND_LOCATION

**Comment by mduchev** [comment]
@jamesmontemagno  Any plans for Android 10 (and iOS 13) support?

**Comment by jamesmontemagno** [comment]
I do have this on my backlog :)

**Comment by kberawala** [comment]
any ETA on this ?

**Comment by jgodort** [comment]
Hi, any news with this? There any way to implement this natively? 
In this this stackoverflow (https://stackoverflow.com/questions/58394585/cannot-find-access-background-location-permission-in-xamarin-android-code-i-n) says that there no possibility to use this permission till Xamarin.Android reaches v29.x.x.x 

Sorry, but I'm not very familiar with xamarin but I have to maintain a legacy app.

**Comment by jamesmontemagno** [comment]
I will be updating the library soon :) Xamarin.Essentials has this built in with 1.5.1

**Comment by jamesmontemagno** [comment]
https://github.com/jamesmontemagno/PermissionsPlugin/pull/170

**Comment by jgodort** [comment]
Thanks James!!

**Comment by JamesDepret** [comment]
I've implemented this following the guide ref. https://docs.microsoft.com/en-us/xamarin/essentials/geolocation?tabs=android
But on my phone, I'm not asked for location always, only when the app is active.

Are there different steps to implement this?

**Comment by jgodort** [comment]
Check if you are requesting FINE and COARSE with ACCESS_BACKGROUND... In Android 11 if you request all at the same time, the request will be ignored!!
