### ISSUE TITLE
iOS 13 has new Bluetooth permission

### ISSUE THREAD

**Issue by rgiurea** [jamesmontemagno/PermissionsPlugin#158]
The new iOS 13 introduced a new Bluetooth permission that the library should also support. Because its such e new feature I did not find any documentation on it yet, but the permission is definitely asked by the system upon bluetooth access. The plist option for defining the description should be something like "Privacy - Bluetooth Always Usage Description".

The iOS Library implementation should also support this new permission as soon as its clearly how to implement it :)

**Comment by mduchev** [comment]
iOS 13 has also another permission changes - Use location "only once". Full support is needed, not only for the Bluetooth one.

**Comment by felipemomm** [comment]
Is there any timeline to have Bluetooth implemented for iOS?

**Comment by jamesmontemagno** [comment]
Only once works the same as "when open" it just resets after a while. That is already supported.

I am not updating or adding more features now that Xamarin.Essentials offers Permissions and is extensible as well.
