### ISSUE TITLE
iOS App uses sensitive data that is not needed

### ISSUE THREAD

**Issue by DavidShochet** [jamesmontemagno/PermissionsPlugin#159]
Version Number of Plugin: 3.0.0.12
Device Tested On: N/A
Version of VS: VS 2019 version 16.3.2
Version of Xamarin: Xamarin.Forms version 4.2.0.709249
Versions of other things you are using: N/A

My app is using PermissionsPlugin. When we are trying to deploy it on the Apple Store, we get the following error:

> ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSCalendarsUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy). 

My app doesn't use Calendars and doesn't mention it. I suspect it is the plugin that uses it behind the scene. If it is not required, could you please provide us with "a version of their code that doesn't contain the APIs"? If it is required, could you please provide us with the explanation of why it is needed?

P.S. We also received the following warning:

> ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data.

The app uses only Permission.LocationWhenInUse, not LocationAlways:
`                PermissionStatus status = await PermissionUtils.CheckPermissions(Permission.LocationWhenInUse);
`
 Though it is just a warning, it is not that critical.

**Comment by jamesmontemagno** [comment]
You will need to use the 5.0-beta and the new API which is linker safe.
