### ISSUE TITLE
App Store submission missing NSUsageDescription without actually requesting those permissions

### ISSUE THREAD

**Issue by veryhumble** [jamesmontemagno/PermissionsPlugin#16]
Hi, we are currently working on a Xamarin.Forms app and have submitted it to the app store for beta testing. It was rejected due to a missing `NSCalendarsUsageDescription` in the info.plist. The only permission we request is the Location, but no calendar information. Could this be a problem with the Permissions Plugin?
## Bug

Version Number of Plugin: 1.2.0-beta9
Device Tested On: iOS10
Simulator Tested On: iOS10
### Expected Behavior

It should not be mandatory to set every NSUsageDescription in the info.plist without actually requesting that particular permission.
### Actual Behavior

App Store review Team: "This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSCalendarsUsageDescription key with a string value explaining to the user how the app uses this data."
### Steps to reproduce the Behavior

Submitt an app using the Permissions Plugin

**Comment by jamesmontemagno** [comment]
Developer seem to be seeing this with random SDKs: https://forums.developer.apple.com/thread/62229

So it may depend on what you are using. I haven't tried any submissions recently with iOS 10. Could just add it in as it doesn't hurt anything.

**Comment by veryhumble** [comment]
I added said UsageDescription and the TestFlight submission seems happy with it 👍  . If this is a known problem, i think this issue can be closed. Thanks for the fast response!

**Comment by jamesmontemagno** [comment]
If you can do additional testing to remove the permission plugin we can figure it out. If so I can then document it I guess or remove the Calendar integration, which would be sad.

**Comment by ElteHupkes** [comment]
FYI, I just got a similar app rejection for an app that does not use the calendar permission after making a minor unrelated fix. The previous release, which had exactly the same plugin versions of everything, targeted the IOS 9 SDK, and got through without issue..

I'm going to add the usage description for now, anything I can do to figure out what the problem is?

**Comment by jamesmontemagno** [comment]
Hmmmm, I will investigate here, I have seen apple do a bunch of random rejections because of permissions. I had to recently add one for photos because I was using the social framework.

**Comment by ElteHupkes** [comment]
Haha, oh Apple.

"I have to change three lines of code in our iOS app. Better block out the whole day."

**Comment by veryhumble** [comment]
I reopen this issue for reference. Maybe Apples automated review process is currently not that good to detect if a permission is actually used or not.

**Comment by jamesmontemagno** [comment]
Interesting... I will take another look. May have to remove the Calendar permission. I may just have to document it as I don't really want to remove it at all. I assume they are scanning code and since the bits are there... even though never being called :( sad

**Comment by ChaseFlorell** [comment]
I'm seeing this with Calendar as well. With our security compliance, I cannot submit to the app store with any permissions that haven't been approved by Corp (IE: I need a valid reason).

**Comment by ChaseFlorell** [comment]
What about making the calendar permissions portion an extension? IE: if you want it you install it separately (nupkg) and it hooks into the permissions plugin.

**Comment by jamesmontemagno** [comment]
@ChaseFlorell I would probably fork and add as submodule with your changes needed. It is a tough call and maintenance nightmare to remove it as well as a breaking change.

**Comment by jlmatus** [comment]
This is still an issue, why is closed? What's the solution? The solution can't be add the permission description because apple would reject my app once they see I'm not using the user's calendar.

**Comment by jamesmontemagno** [comment]
They will not reject your app at all. You just have to add it into the info.plist. The workaround is to just add it. However apple scans their code thinks that it needs it.
