### ISSUE TITLE
Location services are not enabled on device

### ISSUE THREAD

**Issue by dalton5** [jamesmontemagno/PermissionsPlugin#167]
Hi,

I use xamarin forms and the location is not enabled on the device.

Then I get the exception. But how can I provide a solution to show the prompt to enable location service?

I did not find the method in the library.

What are the solutions available?

Thanks,

**Comment by jamesmontemagno** [comment]
You will just have to prompt the user to turn on their location settings and open the settings on the device.

**Comment by dalton5** [comment]
Is there a code to open the settings? I wanted to show the prompt dialog like in maps on Android. Enable location? Would you have a sample to do this? Thanks
