### ISSUE TITLE
AndroidX support or use Essentials? :)

### ISSUE THREAD

**Issue by paleicikas** [jamesmontemagno/PermissionsPlugin#168]
Can not resolve reference: `Xamarin.Android.Support.Compat`, referenced by `Plugin.Permissions`.

**Comment by jamesmontemagno** [comment]
You should be able to use the https://www.nuget.org/packages/Xamarin.AndroidX.Migration/ package and you should be fine.

**Comment by jamesmontemagno** [comment]
Would recommend migrating to Essentials though as that is my main focus with the team.

**Comment by jamesmontemagno** [comment]
https://github.com/jamesmontemagno/PermissionsPlugin/pull/170
