### ISSUE TITLE
Update samples to Generics

### ISSUE THREAD

**Issue by mzieg** [jamesmontemagno/PermissionsPlugin#173]
## Bug Information

Version Number of Plugin: 6.0.1
Device Tested On: n/a
Simulator Tested On: n/a
Version of VS: 2019 MacOS (8.5.1 build 42)
Version of Xamarin: Xamarin.Mac 6.14.1.39 
Versions of other things you are using:

### Steps to reproduce the Behavior

Compile code snippet.

### Expected Behavior

It looks like you're moving CheckPermissionStatusAsync to a Generic, which would force compiler-level type correctness, which is cool.  However, I can't figure out how to pass it the correct type.

### Actual Behavior

Compiler returns: 'T' must be a non-abstract type with a public parameterless constructor in order to use it as parameter 'T' in the generic type or method 'IPermissions.CheckPermissionStatusAsync<T>()'.

I've checked your implementation of LocationWhenInUsePermission and similar classes, and they do have such a parameterless constructor, so I'm not sure what I'm doing wrong.  I'd like to use your library "as intended," so please update your examples to show how you wish these classes to be used.

### Code snippet

```
var ok = _requestPermissionAsync<LocationWhenInUsePermission>(Permission.LocationWhenInUse, "Location", "I need this."));

async Task<bool> _requestPermissionAsync<T>(Permission perm, string name, string reason) where T : BasePermission
{
    // this works, but generates a deprecation warning (should use Generic)
    var statusOne = await CrossPermissions.Current.CheckPermissionStatusAsync(perm);

    // this resolves the warning, but generates a compiler error message:
    var statusTwo = await CrossPermissions.Current.CheckPermissionStatusAsync<T>(); 

    return statusTwo;
}
```

### Screenshots

**Comment by jamesmontemagno** [comment]
Updated
