### ISSUE TITLE
Errors on package install

### ISSUE THREAD

**Issue by JohnHind** [jamesmontemagno/PermissionsPlugin#18]
## Bug 

Version Number of Plugin: 1.1.7
Device Tested On: Did not get that far
Simulator Tested On: See above

### Expected Behavior
NuGet Installs the plugin
### Actual Behavior
Package Manager Console Host Version 3.5.0.1484

Type 'get-help NuGet' to see all available NuGet commands.

PM> Install-Package Plugin.Permissions -Version 1.1.7
Install-Package : Project 'Default' is not found.
At line:1 char:1
+ Install-Package Plugin.Permissions -Version 1.1.7
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Default:String) [Install-Package], ItemNotFoundException
    + FullyQualifiedErrorId : NuGetProjectNotFound,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
PM> 
### Steps to reproduce the Behavior
In Visual Studio Community 2015 Version 14.0.25425.01 Update 3, Tools, NuGet Package Manager, Package Manager Console, then type command line as above.

Sorry if this is a newbe problem, but I am one in this area and I am following the instructions to the best of my ability!

**Comment by jamesmontemagno** [comment]
I I would maybe post the issue here for NuGet: https://github.com/NuGet/Home

I haven't had any issues installing it although I don't use the command line, i just use the normal explorer.
