### ISSUE TITLE
Scoped storage permission on Xamarin Android 10+?

### ISSUE THREAD

**Issue by stefancvetkovic** [jamesmontemagno/PermissionsPlugin#181]
Hey James!
I was wondering how to implement scoped storage that is required for android 10+ devices?
https://medium.com/better-programming/all-you-need-to-know-about-scoped-storage-in-android-10-e621f40bc8b9

I added your plugin, and it works on Android 9, but on Android 10 it says - /storage/emulated/0/test.pdf: open failed: EACCES (Permission denied)

I double checked, Im giving it a permision for storage (added in manifest to write/read external storage), but because of this scoped storage obviosly I need to add something more..
Do you have some hint for me?

**Comment by nihil007** [comment]
Same problem:
<uses-sdk android:minSdkVersion="28" android:targetSdkVersion="28" /> WORKS
<uses-sdk android:minSdkVersion="28" android:targetSdkVersion="29" /> DOESN'T WORK

**Comment by nihil007** [comment]
Same problem: android:targetSdkVersion="29" doesn't work but android:targetSdkVersion="28" works

**Comment by stefancvetkovic** [comment]
@nihil007 I temporarily fixed this when I put `android:fitsSystemWindows="false"` to my manifest file in <application> tag section

**Comment by jamesmontemagno** [comment]
I am not updating or adding more features now that Xamarin.Essentials offers Permissions and is extensible as well.
