### ISSUE TITLE
RequestPermissionAsync on Application Load throws null ref

### ISSUE THREAD

**Issue by sisaacks** [jamesmontemagno/PermissionsPlugin#189]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 6.0.1
Device Tested On: Samsung SM-G975U1
Simulator Tested On:
Version of VS: Microsoft Visual Studio Professional 2019 16.7.6
Version of Xamarin Forms:4.8.0.1687
Version of Xamarin Essentials:1.5.3.2
Versions of other things you are using:

### Steps to reproduce the Behavior
I have a Xamarin Shell App. When the application starts in the OnAppearing method I call to CheckAndGetPermissions. I have the code from your examples online.  This code works fine....other than in application loading.  
status = await CrossPermissions.Current.CheckPermissionStatusAsync<LocationPermission>();
The above line works fine.  However when trying to request permission I get a null ref
 status = await CrossPermissions.Current.RequestPermissionAsync<LocationPermission>();
If I call this method outside of loading the application it works fine.  

### Expected Behavior
 I would expect status = await CrossPermissions.Current.RequestPermissionAsync<LocationPermission>(); 
to work when the app is loading.

### Code snippet
 public async Task<PermissionStatus> PermissionCheck(Permission permission)
        {
            PermissionStatus status = PermissionStatus.Unknown;

            switch (permission)
            {
                case Permission.Location:
                    status = await CrossPermissions.Current.CheckPermissionStatusAsync<LocationPermission>();
                    break;

                case Permission.Storage:
                    status = await CrossPermissions.Current.CheckPermissionStatusAsync<StoragePermission>();
                    break;
            }

            if (status != PermissionStatus.Granted)
            {
                switch (permission)
                {
                    case Permission.Location:
                        status = await CrossPermissions.Current.RequestPermissionAsync<LocationPermission>();
                        break;

                    case Permission.Storage:
                        status = await CrossPermissions.Current.RequestPermissionAsync<StoragePermission>();
                        break;
                }
            }

            return await Task.FromResult(status);
        }

**Comment by jamesmontemagno** [comment]
Your app must be open, wait until the first page is open.

**Comment by sisaacks** [comment]
Hello Jamesmontemagno/Permissionsplugin

I have been trying to get in contact with you for a bit.
Fair enough on your response, but I need to run some things on app
load.....that depend on knowing if I have permissions or not.

**Comment by jamesmontemagno** [comment]
Permission checks need access to the Activity, so you must wait until that fully loads for things to work. Just don't call the code until the permission is set. You shouldn't be doing anyting really in the application load as it will block your app from launching. 

A tip is to navigate first to a screen, check permissions, and then move on or request.

**Comment by sisaacks** [comment]
I have a shell application with flyouts.
So the first page on the first tab loads.
The only load method is OnAppearing() which happens after the ViewModel
Initialize
There are certain aspects in the VM.....that I need to set...that depend on
permissions.
From what you stated above, I would call these functions after OnAppearing
has finished...but I am not aware of a method that knows when OnAppearing
has finished.
In WPF you have OnLoading and OnLoaded.....the later being the past tense
of when completed.
