### ISSUE TITLE
I can't compile my project

### ISSUE THREAD

**Issue by acaliaro** [jamesmontemagno/PermissionsPlugin#19]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: latest
Device Tested On: none
Simulator Tested On: none

### Expected Behavior

Can compile my project

### Actual Behavior

I have add 

		//Per permission plugin
		public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)
		{
			PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
		}

to my MainActivity.cs and add

using Plugin.Permissions;

but I have 

 Error CS0115: `IWapp.Droid.MainActivity.OnRequestPermissionsResult(int, string[], Android.Content.PM.Permission[])' is marked as an override but no suitable method found to override (CS0115) (IWapp.Droid)

### Steps to reproduce the Behavior

follow your github readme

**Comment by jamesmontemagno** [comment]
You need to make sure app is set to Compile against API 23+

This in the Android project settings. In Xamarin Studio Under general and under the app settings in VS
