### ISSUE TITLE
Path to Maui?

### ISSUE THREAD

**Issue by marcusts** [jamesmontemagno/PermissionsPlugin#194]
I am starting to port my test app to Maui, but of course, none of the NuGets are compatible!  I am wondering if/when you intend to fork/port your own work to Maui.

Thank you for the years of great work.

**Comment by jamesmontemagno** [comment]
Permissions is included in .NET MAUI directly with the built in Permissions API of .NET MAUI Essentials! I would highly recommend upgrading to that ;)

I don't see much value in my plugin now that it is included in the box.

**Comment by Seanxwy** [comment]
MAUI include this? What is the API

**Comment by jamesmontemagno** [comment]
@Seanxwy  every single API from Xamarin.Essentials is in .NET MAUI -> https://docs.microsoft.com/en-us/xamarin/essentials/

using Microsoft.Maui.Essentials;

**Comment by kvsiemetero** [comment]
Package Plugin.Permissions should no longer be necessary with built-in permission support in MAUI: https://github.com/jamesmontemagno/PermissionsPlugin/issues/194
