### ISSUE TITLE
Requests once

### ISSUE THREAD

**Issue by SamuelDebruyn** [jamesmontemagno/PermissionsPlugin#2]
The plugin requests the permissions only once. What if the user has denied the permission, changes his mind and would like to grant the permission after all? I can't use this plugin to show the dialog again once the user has denied the permission.

## Bug 

Version Number of Plugin: 1.1.7
Device Tested On: iPhone SE iOS 9.3
Simulator Tested On: iPhone 6s iOS 9.3

### Expected Behavior
Dialog pops up with permission request.

### Actual Behavior
Plugin returns with denied.

### Steps to reproduce the Behavior
Request location permission after the user has denied the permission.

## Feature Request:
Let me override the default so I can ask for the permission a second time.

**Comment by jamesmontemagno** [comment]
This is how iOS works, sorry, you can only request once. I recommend doing something like this:

https://github.com/xamarinhq/app-evolve/blob/master/src/XamarinEvolve.Clients.UI/Pages/MiniHacks/MiniHacksDetailsPage.xaml.cs#L68-L117

**Comment by SamuelDebruyn** [comment]
Sorry, should have checked that first :/ Thanks for the clarification and the great plugin! :)

**Comment by Umar3x** [comment]
@jamesmontemagno  

Hello james. Your link is not available anymore ... I'm running the same prob and I'd like to know what you would recommend. Thanks.
