### ISSUE TITLE
Failed to resolve "Speech.SFSpeechRecognizerAuthorizationStatus"

### ISSUE THREAD

**Issue by jeroendk** [jamesmontemagno/PermissionsPlugin#22]
When using this plugin with the media plugin my app wont build for a iOS 10 device (build with ios sdk 9.3) Building on the simulator with ios9 works fine. 

The error i get is:
Failed to resolve "Speech.SFSpeechRecognizerAuthorizationStatus"

Version Number of Plugin: 1.2.1

**Comment by jamesmontemagno** [comment]
You must now build with the iOS 10 SDK as it is built against it. Sorry.

**Comment by jeroendk** [comment]
I see, thank you.

**Comment by CarbonSft** [comment]
So it is not compatible with iOS 7? If so, then compatibility table on project's page missleads developers :-(
