### ISSUE TITLE
Even if I manually disable camera permission, It's still say "Granted".

### ISSUE THREAD

**Issue by allbdeveloper** [jamesmontemagno/PermissionsPlugin#23]
## Bug 

Version Number of Plugin: 1.2.1
Device Tested On: LG G3(Android 6)
Simulator Tested On:

### Actual Behavior

I manually set Permission to off in Android app setting and try this
`var status = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Camera);`

It's still say "Granted" and app crash because I try to use Camera.
(in debug test)

It's not happening to you?
Am I wrong somewhere?

Thanks.

**Comment by allbdeveloper** [comment]
https://github.com/jamesmontemagno/PermissionsPlugin/issues/11

I saw there comment. 
Can you let me understand more? 

If I set target of my app to Android 6, but plugin is made with 7, it would not work? 
How can I set plugin's target lower with using nuget package?

**Comment by allbdeveloper** [comment]
It's working now.
After saw #11  and followed it.

I have no idea what was going on.
SDK target says "automatic - api23"
So I thought it's set as api23. 
But I change it api23 'manually'.
My problem was solved.

**Comment by jamesmontemagno** [comment]
You can have it compile or target 23 or 24 for it to work. Glad it is now working :)

Automatic doesn't work :( yeah

**Comment by allbdeveloper** [comment]
Thank James!
