### ISSUE TITLE
Android dependencies for API 24+

### ISSUE THREAD

**Issue by softwaremills** [jamesmontemagno/PermissionsPlugin#24]
Plugin.Permissions requires Xamarin.Android.Support.v4. Unfortunately other Xamarin packages, like AppCompat, that used to require this library (in versions up to 23.4.0.1) now require things like Xamarin.Android.Support.Core.Utils, which define the same symbols. This means that in order to compile projects that use both Plugin.Permissions and AppCompat, I need to use the 23.x version of AppCompat et al, not the 24.x version.

Currently I don't need the 24.x versions of Xamarin's support library; I can get by with the 23.x versions. But it seems like something to keep in mind.

**Comment by softwaremills** [comment]
Total coincidence that this turned out to be Issue #24. :)

**Comment by jamesmontemagno** [comment]
I usually keep in line with what Xamarin.Forms currently targets. Usually there aren't any breaking changes in between when upating, but could be the versions changed and such... let me think about how I can do it.

**Comment by softwaremills** [comment]
Thanks so much again for your effort on various Xamarin plugins. Settings, Permissions, and your work updating the Media plugin ... all very much appreciated.

**Comment by jamesmontemagno** [comment]
I tested this out and it and it seemed to work great with all of the 24.X installed. I have the library set to >= 23.3.0 so it should be working just fine. Tested with permissions and the geolocator plugin. 

I have included a sample: https://github.com/jamesmontemagno/PermissionsPlugin/tree/master/samples

**Comment by softwaremills** [comment]
Try testing with AppCompat 24.x. AppCompat 24.x requires different packages than AppCompat 23.x (used by the current version of Xamarin.Forms) and the symbols those packages define conflict with Xamarin.Android.Support.v4.

**Comment by jamesmontemagno** [comment]
Xamarin.Forms requires 23.3.0 to be installed.

I created a non-xamarin.forms app installed all 24.x and it worked perfect. I linked to the sample including the non-forms.

Feel free to pull down the repo and run the sample.

**Comment by jamesmontemagno** [comment]
![image](https://cloud.githubusercontent.com/assets/1676321/20232337/740c1702-a81c-11e6-9798-156e2f89fdcf.png)
