### ISSUE TITLE
System.InvalidOperationExceptionAn attempt was made to transition a task to a final state when it had already completed.

### ISSUE THREAD

**Issue by MatthewGerber** [jamesmontemagno/PermissionsPlugin#27]
## Bug 

System.InvalidOperationExceptionAn attempt was made to transition a task to a final state when it had already completed.
Raw
System.Threading.Tasks.TaskCompletionSource<TResult>.SetResult(TResult result)<368820a9888f43ddb85d18e87189adbf>:0
Plugin.Permissions.PermissionsImplementation.OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)<47bb53b40691435f96893bccf92fcd93>:0
Sensus.Android.AndroidMainActivity.OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)<23556fa8db484a1f9fb76c2fcebf4564>:0
Android.App.Activity.n_OnRequestPermissionsResult_IarrayLjava_lang_String_arrayI(IntPtr jnienv, IntPtr native__this, int requestCode, IntPtr native_permissions, IntPtr native_grantResults)<148efd2f7a03496fb40611cf5f4f0bb1>:0
at (wrapper dynamic-method) System.Object:d20dfcf5-62be-4e27-8c5a-6c2b9ce6303b (intptr,intptr,int,intptr,intptr)

Version Number of Plugin:  1.1.7
Device Tested On:  Android M
Simulator Tested On:  None

### Expected Behavior
No exception.

### Actual Behavior
Exception.

### Steps to reproduce the Behavior
Not sure. Got this in Insights.

**Comment by jamesmontemagno** [comment]
How did you call it? This probably means you called a method twice without awaiting.

Or this means you didn't put the code in your main activity to pass up the event.

**Comment by MatthewGerber** [comment]
I obtain permission with the following call:

`await CrossPermissions.Current.RequestPermissionsAsync(permission)`

I don't call this method anywhere else, although it's possible for this line of code to run concurrently in multiple threads. Is this a problem?

I've got the following in my main activity:

```
        public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)
        {
            PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }
```

**Comment by jamesmontemagno** [comment]
Looks correct to me. Perhaps the user pressed some button that trigger the call multiple times? That may cause something like it. Out of the box I have never seen something like this from normal use.

**Comment by MatthewGerber** [comment]
The calls don't result from user interaction. It's quite possible for them to be performed concurrently across threads. I'll try restricting concurrent executions for this code.

**Comment by jamesmontemagno** [comment]
Perhaps there is something I can do in the code to stop it... 

Essentially what I do here is cancel the current one if a new one comes in...

https://github.com/jamesmontemagno/PermissionsPlugin/blob/master/src/Plugin.Permissions.Android/PermissionsImplementation.cs#L120-L124

So perhaps it is a weird timing issue?

**Comment by MatthewGerber** [comment]
Yeah maybe. I'm pretty sure that `await CrossPermissions.Current.RequestPermissionsAsync(permission)` is being called within multiple threads. If you can handle it that would be great.

**Comment by jamesmontemagno** [comment]
I don't think i can handle multiple requests at the same time persay based on my design of the library... if I could get a small repo somehow then I could test for it.

I could see how it could come up though if you call it form message center or something like that... 

Need some threading experts.

**Comment by gjkhw** [comment]
Would it be as straightforward as guarding RequestPermissionsAsync with a [SemaphoreSlim](https://msdn.microsoft.com/en-us/library/system.threading.semaphoreslim(v=vs.110).aspx) instance variable on PermissionsImplementation?  You can await the SemaphoreSlim's availability with its [WaitAsync](https://msdn.microsoft.com/en-us/library/hh462805(v=vs.110).aspx) method.

**Comment by justinimel** [comment]
This was my issue and SemaphoreSlim solved it for me. Thanks for the tip!

**Comment by johnshardman** [comment]
Getting the same problem.

Semaphore just on RequestPermissionsAsync or also other methods as well (e.g. CheckPermissionStatusAsync) ?

**Comment by inkrh** [comment]
More of a "me too" post. I'm seeing the same issue with PermissionsPlugin occuring when using xam.plugins.geolocator (not hitting permissions myself). 

It has only occurred on the Android side (so far), not on the iOS side.  

> Exception: Message: An attempt was made to transition a task to a final state when it had already completed.; StackTrace: at System.Threading.Tasks.TaskCompletionSource`1[TResult].SetResult (TResult result) [0x00013] in <06ef333e5e2644c1b4965d5d27f9ec90>:0 at Plugin.Permissions.PermissionsImplementation.OnRequestPermissionsResult (System.Int32 requestCode, System.String[] permissions, Android.Content.PM.Permission[] grantResults) [0x0007d] in <47bb53b40691435f96893bccf92fcd93>:0 at UnderSea.Droid.MainActivity.OnRequestPermissionsResult (System.Int32 requestCode, System.String[] permissions, Android.Content.PM.Permission[] grantResults) [0x00005] in <fcd2336abada4fd1b8166ea20ef37969>:0 at Android.Support.V4.App.FragmentActivity.n_OnRequestPermissionsResult_IarrayLjava_lang_String_arrayI (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 requestCode, System.IntPtr native_permissions, System.IntPtr native_grantResults) [0x00038] in <7e083afc7c9045f59e01d9c14931060d>:0 at (wrapper dynamic-method) System.Object:8d1d0ec0-02e8-48c3-9419-cf668207bd90 (intptr,intptr,int,intptr,intptr); Source: mscorlib;

**Comment by jamesmontemagno** [comment]
Would need sample code, you may be calling it multiple times so put some checks around it.

**Comment by inkrh** [comment]
Just re-checked the code, and yes it was being called twice on app launch. Removed the duplicate call which got rid of the error.

**Comment by rd09** [comment]
If you want to trap this exception just go to the MainActivity where OnRequestPermissionsResult is overriden and put a try...catch around: PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);

This way you avoid a crash.
