### ISSUE TITLE
Not seeing 'system prompt' for the ReadCalendar permission when the build target is set to 'automatic'

### ISSUE THREAD

**Issue by TohWei** [jamesmontemagno/PermissionsPlugin#29]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 
Hi,.. I am using the latest version of “Plugin.Permission"  from the nuget to my app.  I have been spending few hours to figure out why I keep NOT able to see the ‘system prompt’ when I ask for the Permission to ReadCalendar (via the RequestPermissionsAsync() method).  At the end, ..I think I found a bug…  

According to your spec, it has to be at least SDK >= 23. My target is 24. So,..by right I should see the ‘prompt’.  According to my test results: 
1. If I set the target android version explicitly to: override - Android 7.0 (API level 24),   or to override - Android 6.0 (API level 23), then I will see the prompt. 
2. However, my setting was:
Target Android version: Automatic - use target framework version (API 24).  Whenever it is with ‘Automatic - then no prompt will be shown.

Version Number of Plugin: 1.2.1
Device Tested On: Samsung Galaxy S6, Android version: 6.0.1

### Expected Behavior
Should see the 'Prompt' after the requestPermissionAsync method() even if I have the target build set to automatic - use target framework version (API 24). 

### Actual Behavior
Whenever it is with ‘Automatic - then no prompt will be shown.

**Comment by jamesmontemagno** [comment]
You can't set Target to Automatic, you MUST choose a target. It is how Android itself works. Automatic is a terrible choice because it doesn't actually add it to your AndroidManifest.xml

I have actually already filed a bug on bugzilla for this for the IDE to insert it into your AndroidManifest.xml

Out of my control.

**Comment by TohWei** [comment]
We have been using 'auto' most of the time. Surprised to hear that the 'auto' doesn't actually add it to Manifest.  Thanks for the tips.
