### ISSUE TITLE
App Crash when I PushModalAsync a new page while Permission popup is shown.

### ISSUE THREAD

**Issue by allbdeveloper** [jamesmontemagno/PermissionsPlugin#30]
If I PushModalAsync a new page while permission popup is still shown on Android(with forms AppCompat). 
App crash.

My new modal page needed to be pushed automatically in some case like a announcement.

I could set boolean variable before await RequestPermissionsAsync and after, to open new page while popup is not shown to avoid crash. (It's working fine)

But I think there is better solution. 
Any suggestion?

**Comment by jamesmontemagno** [comment]
Can you put the stack trace into http://gist.github.com for me and post here so I can see what the crash was.

It is not a use case that I would support to push a page while the prompt was open. I would not do that at all as I am not sure what would even happen in non-forms apps.

**Comment by allbdeveloper** [comment]
exception was Java.Lang.IllegalStateException: Can not perform this action after
onSaveInstanceState.

I'm sure you know this.
I will put stacktrace too in a future.

**Comment by jamesmontemagno** [comment]
This is a Xamarin.Forms issue, not an issue in the library. This means you are attempting to navigate too fast before the Fragments have re-hydrated. 

You should try something like:

await Task.Delay(100); 

to see if that artificial delay helps.

**Comment by allbdeveloper** [comment]
Yes. You're right. 
Xamarin's bugzilla is better place to say. 

I tried your suggestion but same crash again. 
I can't pushModalPage while the prompt is opened. 

> Java.Lang.RuntimeException: Can not perform this action after onSaveInstanceState
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <5ba073af17cd4220bb60f6d1acb0950e>:0
>   at Java.Interop.JniEnvironment+InstanceMethods.CallIntMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method) [0x00084] in <2af388b7a2e94afe89596a2181bd5056>:0
>   at Android.Runtime.JNIEnv.CallIntMethod (System.IntPtr jobject, System.IntPtr jmethod) [0x0000e] in <2c7dc34cd8314860bd3e55b10e55d264>:0
>   at Android.Support.V4.App.FragmentTransactionInvoker.Commit () [0x00033] in <27c17fe440cf491ba8255bcefade6e02>:0
>   at Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.SwitchContentAsync (Xamarin.Forms.Page view, System.Boolean animated, System.Boolean removed, System.Boolean popToRoot) [0x0014b] in C:\BuildAgent2\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:621
>   at Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.OnPushAsync (Xamarin.Forms.Page view, System.Boolean animated) [0x00000] in C:\BuildAgent2\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:452
>   at Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.PushViewAsync (Xamarin.Forms.Page page, System.Boolean animated) [0x00000] in C:\BuildAgent2\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:108
>   at Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e) [0x0018e] in C:\BuildAgent2\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:252
>   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000f4] in C:\BuildAgent2\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:193
>   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in C:\BuildAgent2\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:129
>   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element) [0x0001f] in C:\BuildAgent2\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\Platform.cs:289
>   at Xamarin.Forms.Platform.Android.AppCompat.Platform+ModalContainer..ctor (Android.Content.Context context, Xamarin.Forms.Page modal) [0x00038] in C:\BuildAgent2\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:335
>   at Xamarin.Forms.Platform.Android.AppCompat.Platform.PresentModal (Xamarin.Forms.Page modal, System.Boolean animated) [0x0000d] in C:\BuildAgent2\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:285
>   at Xamarin.Forms.Platform.Android.AppCompat.Platform+<Xamarin-Forms-INavigation-PushModalAsync>d__30.MoveNext () [0x0004a] in C:\BuildAgent2\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:150
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <5ba073af17cd4220bb60f6d1acb0950e>:0
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <5ba073af17cd4220bb60f6d1acb0950e>:0
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <5ba073af17cd4220bb60f6d1acb0950e>:0
>   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <5ba073af17cd4220bb60f6d1acb0950e>:0
>   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <5ba073af17cd4220bb60f6d1acb0950e>:0
>   at Xamarin.Forms.Application+NavigationImpl+<OnPushModal>d__3.MoveNext () [0x0008d] in C:\BuildAgent2\work\ca3766cfc22354a1\Xamarin.Forms.Core\Application.cs:330
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <5ba073af17cd4220bb60f6d1acb0950e>:0
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <5ba073af17cd4220bb60f6d1acb0950e>:0
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <5ba073af17cd4220bb60f6d1acb0950e>:0
>   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <5ba073af17cd4220bb60f6d1acb0950e>:0
>   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <5ba073af17cd4220bb60f6d1acb0950e>:0
>   at allbX.AnnouncePage+<CheckNewAnnounce>c__async0.MoveNext () [0x002df] in /Users/bright/Devlibs/project/allb_xamarin/allbX/allbX/Pages_NotiTab/AnnouncePage.xaml.cs:118
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <5ba073af17cd4220bb60f6d1acb0950e>:0
>   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__1 (System.Object state) [0x00000] in <5ba073af17cd4220bb60f6d1acb0950e>:0
>   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) [0x0000e] in <5ba073af17cd4220bb60f6d1acb0950e>:0
>   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x0008d] in <5ba073af17cd4220bb60f6d1acb0950e>:0
>   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <5ba073af17cd4220bb60f6d1acb0950e>:0
>   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x0002a] in <5ba073af17cd4220bb60f6d1acb0950e>:0
>   at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00096] in <5ba073af17cd4220bb60f6d1acb0950e>:0
>   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <5ba073af17cd4220bb60f6d1acb0950e>:0
>   at java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
>   at at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1493)
>   at at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1511)
>   at at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:638)
>   at at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:617)
>

**Comment by allbdeveloper** [comment]
![screen shot 2016-11-28 at 2 05 41 pm](https://cloud.githubusercontent.com/assets/14910356/20656864/28838968-b574-11e6-8241-6992a6fb6427.png)

**Comment by allbdeveloper** [comment]
I wrote on bugzilla too. 
Thanks.

https://bugzilla.xamarin.com/show_bug.cgi?id=48147

**Comment by jamesmontemagno** [comment]
Thanks. Closing as it is with Xamarin.Forms, not the library. Looks like they may have some pull requests in there currently for workarounds. The solution currently is not to do that.

**Comment by allbdeveloper** [comment]
Yes. you're right. 
Thanks.
