### ISSUE TITLE
Permission plugin not working in Xamarin.Forms project

### ISSUE THREAD

**Issue by xerotolerant** [jamesmontemagno/PermissionsPlugin#32]
The Plugin fails in my project. No pompt is displayed when 
    `var results = await CrossPermissions.Current.RequestPermissionsAsync(new[] {Permission.Location});`
is run. The permission status can be determined by running 

    `varstatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Location);`

If the permission is manually changed in Android's settings the value returned would say granted or denied correctly. However no matter what I do no prompt is showing. No Error message. nothing at all. I made sure to add 
      ```
public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grant Results)
        {
            PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }
```

to MainActiviy in MainActivity.cs

Version Number of Plugin: 1.2.1

Device Tested On:
Samsung galaxy S6 and HTC Nexus 9

I posted a question on[StackOverflow](http://stackoverflow.com/questions/41473975/xamarin-forms-android-permission-prompt-not-displaying) and in the [xamarin forum](https://forums.xamarin.com/discussion/85836/how-to-use-xamarin-forms-maps-in-android-6)
### Expected Behavior
Prompt for permission would show.
### Actual Behavior
No prompt. Things that rely on permission, in this case Xamarin.Forms.Maps throw unhandled exception

**Comment by jamesmontemagno** [comment]
Make sure you are targeting and compiling against API 23. You must manually set this. Please see readme.

**Comment by xerotolerant** [comment]
I did have it set. I followed the readme to the letter. The issue was that  there was no MainApplication in my project. I had to manually add one. I am not sure why though since the application was already working properly before change the target api.

**Comment by jamesmontemagno** [comment]
The MainApplication.cs should get automatically installed for you with the CurrectActivity Plugin. Glad it was all working now.
