### ISSUE TITLE
Make MainApplication partial

### ISSUE THREAD

**Issue by Cheesebaron** [jamesmontemagno/PermissionsPlugin#33]
Not a bug. However, lets say framework X implement their own Application class, it would be desirable to have both this and the framework's Application class co-exist.

Would it be possible to mark MainApplication partial along with the methods it implements?

**Comment by jamesmontemagno** [comment]
Hmmmm, the file just gets added in automatically, could the dev just change it today?

I am sure we could try this out. 

Ideally devs would just inherit from Framework X's application class in my MainApplication.cs

**Comment by Cheesebaron** [comment]
What will happen if they also call it MainApplication? Wouldn't it get overrriden?

**Comment by jamesmontemagno** [comment]
You would have different namespaces.

A framework can add an Application implementation, but should NOT add the [Application] attribute, this is where the issue could come in. 

Ideally it would be:

```
[Application]
public class MainApplication: FrameworkXApplication
{

}
```

This should probably move to: https://github.com/jamesmontemagno/CurrentActivityPlugin as that is where this file comes from.

**Comment by jamesmontemagno** [comment]
Moved to correct github page for this
