### ISSUE TITLE
[UWP]CheckPermissionStatusAsync unexpectedly popping up dialog

### ISSUE THREAD

**Issue by johnshardman** [jamesmontemagno/PermissionsPlugin#34]
## Bug 

Version Number of Plugin: 1.2.1
Device Tested On: Windows 10 desktop, built as x86 but running on x64 (an issue in Xamarin.Auth is preventing build of x64 at present)

### Expected Behavior
CheckPermissionStatusAsync should return a value but not pop up a dialog
RequestPermissionsAsync should pop up a dialog

### Actual Behavior
CheckPermissionStatusAsync pops up the dialog saying

Let YourApp access your precise location?
To change this later, go to the Settings app.
Yes No

**Comment by jamesmontemagno** [comment]
I think unfortunately there is no control over this and happens due to UWP itself.
