### ISSUE TITLE
#Bug CheckPermissionStatusAsync(Permission.Calendar) on Andriod always returns Granted

### ISSUE THREAD

**Issue by michelmoorlag** [jamesmontemagno/PermissionsPlugin#35]
## Bug 
First thanks for this really sweet plugin!

Version Number of Plugin: v2.5.2.1
Device Tested On: Motorola Moto E second generation with 4G LTE on Android 6.0

### Expected Behavior
When I install the app the calender permission is granted automatically which is fine and all works ok.
When I revoke the permission manually and I kill the app I would expect permission Denied or Disabled.

### Actual Behavior
I get permission Granted while I revoked the calender permission for my app. When I try to get the calender list I won't get any calanders any more which is logical since it has no permissions any more.

### Steps to reproduce the Behavior
I followed al steps in the plugin readme to the letter and on IOS it all works fine. On android I install the app, go to settings, apps, settings, app-permissions, Calender and I revoke the calender permission for my app. Then I restart the app and the CheckPermissionStatusAsync(Permission.Calendar) will return Granted. This is not what I would expect.

**Comment by jamesmontemagno** [comment]
You must manually set the target version number to 6.0+ as use compiled doesn't set the manifest

**Comment by michelmoorlag** [comment]
Yup you are right. It seems I mist the capital MUST in: You MUST set your Target version to API 23+ and Compile against API 23+
I feel a little silly and I should!
Sorry for wasting your time :(

**Comment by jamesmontemagno** [comment]
It's all good. These posts kinda live as additional documentation.
