### ISSUE TITLE
#Bug CheckPermissionStatusAsync(Permission.Calendar) on Andriod always returns Granted

### ISSUE THREAD

**Issue by NVentimiglia** [jamesmontemagno/PermissionsPlugin#36]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin:
1.2.1
Device Tested On:
NVIDIA Shield
Android 6.0.1

### Expected Behavior
var val = await CrossPermissions.Current.CheckPermissionStatusAsync(permission);
val should be Denied.

### Actual Behavior
val is Granted

### Steps to reproduce the Behavior
In System App settings deny permission to camera, ect.
Run app with plugin

**Comment by NVentimiglia** [comment]
https://github.com/jamesmontemagno/PermissionsPlugin/issues/35

**Comment by NVentimiglia** [comment]
![image](https://cloud.githubusercontent.com/assets/125889/22621754/c44770ee-eadf-11e6-9ef5-9d17f08b73dd.png)

**Comment by jamesmontemagno** [comment]
You Must set the target version to 6.0+

**Comment by jamesmontemagno** [comment]
It can't be use compile as it doesn't get added to manifest
