### ISSUE TITLE
RequestPermissionsAsync(Permission.Sensors) always returns PermissionStatus.Denied in iOS emulator

### ISSUE THREAD

**Issue by idan-rubin** [jamesmontemagno/PermissionsPlugin#37]
the method RequestPermissionsAsync(Permission.Sensors) returns PermissionStatus.Denied even after allowing access to NSMotionUsageDescription in iOS iPhoneSimulator (clicking 'Ok' button)

Version Number of Plugin: 1.2.1
Device Tested On: Emulator only
Simulator Tested On: iPhone 6 iOS 10.1

### Expected Behavior
returned value is PermissionStatus.Granted
### Actual Behavior
returned value is PermissionStatus.Denied

### Steps to reproduce the Behavior
repro steps:
1. Add the following property to info.plist:
<key>NSMotionUsageDescription</key>
<string></string>
2. Call CrossPermissions.Current.RequestPermissionsAsync(Permission.Sensors);
3. When prompted, click 'Ok' button in permission dialog
4. Check returned value

**Comment by jamesmontemagno** [comment]
It is not supported on Simulators

**Comment by idan-rubin** [comment]
Thanks James! That's what I suspected too, but wanted to confirm.
