### ISSUE TITLE
RequestPermissionsAsync hangs when calling with a Permission array

### ISSUE THREAD

**Issue by idan-rubin** [jamesmontemagno/PermissionsPlugin#38]
## Bug 
When passing the following permission array to RequestPermissionsAsync, the dialog for Permission.Sensors is never shown.
private static Permission[] permissionList = new Permission[]
            {
                Permission.Storage,
                Permission.Camera,
                Permission.Location,
                Permission.Sensors
            };

Version Number of Plugin: 1.2.1
Device Tested On: Emulator only
Simulator Tested On: iPhone 6 iOS 10.1

### Expected Behavior
Permission dialog is shown for Permission.Sensors and RequestPermissionsAsync method returns.
### Actual Behavior
Camera and Location dialogs are shown, then app hangs and RequestPermissionsAsync doesn't return

### Steps to reproduce the Behavior
1. Add the following properties to info.plist:
    <key>NSCameraUsageDescription</key>
    <string></string>
    <key>NSLocationWhenInUseUsageDescription</key>
    <string></string>
    <key>NSMotionUsageDescription</key>
    <string></string>
2. Call CrossPermissions.Current.RequestPermissionsAsync with the Permission array from above:
var result = await CrossPermissions.Current.RequestPermissionsAsync(permissionList);

**Comment by jamesmontemagno** [comment]
What if you only call it with sensors? Do you have the correct settings set in the info.plist?

**Comment by jamesmontemagno** [comment]
See your other post as that permission isn't supported on emulators, try on a device.

**Comment by idan-rubin** [comment]
Much obliged.
