### ISSUE TITLE
CrossPermissions.Current.RequestPermissionsAsync always returns PermissionStatus.Unknown.

### ISSUE THREAD

**Issue by pradeeparutla** [jamesmontemagno/PermissionsPlugin#39]
CrossPermissions.Current.RequestPermissionsAsync always returns PermissionStatus.Unknown.

## Bug 

Version Number of Plugin: 1.2.1
Device Tested On: Android 6.0 OS
Simulator Tested On:

### Expected Behavior
CrossPermissions.Current.RequestPermissionsAsync  should return the status as PermissionStatus.Granted.

### Actual Behavior
CrossPermissions.Current.RequestPermissionsAsync always returns PermissionStatus.Unknown.

### Steps to reproduce the Behavior
Request the permission using the below statement in dependency service in android project.

var results =  await CrossPermissions.Current.RequestPermissionsAsync(new[] { Permission.Camera, Permission.Storage });

 cameraStatus = results[Permission.Camera]; //CameraStatus is always returned as PermissionStatus.Unknown

I am using the plugin.currentactivity in android project.

Note: I am writing the above code in custom control and using it later in the actual application.

**Comment by pradeeparutla** [comment]
When I check in the code permissionStatus.Unknown is returned in the below scenario. Do I need to do anything in my application for this ?  Debug.WriteLine("Unable to detect current Activity or App Context. Please ensure Plugin.CurrentActivity is installed in your Android project and your Application class is registering with Application.IActivityLifecycleCallbacks.")

**Comment by jamesmontemagno** [comment]
Did you do this: https://github.com/jamesmontemagno/PermissionsPlugin#android-specific-in-your-baseactivity-or-mainactivity-for-xamarinforms-add-this-code


When you install this plugin it will also install a file called "MainApplication.cs" into your Android app and that needs to be there.

**Comment by pradeeparutla** [comment]
It is now working. Application.cs class is missing from my project. Thankyou James for the reply

**Comment by savvaskef** [comment]
I have the exact same problem. but no application.cs was added nor a mainapplication.cs when i updated the Mediaplugin and installed PermissionsPlugin.
Do I also need to change MainActivity.cs?(It already has an override for on OnRequestPermissionsResult )

**Comment by Kiran23-ui** [comment]
Thanks @savvaskef  
Helped me in solving the issue
