### ISSUE TITLE
Is it possible to use without singleton?

### ISSUE THREAD

**Issue by thefenix1** [jamesmontemagno/PermissionsPlugin#4]
Since singleton approach will affect possibilities to do a clean unit test I was wondering if this would just work just injecting IPermissions as a singleton instance on constructor.

Thanks!

**Comment by jamesmontemagno** [comment]
The best way to do testing is simply is to implemented your own IPermissions

Then, in your shared code to test do something like this:

```
public static IPermissions Permissions
{
   get 
   { 
     //if in unit testing return your implementation, else return
      return CrossPermissions.Curren; 
    }
}
```
