### ISSUE TITLE
NuGet packages not up to date

### ISSUE THREAD

**Issue by geoffreys** [jamesmontemagno/PermissionsPlugin#40]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 
NuGet package currently published (1.2.1) does not include recent fixes, specifically the permissions check order flip on iOS from 23/Dec/16  (https://github.com/jamesmontemagno/PermissionsPlugin/commit/f18dfdeaaa47d8d8f0dc70003d2dc3f2f495b536#diff-0231fffb2dcaf285d46c31f201305e10 )

Version Number of Plugin: NuGet 1.2.1 / current release
Device Tested On: n/a
Simulator Tested On: iOS 10 Simulator

### Expected Behavior
iOS Location 'Always' setting is given precedence over 'When In Use' per the above commit via NuGet package

### Actual Behavior
NuGet package is old and does not include the above fix

### Steps to reproduce the Behavior
Using current NuGet package 1.2.1, on iOS project add both Always and When In Use location permission requests to info.plist, then use the plugin to request permission.  

Doesn't give priority to Always option, which was fixed in the commit referenced above.

## Feature Request:
Please fill in what you would like

**Comment by jamesmontemagno** [comment]
Not sure why you would add both to your info.plist as you only need one to be honest.

**Comment by jamesmontemagno** [comment]
OUtput a new beta, but you can also add the development nuget feed: https://ci.appveyor.com/nuget/permissionsplugin
