### ISSUE TITLE
Should be able to capture the photos in square shape

### ISSUE THREAD

**Issue by pradeeparutla** [jamesmontemagno/PermissionsPlugin#42]
I have a requirement to capture the image in the form of square (or) provide an option for  pan/crop captured image in the image preview before saving.

### Expected Behavior
Should be able to capture the images in the square shape in both android and iOS.

### Actual Behavior
Currently there is no option to capture the image in the form of square in Android and iOS devices.

## Feature Request:
I have a requirement to capture the image in the form of square (or) provide an option for  pan/crop captured image in the image preview before saving.

**Comment by jamesmontemagno** [comment]
This is not supported and no plans to add cropping.

**Comment by pradeeparutla** [comment]
You mean, capturing the pictures using sqare shape is not supported?

**Comment by jamesmontemagno** [comment]
It launches the default camera and maybe it has an option to do a square photo or cropping, but this library does not and will not provide that functionality.

**Comment by jamesmontemagno** [comment]
Also you probably meant to put this in the MediaPlugin, not the PermissionsPlugin repo.
