### ISSUE TITLE
[UWP] Accepted permission decision not stored on Windows 10 Desktop

### ISSUE THREAD

**Issue by No1e** [jamesmontemagno/PermissionsPlugin#43]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 1.2.1
Device Tested On: HP ElitePad 900 

### Expected Behavior
Once user accepts permissions, they shall be stored and user shall not be asked again.

### Actual Behavior
User is asked each time to give permissions to application.

### Steps to reproduce the Behavior
Create simple Xamarin.Forms UWP project that request some permissions in runtime, run app on Win 10.

## Feature Request:
Please fill in what you would like

**Comment by jamesmontemagno** [comment]
Which permission? Not very helpful here. Please add code sample.

**Comment by No1e** [comment]
Hi James,

An example below works on:
- Android 6 (consumer, industrial devices)
- iOS 10.2.1 (iPhones, iPads)
- Winows Phone 10.0.14393.953 (Phone Microsoft RM-1104_15442)
Not working on:
- Windows Desktop 10.0.10240.16725 ( Tablet HP ElitePad 900).

Here is the code:
```
Permission[] requiredPermissions = new Permission[] { Permission.Location, Permission.Camera };
bool permisstionGranted = false;
PermissionStatus status;

foreach (var permission in requiredPermissions)
{
	permisstionGranted = false;

	while (!permisstionGranted)
	{
		status = await CrossPermissions.Current.CheckPermissionStatusAsync(permission);

		if (status != PermissionStatus.Granted)
		{
			var results = await CrossPermissions.Current.RequestPermissionsAsync(new Permission[] { permission });

			if (results[permission] == PermissionStatus.Granted)
			{
				permisstionGranted = true;
			}
		}
		else
		{
			permisstionGranted = true;
		}
	}
}
```

**Comment by jamesmontemagno** [comment]
which permission is popping up on Windows 10 multiple times? what line of code does it pop up at?

**Comment by No1e** [comment]
1. It was asking for location permission.

2. I expect the method responsible  CrossPermissions.Current.RequestPermissionsAsync 
I guess this is the only one that pops up dialog to user.

As soon as I get device back I will try it out, and give you info regarding 2.

**Comment by dominik-weber** [comment]
It seems like UWP is asking for the location permission again every time you create a new build (i.e. press run in visual studio). I don't think this is a bug of this library, but rather a design decision made by the UWP team.
Have you tried launching the app from the start menu to check if the permission is stored in this case?

**Comment by jamesmontemagno** [comment]
I am unable to reproduce with my sample that is in this repo.
