### ISSUE TITLE
 Application cannot have both a type with an [Application] attribute and an [assembly:Application] attribute.

### ISSUE THREAD

**Issue by KarenMuller** [jamesmontemagno/PermissionsPlugin#5]
I get the following error after adding the permissions plugin to my android app.

Error MSB4018: The "GenerateJavaStubs" task failed unexpectedly.
System.InvalidOperationException: Application cannot have both a type with an [Application] attribute and an [assembly:Application] attribute.
   at Xamarin.Android.Tasks.ManifestDocument.CreateApplicationElement(XElement manifest, List`1 subclasses, List`1 selectedWhitelistAssemblies)
   at Xamarin.Android.Tasks.ManifestDocument.Merge(List`1 subclasses, List`1 selectedWhitelistAssemblies, Boolean embed, Boolean replaceSplashScreen, IDictionary`2 splashScreenClasses, String bundledWearApplicationName, IEnumerable`1 mergedManifestDocuments)
   at Xamarin.Android.Tasks.GenerateJavaStubs.Run()
   at Xamarin.Android.Tasks.GenerateJavaStubs.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() (MSB4018)

**Comment by SamuelDebruyn** [comment]
This plugin depends on https://github.com/jamesmontemagno/CurrentActivityPlugin
The Current Activity plugin adds an `Application` class to your Android project. Make sure there's only one `Application` class and attribute in your Android project.

**Comment by jamesmontemagno** [comment]
^ Yup!

Simply add the code from the Application class I bring in into your Application class.

**Comment by jmartine2** [comment]
How can I do this if I'm using the Nuget version?

**Comment by jamesmontemagno** [comment]
You have to install the NuGet into your Android app and it automatically get added for you. @jmartine2

**Comment by fgiacomelli** [comment]
Hello, I have the same problem using your plugin permission, I see that I have the class MainApplication.cs in my Droid project, what can I check to solve my problem?
Thank you

**Comment by anniexclusive** [comment]
I had the same issue and tried merging the two Activity classes but there are errors. here is my own activity class:

` using System;

using Android.App;
using Android.Content.PM;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Android.OS;
using Android.Media;
using Plugin.CurrentActivity;

namespace bnwPcl.Droid
{
    [Activity(Label = "BreadAndWine", Icon = "@drawable/iconn", Theme = "@android:style/Theme.Holo.Light")]    
    public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsApplicationActivity
    {
        MediaPlayer _player;

       
        protected override void OnCreate(Bundle bundle)
        {

            base.OnCreate(bundle);            
            _player = MediaPlayer.Create(this, Resource.Raw.ancient_words);
            _player.Start();

            //var title = "Bread and Wine";
            //SetTitle(title);

            global::Xamarin.Forms.Forms.Init(this, bundle);            
            LoadApplication(new App());
            //_player.setLooping(true);            
           
        }
        public void onUserLeaveHint()
        {
            _player.Stop();
            base.OnUserLeaveHint();
        }
        public void onPause()
        {
           
            base.OnPause();
            _player.Pause();
        }
        public void onResume()
        {
            base.OnResume();
            _player.Start();
        }
    }
}`

**Comment by Jrage** [comment]
for me it was in my AssemblyInfo.cs
#if DEBUG
[assembly: Application(Debuggable=true)]
#else
[assembly: Application(Debuggable=false)]
#endif

**Comment by mazloumi** [comment]
Jrage: How did you resolve the issue with AssemblyInfo.cs?

**Comment by Jrage** [comment]
mazloumi: sorry, I have no recollection of this at all, I can't remember the project, the problem, my solution, nor informing you all. So sorry, in the future I will attempt to make better future proof answers. :/

**Comment by michelmoorlag** [comment]
@mazloumi 
Remove those lines from your AssemblyInfo.cs.
Look for the Android class that has the [Application] attribute above it (in my case MainApplication) and replace that attribute with:
#if DEBUG
[Application(Debuggable = true)]
#else
[Application(Debuggable = false)]
#endif
That fixed the above error for me.

**Comment by slam023** [comment]
For me in my main application, I have an application attribute and extend with Application. I remove the Application attribute, then it works
