### ISSUE TITLE
 [ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.

### ISSUE THREAD

**Issue by ShahriatHossain** [jamesmontemagno/PermissionsPlugin#52]
I am trying to prompt user to allow permission for storage:

var results = await CrossPermissions.Current.RequestPermissionsAsync(Permission.Storage);

but getting this exception System.InvalidOperationException. Can anybody face the same problem and what should be solution to fix this problem.

**Comment by jamesmontemagno** [comment]
This means you have multiple operations going at the same time or you didn't update your Activity to forward on the event. Check the docs
