### ISSUE TITLE
Problem in the MAC

### ISSUE THREAD

**Issue by brunoracosta** [jamesmontemagno/PermissionsPlugin#55]
After I install the package, I receive a error on the build time

This message is show

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(3,3): Error: java.lang.IllegalArgumentException: already added :  Landroid/support/v4/view/VelocityTrackerCompat; (Project.Droid)

## Bug Information

Version Number of Plugin: 2.0.1
Version of VS: VS for MAC
Version of Xamarin: Xamarin Forms 2.3.4.231
Versions of Framework: .NET Portable: PCL 4.6 - Profile44

**Comment by jamesmontemagno** [comment]
This means you probably haven't upgraded all of your Support compat to 25.3.1 see: http://motzcod.es/post/162402194007/plugins-for-xamarin-go-dotnet-standard

**Comment by jamesmontemagno** [comment]
Also make sure you clean/rebuild fully too
