### ISSUE TITLE
TaskCanceled Exception

### ISSUE THREAD

**Issue by czuvich** [jamesmontemagno/PermissionsPlugin#56]
## Bug Information

I'm seeing a TaskCanceledException when trying to request permissions for Location.  I stepped through the code, and what I'm seeing is the following:

RequestPermissionsAsync() the line tcs.Task.ConfigureAwait(false); is causing the code to execute RequestPermissionsAsync again which causes the tcs to get set to null.

Version Number of Plugin:  2.0.1
Device Tested On: Moto G4 16GB running Android 7.0
Simulator Tested On: N/A
Version of VS: Visual Studio for Mac
Version of Xamarin: Xamarin Forms 2.3.4
Versions of other things you are using:

### Steps to reproduce the Behavior
Create an Activity, call the await RequestPermissionsAsync(Location).

### Expected Behavior
No crash

### Actual Behavior
Crash

**Comment by czuvich** [comment]
Nevermind.  User error.

**Comment by kevincraig** [comment]
what was the user error I'm seeing this now as well, figured it was something I did but I'm just not seeing it.
