### ISSUE TITLE
I DON'T KNOW WHICH TITLE FOR THIS ERROR?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [jamesmontemagno/PermissionsPlugin#57]
I try with New Empty Project
1. Install Plugin.Permission of James Montemagno
2. I get this error "java.lang.IllegalArgumentException: already added : Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat;"
3. I try Enable Multi-Dex
4. I get this error "Can't write [C:\Users\nguye\AppData\Local\Temp\mainDexClasses-11498.tmp.jar] (Can't read [C:\Users\nguye\AppData\Local\Xamarin\Xamarin.Android.Support.v4\23.3.0.0\embedded\classes.jar] (Duplicate zip entry [classes.jar:android/support/v4/view/ViewCompat$JbMr1ViewCompatImpl.class]))"
5. No comment!

**Comment by christophedemey** [comment]
I also get this error :(

**Comment by christophedemey** [comment]
I found on xamarin forums to update appcomat v4 package, but updating packages yields a pathTooLongException, yay xamarin 🗡

**Comment by nguyenthanhliemfc** [comment]
I found it. Change your Profile259 to Profile111. IF not try update all packet in Nuget

**Comment by christophedemey** [comment]
@nguyenthanhliemfc  where ?

**Comment by jamesmontemagno** [comment]
You need to update all of your support packages to 25.3.1
