### ISSUE TITLE
[Android] Incorrect value being returned for permission status

### ISSUE THREAD

**Issue by Xandroid4Net** [jamesmontemagno/PermissionsPlugin#59]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 2.0.1
Device Tested On: Galaxy S5 Android 6.0.1
Simulator Tested On: Genymotion Pixel Android 7.1
VS For Mac: 7.1.3 (build 1)
Versions of other things you are using: N/A

### Steps to reproduce the Behavior
Target Android API 25
Install your app that requests permissions using this plugin.
Press the home key so the app goes to the background.
Go into Settings > Application Manager > App and deny the permission you have requested.
Go back to the app and check if the permission has been granted.

### Expected Behavior
The Permission plugin should return that the permission is not granted.

### Actual Behavior
The Plugin reports that the permission is granted.

### Screenshots
In the below screen shot it can be seen that android has a bug in the CheckSelfPermisson.
This SO Post led me to a possible solution
https://stackoverflow.com/questions/35342667/androids-contextcompat-checkselfpermission-returns-incorrect-value

Possible fix: Plugin should be updated to use PermissionChecker

![screen shot 2017-09-19 at 10 55 43 am](https://user-images.githubusercontent.com/5997627/30607430-d885923c-9d29-11e7-99ee-f17661db939a.png)

**Comment by jamesmontemagno** [comment]
Can you take a screenshot of your Target/Min/Compile settings?

Ensure they are MANUALLY set and NOT "use compile"

**Comment by Xandroid4Net** [comment]
Here is the shot.
![screen shot 2017-09-19 at 5 31 36 pm](https://user-images.githubusercontent.com/5997627/30621518-73641176-9d60-11e7-9fe0-586dbba7b599.png)

**Comment by jamesmontemagno** [comment]
Yes, you can not use Automatic, you MUST set it manually to API 25.
