### ISSUE TITLE
Bluetooth Permission on Android

### ISSUE THREAD

**Issue by IlSocio** [jamesmontemagno/PermissionsPlugin#6]
Hi James, 
looking at the code, it seems that currently the Bluetooth permission is not supported on Android, am I right?
Do you have any plan to support it in the future?

Thanks,
Marco.

**Comment by jamesmontemagno** [comment]
There is no run time permission check needed for Bluetooth. You simply add it to your manifest and it is always granted. There is no need for it to be added. 

See: https://developer.android.com/training/permissions/requesting.html

**Comment by IlSocio** [comment]
Thank you james for the explaination and please accept my apologies for bothering :)

**Comment by jamesmontemagno** [comment]
There is no bother at all :) Good question.
