### ISSUE TITLE
2 problems and one question

### ISSUE THREAD

**Issue by Moltroon** [jamesmontemagno/PermissionsPlugin#61]
Hello,
I have post my problem on [Xamarin Forum](https://forums.xamarin.com/discussion/comment/299075#Comment_299075)
I would appreciate it if you could help Mr. Montemagno. Thank you for your work.

**Comment by prashantvc** [comment]
Tagged James on the forum post, I think we should keep this discussion on the forum. If you feel otherwise, please create a new issue with all the details in relevant Github repos
