### ISSUE TITLE
CrossPermissions.Current.RequestPermissionsAsync not shows any alert to request permission

### ISSUE THREAD

**Issue by MartinGian** [jamesmontemagno/PermissionsPlugin#62]
## Bug Information

Version Number of Plugin: latest
Device Tested On: Android 6.0 (simulator)
Version of VS: 2017

### Steps to reproduce the Behavior

CrossPermissions.Current.RequestPermissionsAsync always returns Unknown, and never shows an alert to request the permissions

I'm requesting the permissions in this specific line:
https://github.com/MartinGian/dona/blob/b892fae88cc93b005ae6d025b6409a6f1f7a3d40/donation-mvp/Services/SmsService.cs#L43

AND I use that UI Service inside my viewmodels.

I already added the override of OnRequestPermissionsResult in the MainActivity in the Droid project.

Please help! 
Thanks.

**Comment by jamesmontemagno** [comment]
You MUST set your Target version to API 25+ and Compile against API 25+:

**Comment by MartinGian** [comment]
That was not the problem. The problem was that I already have a MainApplication.cs file when I installed the plugin, and the installation didn't generate another file or any modification to the existing file. 
So I installed the plugin on a blank project, and copy the changes from the generated MainApplication.cs file to mine.
It's working now.

**Comment by dernippel** [comment]
I had the same Issue today.
To solve it I had to install the Plugin.CurrentActivity Package in the Android Project manually and create the MainApplication.cs by myself (copied the file from my former pcl-based project).

Additional Information:
I'm using a freshly .netstandard Xamarin.Forms project created by the Prism Template Pack. The "Plugin.CurrentActivity"-Package was shown as a dependency at the installation of PermissionsPlugin but wasn't installed.

Versions:
Compile: Android 8.0 (API 26)
Android Minimum: API 22
Android Target: API 25

Xamarin.Forms: v2.5.0.121934
Xamarin.Android.Support.*: v26.1.0.1

**Comment by iCursao** [comment]
Hi,
I'm facing the same issue.
I've a Xamarin.Forms project, I need to show the permission popup just in android (phoneStateListener). I've an application in my PCL Project can I add one to the Xamarin.Android project?
if I con do this, what I've to put inside the init of the CurrentActivity Plugin?

**Comment by jamesmontemagno** [comment]
You must setup the current activity plugin in the Android project.

**Comment by Juansero29** [comment]
Did what @dernippel and @jamesmontemagno  recommended and I confirm it works :)
