### ISSUE TITLE
No Notification permission in Permission enum?

### ISSUE THREAD

**Issue by gercobrandwijk** [jamesmontemagno/PermissionsPlugin#63]
Why is there no Notification permission listed in the Permission enum?

It is because this permission is not a 'dangerous' permission on Android (so it is granted on install)? But on iOS it requires a permission request.. Currently this makes it hard for me to check if this permission is approved by the user on iOS, because for this specific permission I need to implement the permission request myself, which I don't like, because I only want to use this plugin for managing permission.. ;)

In the iOS implementation I found some commented code about the notification permission:

https://github.com/jamesmontemagno/PermissionsPlugin/blob/e818287483b6a4d408fae2eeede5ca56c4c0a59a/src/Plugin.Permissions.iOS/PermissionsImplementation.cs#L334-L357

I searched through all the issues, but was not able to find anything about the missing Notification permission.. Can anyone tell me why this is commented out? And perhaps also the best way to implement this myself?

**Comment by jamesmontemagno** [comment]
They are too complex and specific to iOS only: https://developer.xamarin.com/guides/ios/platform_features/user-notifications/deprecated/remote_notifications_in_ios/

**Comment by gercobrandwijk** [comment]
But is it not an option to only implement the permission request in this library? And not all of the configuration that is needed to get it really working.

In my opinion this library is only for requesting the permission, not for the configuration of the things that you want to do which require this permission. (e.q.: the location permission is also only asking permission and not setting anything up like GPS e.d.)

**Comment by jamesmontemagno** [comment]
This library requests permissions cross platform. https://montemagno.com/simplified-ios-android-runtime-permissions-with/

I don't have plans to add the notifications into this library as it is a bit more complex and the dev needs to handle it currently in the app delegate of iOS

Other plugins do the work of actually accessing features.

**Comment by gercobrandwijk** [comment]
Yes, I understand that his library requests permissions, but not for the notification permissions ;) So this makes this library a little bit less usefull, because it does not cover everything..

To summarize/end this issue, do you perhaps have a good example for the notification permissions where you are talking about (so the implemented that is needed in the AppDelegate), so that use who find this thread has a good working example..?

**Comment by jamesmontemagno** [comment]
Look at the docs: https://developer.xamarin.com/guides/ios/platform_features/user-notifications/
