### ISSUE TITLE
iOS 11 - No response from RequestPermissionsAsync

### ISSUE THREAD

**Issue by sorsimu** [jamesmontemagno/PermissionsPlugin#64]
## Bug Information
`_await CrossPermissions.Current.RequestPermissionsAsync(Permission.Location); `
- no response back from this line of code. Can I do something about it with this version of plugin (2.0.1), or do I have to wait till the next release when it will support iOS 11 too ? 

Version Number of Plugin: 2.0.1
Device Tested On: iOS 11
Simulator Tested On: iOS 11
Version of VS: 2017 15.3.5
Version of Xamarin: 4.7.9.45

Thanks!

**Comment by jamesmontemagno** [comment]
What permissions are in your info plist?

**Comment by sorsimu** [comment]
For locations are the following:        
```
        <key>NSLocationAlwaysUsageDescription</key>
	<string>bla bla</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>bla bla</string>
	<key>NSLocationUsageDescription</key>
	<string>bla bla</string>
```

**Comment by bprochniak** [comment]
I experience the same issue. Version 1.2.1 is working fine, on iOS 11 as well.

**Comment by jamesmontemagno** [comment]
I see what is going on. This is because you have both permissions for Always and WhenInUse in there. It has to be one or the other.

**Comment by jamesmontemagno** [comment]
This is because Apple has a typo in their docs, it is => NSLocationAlwaysAndWhenInUseUsageDescription

**Comment by KalyanXamarin** [comment]
I am still getting sam issue in 2.2.1

**Comment by Josecanalla** [comment]
Hello, I have this same problem in iOS 11.4. I tested in iOS 9.0 and iOS 10.0 and it works OK.
I have the 3.0.0.12 version of the plugin

When executing this line: CrossPermissions.Current.RequestPermissionsAsync(Permission.Location); the app not responds. 

I try a lot of combinations of permissions in Info.plist but nothing works, and always get the same result. 

When I delete all Location permissions from Info.plist the line above raises an Exception where it says that I have to add NSLocationWhenInUseUsageDescription or NSLocationAlwaysUsageDescription to Info.plist. But in my case this not works.

**Comment by jerryqburst** [comment]
update plist with following
 <key>NSLocationWhenInUseUsageDescription</key>
    <string>This app needs access location when open.</string>
    <key>NSLocationAlwaysUsageDescription</key>
    <string>This app needs access to your location.</string>
    <key>NSLocationUsageDescription</key>
    <string>This app needs access to your location.</string>
    <key>NSLocationAlwaysAndWhenInUsageDescription</key>
    <string>This app needs access to your location.</string> 
    <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
    <string>This app needs access to your location.</string>
