### ISSUE TITLE
Unexpected extra permission READ_PHONE_STATE, why?

### ISSUE THREAD

**Issue by VitalyKnyazev** [jamesmontemagno/PermissionsPlugin#65]
## Bug Information

Version Number of Plugin: 2.1.0.0
Device Tested On: Google Pixel
Simulator Tested On: API 22 to 26
Version of VS: 2017.4
Version of Xamarin: Android 8.0.0.33
Versions of other things you are using: targeting API 26, InAppBilling 1.2.3.107

### Steps to reproduce the Behavior
Using with InAppBilling 1.2.3.107

### Expected Behavior
No extra permissions required, like in 2.0.1.0

### Actual Behavior
When restoring purchase getting error message about READ_PHONE_STATE permission, purchase not restored.

**Comment by jamesmontemagno** [comment]
This would be a google issue: https://github.com/googlesamples/android-play-billing/issues/26
