### ISSUE TITLE
Upgraded to Xamarin.Forms 2.4.0.38779 Permissions not working as expected

### ISSUE THREAD

**Issue by StanleyBroo** [jamesmontemagno/PermissionsPlugin#66]
Just upgraded to stable Xamarin.Forms 2.4.0.38779 and the permissions check stopped working.
Version Number of Plugin:
Device Tested On: Galaxy s7 Edge 
Version of VS: 2017 enterprise
Version of Xamarin Forms: 2.4.0.38779

### Steps to reproduce the Behavior
await CrossPermissions.Current.CheckPermissionStatusAsync
### Expected Behavior
Get i.e. PermissionStatus.Denied , PermissionStatus.Granted
### Actual Behavior
PermissionStatus.Unknown

**Comment by StanleyBroo** [comment]
Have to investigate further. It seems like the update of Xamarin Forms to 2.4.0.38779 , wiped out my Android manifest settings??

**Comment by StanleyBroo** [comment]
Yes it did ;-)

**Comment by nbsoftware** [comment]
Hello,
What was your fix for this?
