### ISSUE TITLE
[ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentException: An item with the same key has already been added.

### ISSUE THREAD

**Issue by TheForeignMan** [jamesmontemagno/PermissionsPlugin#67]
Hi,

This is a fantastic and easy-to-use plugin, which as made my development life much easier!

I'm getting an exception thrown when I'm checking the `Location` permission:

    [ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentException: An item with the same key has already been added. Key: Location
        at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x000bb] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
        at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 

This has started to appear more often recently (using v2.1.0 of the Permissions plugin). The code I am using for checking permissions is as follows:

    var result = await Plugin.Permissions.CrossPermissions.Current.RequestPermissionsAsync(new[] { Plugin.Permissions.Abstractions.Permission.Location });
    var status = result[Plugin.Permissions.Abstractions.Permission.Location];
    if (status != Plugin.Permissions.Abstractions.PermissionStatus.Granted)
    {
        // Display warning
    }

Because I am getting this exception thrown more often now, I figured it would be something to do with the plugin itself, as this wasn't happening 2-3 weeks ago. If not, what is wrong with how I check my permissions? 

Thanks

**Comment by prashantvc** [comment]
Could you provide following information? It will help us to troubleshoot the issue

## Bug Information

Version Number of Plugin:
Device Tested On:
Simulator Tested On:
Version of VS: 
Version of Xamarin:
Versions of other things you are using:

**Comment by TheForeignMan** [comment]
More info:

Version Number of Plugin: 2.1.0
Device Tested On:   Samsung J5 (Android 6.0)
Simulator Tested On:   <none>
Version of VS:   Microsoft Visual Studio Community 2015 (Version 14.0.25425.01 Update 3)
Version of Xamarin:   Xamarin 4.7.10.33 (70936af)

**Comment by jamesmontemagno** [comment]
How are you running your code? Is there a possibility you are calling the methods multiple times?

**Comment by prashantvc** [comment]
@TheForeignMan Are you able to reproduce this on any other device/emulator?
I am not able to reproduce this on Galaxy S7E and a Pixel

Additionally, could you answer James' questions :)

**Comment by TheForeignMan** [comment]
@jamesmontemagno I guess it is possible. This permission check is called on a button press, so I can check if the button is already pressed. However, this does happen when I have the Location permission already granted.

@prashantvc I've not seen it on other devices. This has happened only a handful of times whilst I have been developing, but obviously I want to properly handle it before it gets released. As with James, I will add a button press check to avoid double calling the method, and see if the changes things. 

Just as some additional information, this exception doesn't always appear, only sometimes. As such, I have no idea when the next one will come up.

**Comment by jamesmontemagno** [comment]
I'll take a look further maybe I'm doing something weird. Good to know it is when you already have the permissions

**Comment by prashantvc** [comment]
@TheForeignMan Is that all the stacktrace you get on exception? Could you share the ADB device logs too?

**Comment by jamesmontemagno** [comment]
Oh... It only happens on Android? Weird I assume maybe multiple threads

**Comment by TheForeignMan** [comment]
@prashantvc Next time I get the exception, I will post the full stacktrace. I won't be able to get the device logs now, as it was too long ago, but I could post those too if required.

**Comment by jamesmontemagno** [comment]
try out the latest beta nuget should be good
