### ISSUE TITLE
Permissions- InvalidOperationException: transition a task to a final state

### ISSUE THREAD

**Issue by hvaughan3** [jamesmontemagno/PermissionsPlugin#7]
Received an exception report within Google Play Store site from a production user. The StackTrace is listed below.

> java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
> Caused by: java.lang.reflect.InvocationTargetException
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
> 	... 1 more
> Caused by: android.runtime.JavaProxyThrowable: System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
>   at System.Threading.Tasks.TaskCompletionSource`1[TResult].SetResult (System.Threading.Tasks.TResult result) <0x9770c2e8 + 0x0004c> in <filename unknown>:0 
>   at Plugin.Permissions.PermissionsImplementation.OnRequestPermissionsResult (Int32 requestCode, System.String[] permissions, Android.Content.PM.Permission[] grantResults) <0x9770c000 + 0x0020b> in <filename unknown>:0 
>   at APP.Droid.MainActivity.OnRequestPermissionsResult (Int32 requestCode, System.String[] permissions, Android.Content.PM.Permission[] grantResults) <0x98023c80 + 0x00033> in <filename unknown>:0 
>   at Android.App.Activity.n_OnRequestPermissionsResult_IarrayLjava_lang_String_arrayI (IntPtr jnienv, IntPtr native__this, Int32 requestCode, IntPtr native_permissions, IntPtr native_grantResults) <0x980239b8 + 0x0011b> in <filename unknown>:0 
>   at (wrapper dynamic-method) System.Object:01b25bb4-ee19-4a08-9b1e-0f10bc1cbad2 (intptr,intptr,int,intptr,intptr)
> 	at md53544c7d34300ea24a1c2b39d6d0f2051.MainActivity.n_onRequestPermissionsResult(Native Method)
> 	at md53544c7d34300ea24a1c2b39d6d0f2051.MainActivity.onRequestPermissionsResult(MainActivity.java:56)
> 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7263)
> 	at android.app.Activity.dispatchActivityResult(Activity.java:7141)
> 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4916)
> 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4963)
> 	at android.app.ActivityThread.access$1600(ActivityThread.java:221)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1848)
> 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 	at android.os.Looper.loop(Looper.java:158)
> 	at android.app.ActivityThread.main(ActivityThread.java:7224)
> 	... 3 more

## Bug 

Version Number of Plugin: 1.1.7
Device Thrown On: Samsung Galaxy S5 - Android 6.0

### Expected Behavior
An exception is not thrown.

### Actual Behavior
An exception is thrown.

### Steps to reproduce the Behavior
Unfortunately I am not able to recreate the issue because I am not sure what caused it and do not know who the user is that submitted the exception. I am wondering if this could be caused by the user double-tapping a control or something like that which would cause `OnRequestPermissionsResult()` to run multiple times, which would make the `TaskCompletionSource<Dictionary<Plugin.Permissions.Abstractions.Permission, PermissionStatus>>` throw the exception.

**Comment by jamesmontemagno** [comment]
Most likely this could be caused if you called permission requests on different threads multiple times in a row without awaiting on them to return.

**Comment by hvaughan3** [comment]
Will have to double-check everything, thank you very much for your help!

**Comment by hvaughan3** [comment]
Just to follow up here, for anyone else hitting this, I found the place where we were requesting permissions using `Task.Run()` without `await`. That alone did not cause an issue but in certain cases permissions were asked for again soon after that code ran, which cause the issues. Thanks again James!

**Comment by hvaughan3** [comment]
Sorry to drag this one up from the grave but I found another cause for this error which happens when calling the permissions code a second time before allowing the first permissions call to return. So I was calling the permissions check on line 5 for example and then later down on line 25 for example I was calling it again but the user had not finished answering the first request.
