### ISSUE TITLE
Crashing on camera request in android 7.0 htc one 

### ISSUE THREAD

**Issue by pritasam** [jamesmontemagno/PermissionsPlugin#70]
Got a SIGSEGV while executing native code. This usually indicates
 a fatal error in the mono runtime or one of the native libraries 
used by your application.

**Comment by jamesmontemagno** [comment]
Would need more information as can't reproduce at all, and your code snippet.

**Comment by SerhatSelim** [comment]
I have same issue @jamesmontemagno  please proivde a solution.

**Comment by jamesmontemagno** [comment]
What version, code sample? What are you compiling against.. Any information would help obviously.

**Comment by jamesmontemagno** [comment]
Just tried the sample and works great. Make sure to follow the documentation.
