### ISSUE TITLE
UWP Check Permission Async for Photos and Camera just return true

### ISSUE THREAD

**Issue by JKennedy24** [jamesmontemagno/PermissionsPlugin#72]
using the Check Permissions Async on UWP returns Granted, even if it isnt.

Checking the code UWP Permissions plugin doesnt look complete for Check Permissions Async:

https://github.com/jamesmontemagno/PermissionsPlugin/blob/master/src/Plugin.Permissions.UWP/PermissionsImplementation.cs#L39

**Comment by jamesmontemagno** [comment]
It is not and can't be because the APIs dont' exist :(

**Comment by JKennedy24** [comment]
@jamesmontemagno wow thats crazy! Thanks for letting me know
