### ISSUE TITLE
iOS does not return from RequestPermissionsAsync

### ISSUE THREAD

**Issue by devology-rob** [jamesmontemagno/PermissionsPlugin#74]
## Bug Information

Version Number of Plugin: 2.1.0
Device Tested On: iPhone 6 Plus 11.1.2
Simulator Tested On: N/A
Version of VS:  Mac 7.2.2 (build 11)
Version of Xamarin: Xamarin.iOS Version: 11.3.0.47 (Visual Studio Community) / Xamarin.Forms 2.3.4.247
Versions of other things you are using:
Version: 3.8.1.0 (Visual Studio Community)
Mac OS X 10.13.1

### Steps to reproduce the Behavior
I've copy and pasted the sample code from https://github.com/jamesmontemagno/PermissionsPlugin but replaced the geo locator plugin to invoke my own geo code.

### Expected Behavior
I expect the RequestPermissionsAsync to return a result, but it doesn't and it also doesn't cause an exception.

### Actual Behavior
The call to RequestPermissionsAsync never returns

### Additional information

I have added the appropriate info.plist permissions for Location, plus added the permission for the Calendar (any news on not needing to include this BTW?).

### Code snippet
```
        private async Task StartGps()
        {
            Logger.Log(this, "StartGps invoked");

            var gpsAccuracy = ActiveLoneWorkingSession.ActiveLoneWorkingSessionData.Strategy.GpsAccuracy;
            var gpsFreqSecs = ActiveLoneWorkingSession.ActiveLoneWorkingSessionData.Strategy.GpsFreqSecs;

            try
            {
                var status = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Location);
                if (status != PermissionStatus.Granted)
                {
                    if (await CrossPermissions.Current.ShouldShowRequestPermissionRationaleAsync(Permission.Location))
                    {
                        this.PlatformDifferences.DisplayMessage("Need location", "Gunna need that location");
                    }

                    var results = await CrossPermissions.Current.RequestPermissionsAsync(Permission.Location);
                    //Best practice to always check that the key exists
                    if (results.ContainsKey(Permission.Location))
                        status = results[Permission.Location];
                }

                if (status == PermissionStatus.Granted)
                {
                    PlatformDifferences.StartGpsTracking(gpsAccuracy, gpsFreqSecs);
                    //var results = await CrossGeolocator.Current.GetPositionAsync(10000);
                    //LabelGeolocation.Text = "Lat: " + results.Latitude + " Long: " + results.Longitude;
                }
                else if (status != PermissionStatus.Unknown)
                {
                    this.PlatformDifferences.DisplayMessage("Location Denied", "The session will still run, but the location details will not be captured.");
                }
            }
            catch (Exception ex)
            {
                this.PlatformDifferences.DisplayMessage("Location Error", "There was an unexpected problem with GPS/Location services. Please contact MyTeamSafe support.");
            }

            Logger.Log(this, "StartGps done");
        }

```
### Screenshots
Plist file with permissions requested.
![screen_shot_2017-12-04_at_13_21_36](https://user-images.githubusercontent.com/18516600/33554846-2fe90ccc-d8f6-11e7-8638-a7806bbdc00d.png)

**Comment by devology-rob** [comment]
I've now tested on **Android** and I also have an issue in an awaiting a method there too, but much earlier, in this initial line..

`
var status = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Location);
`

The thread it's invoked on is the UI thread, I presume that doesn't cause an issue.

**Comment by jamesmontemagno** [comment]
Have your tried the sample code? I haven't had any issues with this.

**Comment by devology-rob** [comment]
Thanks James, yes, I've now run your sample on an Android device with no problem.  Interestingly the project doesn't enable me to run on my iOS device - it enumerates all of the simulators but not my phsyical device, yet if I swap to my project it does offer my device.  I swap back to your project, no device listed again 🙈 I did have to remove the storyboard though to get it to run in a simulator.

I don't know why it doesn't work in my project, I'll keep comparing the differences and if I find a root cause I'll provide feedback.

**Comment by jamesmontemagno** [comment]
Did you select Debug | IPhone specifically? Will close as it is working just fine.

**Comment by devology-rob** [comment]
Hi James, I did try Android and iPhone in debug modes. Neither worked.  

I did however find what was stopping **iPhone** from working.  I had multiple location permissions requested in the manifest...

NSLocationAlwaysUsageDescription
NSLocationWhenInUseUsageDescription
NSLocationUsageDescription

Although the plugin didn't appear to return from the await, nor trigger an Exception, I did eventually notice some console output where it told me I needed the plist entry for NSLocationAlways**And**WhenInUseUsageDescription.  Doh.

I don't know whether Apple combined NSLocationAlwaysUsageDescription and NSLocationWhenInUseUsageDescription together into the single property NSLocationAlwaysAndWhenInUseUsageDescription.  If they did then maybe that was in a specific iOS update.  So for now, I've kept all of them.

I have yet to re-run Android to see if there's some sort of Console output the explains that one too.

**Comment by jamesmontemagno** [comment]
It is pretty heavily documented: https://jamesmontemagno.github.io/GeolocatorPlugin/GettingStarted.html and https://blog.xamarin.com/plugin-permission-changes-ios-11/

**Comment by devology-rob** [comment]
Ah, now that's interesting... I have only installed the permission plugin, so I've read all the documentation there (jamesmontemagno/PermissionsPlugin), it doesn't mention anything about those keys.

It does mention https://blog.xamarin.com/new-ios-10-privacy-permission-settings/ but that blog post doesn't contain those keys either, it might be worth mentioning https://blog.xamarin.com/plugin-permission-changes-ios-11/ instead or in addition to?

I already had my own code that performed the location tracking, so I didn't have the need to read that plugins documentation.  Also, if someone is starting from the Permissions plugin and then working out to the Geolocator plugin, they might take the same route as me and get stuck?

Thanks again James,
Rob.

**Comment by jamesmontemagno** [comment]
I will link to this: https://developer.xamarin.com/guides/ios/application_fundamentals/security-privacy-enhancements/
