### ISSUE TITLE
iOS Location - Requesting WhenInUse then Always returns Denied Before User Chooses

### ISSUE THREAD

**Issue by Castaneda1914** [jamesmontemagno/PermissionsPlugin#75]
## Bug Information

Version Number of Plugin: 2.1.0
Device Tested On: iPhone 7 plus, iOS 11.1
Simulator Tested On: iPhone 8, iOS 11.1
Version of VS: VS for Mac 7.3

### Steps to reproduce the Behavior

1.Request location when in use permission.
2.Obtain user answer.
3.Request location always permission.

### Expected Behavior

User answer should be obtained after each permission request.

### Actual Behavior

Can not obtain proper user answer - the result always has status: denied.

### Code snippet

```
 var locationRequestPermission = await CrossPermissions.Current.RequestPermissionsAsync(Permission.LocationWhenInUse);

 await Task.Delay(5000);

 var locationPermissionStatus = await CrossPermissions.Current.RequestPermissionsAsync(Permission.LocationAlways);
```

### Addition information
https://github.com/jamesmontemagno/PermissionsPlugin/blob/fa325af8c104a0cbc09a8dd06ff11f2dabd7d7ce/src/Plugin.Permissions.iOS/PermissionsImplementation.cs#L280

If locationManager AuthorizationChanged callback is attached first time to manager it immediately returns current status of permissions. That's why first time 
`
if (e.Status == CLAuthorizationStatus.NotDetermined)
						return;
`
works fine, but second time attached callback returns status "WhenInUse" and user choice doesn't affect anything.
Possible way to resolve this issue - initialize field locationManager once and remove it initialize in 
RequestLocationPermission method.

**Comment by viktorgt** [comment]
Same behavior on Android, the ermissions Dialog does not appear, the RequestPermissionsAsync exists always with denied.

**Comment by jamesmontemagno** [comment]
@viktorgt the Always/WhenInUse on android is the same and works fine. You probably didn't follow setup instructions to set your target version and compile version.

@Castaneda1914 I have a repro here that has the issue.

**Comment by jamesmontemagno** [comment]
So this bug literally has no resolution due to how iOS 11 informs us about changes.

Once you have When In Use everything is great.

When you ask for Always then a few things happen:

1. We get an immediate "WhenInUse" which is expected
2. The user gets a dialog to pick and choose When In Use or Always
3. If they choose Always we get another event, which is awesome, but we have already returned... so maybe you think well just ignore the first "WhenInUse", but you can't because of the next problem
4. If they choose WhenInUse no event is fired. And you are stuck in a state of never getting a callback.

**Comment by jamesmontemagno** [comment]
Additionally, caching around the existing locationmanager will mean that if you were denied and you call request again then it will lock because the authorization will not change.

**Comment by jcmanke** [comment]
What about using a timeout? If you don't get a second callback in X seconds (10, 15, 30, 60, whatever) then cancel the task.

**Comment by mackayn** [comment]
Seeing the same thing when asking again for access to the photo library

```
public async Task<Stream> PickPhotoAsync()
        {
            var photoOk = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Photos);

            if (photoOk != PermissionStatus.Denied)
            {
                // returns immediately with PermissionStatus.Denied
                var results = await CrossPermissions.Current.RequestPermissionsAsync(Permission.Photos);
                photoOk = results[Permission.Photos];
```

**Comment by mackayn** [comment]
I did try the async method out of curiosity but you get the exact same behavior.

```
 public async Task<PermissionStatus> RequestPhotoPermission()
	    {
		    PermissionStatus toReturn;
			var res = await PHPhotoLibrary.RequestAuthorizationAsync();

			switch (res)
			{
				case PHAuthorizationStatus.Authorized:
					toReturn = PermissionStatus.Granted.....
```

**Comment by jamesmontemagno** [comment]
@mackayn can you open a new bug as you are using photos and that is different.

**Comment by mackayn** [comment]
OK, willl do.

**Comment by jamesmontemagno** [comment]
Now fixed with a timeout based on order of operation and you can override the timeout too on the platform level. Did the best I could here.
