### ISSUE TITLE
CheckPermissionStatusAsync does not reflect changes made by user

### ISSUE THREAD

**Issue by chameleon67** [jamesmontemagno/PermissionsPlugin#76]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 2.1.0
Device Tested On: Google Nexus 5
Simulator Tested On: AVD_Nexus_6
Version of VS: API 23, API 25
Version of Xamarin: 1.3.2
Version of Xamarin.Android: 8.0.2.1
Versions of other things you are using: Visual Studio for Mac 7.2.2

### Steps to reproduce the Behavior
* Build the Permissions Tests sample and run on API 23 or 25
* Request permission for Camea and Storage
* Quit the app, go to Settings > Apps > Permissions Tests > Permissions
* Turn off Permissions for Camera and Storage
* Run the Permissions Tests again
* Permission.Status for Camera is Pre Results is Granted
* Permission.Status for Storage is Pre Results is Granted

### Expected Behavior
* Permission.Status for Camera is Pre Reults should be Deny so that permission can be requested again
* Permission.Status for Storage is Pre Reults ishould be Deny so that permission can be requested again

### Actual Behavior
* Permission.Status for Camera is Pre Results is Granted causing CrossMedia.Current.IsCameraAvailable to crash App
* Permission.Status for Storage is Pre Results is Granted

### Code snippet
* Permissions Tests sample

**Comment by prashantvc** [comment]
@chameleon67 I am not able to reproduce this on the Emulator running API 23/25.
The result are as expected: 
Permission.Status for Camera is Pre Reults is Deny and I get a prompt to grant permissions

Could you share the Android device/emulator's Android version?

**Comment by chameleon67** [comment]
@prashantvc 
On Android Emulator AVD_Nexus_7 ; Android Version 7.1.1, Kernal version 3.10+
On Nexus 5; Android Version 6.0.1, Kernal version 3.4.0

Both the emulator and physical device exhibit the same behaviour. If the user **changes** the permissions in Settings to Deny.  Permission.Status still results in Granted.

Some further investigation, I added an Android Dependancy Service to the project and ran the following code

`var results = PermissionChecker.CheckSelfPermission(context, Manifest.Permission.Camera);
`

and 'results' was '-2' 

According to the https://developer.android.com/reference/android/support/v4/content/PermissionChecker.html
0 => PERMISSION_GRANTED
-1 => PERMISSION_DENIED
-2 => PERMISSION_DENIED_APP_OP

Thanks for looking into this, let me know if you require further information

**Comment by jamesmontemagno** [comment]
What version of android are you targeting?

For current stable you must target 6.0+.

We use: ContextCompat.CheckSelfPermission(context, name)

**Comment by chameleon67** [comment]
Droid project is set to Automatic Target (API 25)

I did a search on Stackoverflow and found some similar problems
https://stackoverflow.com/questions/36003047/contextcompat-checkselfpermissioncontext-manifest-permission-camera-alway-ret#36008404

I tried using PermissionChecker after I read this SO question and saw "CommonWare's" suggestion at the end of the thread if the user has denied the Permission group via Settings
https://stackoverflow.com/questions/35342667/androids-contextcompat-checkselfpermission-returns-incorrect-value

**Comment by jamesmontemagno** [comment]
I'll test it out. Maybe just need to switch fully over to permission checker.

**Comment by jamesmontemagno** [comment]
Oh, this is your problem.... You have it set to "Automatic". When you do this then the TargetSDKVersion is not set in your manifest :( which really stinks. So you MUST set it manually.

That said though I believe the current beta already fixes your issue because if this is the case I fall back to PermissionChecker.
