### ISSUE TITLE
No Popup for user to Grant Permission

### ISSUE THREAD

**Issue by wizz269** [jamesmontemagno/PermissionsPlugin#79]
I am not sure if it is a bug or an error one my part.
the issue i am getting is disturbing. 
i downloaded the latest plugin to my project via NuGet, i also had the geolocator plugin on my project as well. 
i followed your code line by line. that I get is  I get the Current Status, but there is no Popup to request user to grant permission.
i turn on location manually and provide permissions via APps settings on android I get  message "GRANTED" and i can get the locations without a problem.

what i expected is for the part of granting permissions to the App would be at runtime.

**Comment by jamesmontemagno** [comment]
This probably is because your "target" version is not set to API 23 or higher. So android thinks you are targeting a very old version of android and wouldn't show the dialog.

**Comment by wizz269** [comment]
Thank you for your reply, i tried the suggestion you made.
please clear one thing for me which may be am doing wrong. 
I want to give permissions to Location. but also in the future i would like to do the same for other permissions.

**Comment by wizz269** [comment]
Thank you for your reply, i tried the suggestion you made.
please clear one thing for me which may be am doing wrong.
I want to give permissions to Location. but also in the future i would like to do the same for other permissions.
i downloaded the location plugin and the permissions plugin
the code I used is this  .copied from you

try
{
    var status = await CrossPermissions.Current.CheckPermissionStatus(Permission.Location);
    if (status != PermissionStatus.Granted)
    {
        if(await CrossPermissions.Current.ShouldShowRequestPermissionRationale(Permission.Location))
        {
            await DisplayAlert("Need location", "Gunna need that location", "OK");
        }

        var results = await CrossPermissions.Current.RequestPermissions(new[] {Permission.Location});
        status = results[Permission.Location];
    }

    if (status == PermissionStatus.Granted)
    {
        var results = await CrossGeolocator.Current.GetPositionAsync(10000);
        LabelGeolocation.Text = "Lat: " + results.Latitude + " Long: " + results.Longitude;
    }
    else if(status != PermissionStatus.Unknown)
    {
        await DisplayAlert("Location Denied", "Can not continue, try again.", "OK");
    }
}
catch (Exception ex)
{

    LabelGeolocation.Text = "Error: " + ex;
}


am i missing something , ?  
its no an issue to report so if it fits please reply through mwaimu1986@hotmail.com

**Comment by jamesmontemagno** [comment]
Looks.correct

**Comment by wizz269** [comment]
UPDATE : I managed to get it to work, on Emulator and device, Apparently when i installed the plugins the MainApplication.cs , Utils.cs  were not being added to my project, so i took the sample you provided and added them to the project.  also added the required line on MainActivity.cs  as you instructed 

Plugin.CurrentActivity.CrossCurrentActivity.Current.Activity = this;   

I did something extra added references using dlls as well for the plugins . at this point its working perfect.
just wondering if there is a way to manually revoke permission.

thanks a lot James
