### ISSUE TITLE
App crash in Android when call RequestPermissionsAsync

### ISSUE THREAD

**Issue by Josecanalla** [jamesmontemagno/PermissionsPlugin#80]
## Bug Information

Version Number of Plugin: 2.2.1
Device Tested On: Motorola Moto G4 plus
Simulator Tested On: N/A
Version of VS: VS Community 2017 v15.4.0
Version of Xamarin: 2.5.0.1222203
Versions of other things you are using: Plugin.CurrentActivity 1.0.1

### Steps to reproduce the Behavior

1. Install app and grant Location permission. 
2. Go to Preferences and disable location permission.
3. Open app, and when execute this code:

```
var status = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Location);
            if (status != PermissionStatus.Granted)
            {
                if (await CrossPermissions.Current.ShouldShowRequestPermissionRationaleAsync(Permission.Location))
                {
                    await DisplayAlert("Need location", "Gunna need that location", "OK");
                }

                var results = await CrossPermissions.Current.RequestPermissionsAsync(Permission.Location);
                //Best practice to always check that the key exists
                if (results.ContainsKey(Permission.Location))
                    status = results[Permission.Location];
            }

```
app crash in "RequestPermissionAsync" line.

I get this crash if I run the app in "Release" mode. If I run it in Debug mode, I always get permission is "Granted" so the code where the app crashes is not executed.

Solution: my error is that not setting compiling version API 25.

**Comment by ksu11** [comment]
I have the same problem with API 29, any updates?
