### ISSUE TITLE
Question regarding the logic for iOS location permission implementation.

### ISSUE THREAD

**Issue by jinkhera** [jamesmontemagno/PermissionsPlugin#81]
Hi

This relates to the latest source-code and in particular this file here ->https://github.com/jamesmontemagno/PermissionsPlugin/blob/master/src/Plugin.Permissions.iOS/PermissionsImplementation.cs.

On line the 342 of the switch statement the code falls through to the case "AuthorizedWhenInUse" and it returns Denied. Could you explain why this is so?

Thanks

Jin Khera

**Comment by jamesmontemagno** [comment]
If you are requesting Always and it only Returns WhenInUse then you don't have Always, so it is denied technically. This permission change from apple is a big pain. See: https://github.com/jamesmontemagno/PermissionsPlugin/issues/75

**Comment by jinkhera** [comment]
I did see that issue #75 which prompted the question. I will have a look at a workaround tomorrow as we have just reverted to an older version of the plugin.

**Comment by jamesmontemagno** [comment]
What permission are you requesting? And what is in your info.plist?

**Comment by jinkhera** [comment]
I bit of background first. This is a Xamarin Forms app using the GeoLocator and Permissions plugin. The permission being requested is WhenInUse which then causes the crash. The info.plist has the required keys and values, in this case the NSLocationWhenInUseUsageDescription and NSLocationAlwaysAndWhenInUseUsageDescription. I am more than happy to assist in helping to resolve this issue if that is of course possible.

**Comment by jamesmontemagno** [comment]
If you only need WhenInUse this should be the only item in your info.plist
additionaly it will crash because you are missing the NSLocationAlwaysUsageDescription... you need either WhenInUse or all 3.
