### ISSUE TITLE
Plugin returns incorrect permission results when target Sdk is 8.0 and minimum Sdk is 5.0.

### ISSUE THREAD

**Issue by daymonc** [jamesmontemagno/PermissionsPlugin#82]
Version Number of Plugin: 2.2.1
Device Tested On: Sony Xperia Compact Z3 Api 6.0
Simulator Tested On: Api 7.1
Version of VS: Community 2017 15.4.0
Version of Xamarin: 4.7.10.22
Versions of other things you are using: Xamarin.AndroidSdk 8.0.0.33

### Steps to reproduce the Behavior
Compile against Android Api 8.0
Set Minimum Sdk to 5.0
Request Permission on device.

### Expected Behavior
Permission should return the correct user choice.

### Actual Behavior
The response is Granted when the permission is denided.
OnRequestPermissionResult doesn't fire when the permission is accepted. 

The plugin worked as expected before I upgraded the Sdk from 7.1 to 8.0, hence I'm confident there is no inherent problem with how I'm using the plugin.

The plugin also works correctly when I change the minimum sdk from 5.0 to 6.0+, with no other additional changes.

**Comment by jamesmontemagno** [comment]
can you send me a screenshot of what your target/min/compile looks like.

**Comment by jamesmontemagno** [comment]
This most likely means you are setting the Target to "Use Compile" which doesn't actually set it in the manifest: https://github.com/xamarin/xamarin-android/issues/1163

**Comment by daymonc** [comment]
Thank you for the prompt reply. You are absolutely right, this fixed the issue. I actually noticed this behavior in the manifest, but I thought the fact that no target is set means use the highest by default, good to know it's actually a bug.
