### ISSUE TITLE
Anyway to target older version of Android

### ISSUE THREAD

**Issue by Robbie188** [jamesmontemagno/PermissionsPlugin#83]
More a question than an issue.

I'm pretty sure the answer is no but is there anyway to support older versions of Android than API level 25?  It is a really hard sell to tell my boss that we can only support 8% of Android Users :-)

**Comment by jamesmontemagno** [comment]
You are confusing Target with Minimum. You can set Minimum to whatever you would like.

**Comment by Robbie188** [comment]
Apologies, you are correct I did indeed miss-interpret that when reading your release notes. Thanks for getting back to me.
