### ISSUE TITLE
TaskCanceledException

### ISSUE THREAD

**Issue by duzenko** [jamesmontemagno/PermissionsPlugin#85]
Stack trace: https://gist.github.com/duzenko/ef6fbb3ebab9e6f9705215ce3c7de65b

## Bug Information

Version Number of Plugin: 2.2.1
Device Tested On: Samsung Tab S2
Version of VS: 2017 15.6
Version of Xamarin: 4.9 749

### Steps to reproduce the Behavior
Run this code on a ContentPage's OnAppearing
It only crashes on the first run after install on device.

### Expected Behavior
It await's for user decisions

### Actual Behavior
Crash to home screen

### Code snippet

```
        internal static async Task CheckPermissions() {
            if( Device.RuntimePlatform != Device.Android )
                return;
            LocationAllowed = (await CrossPermissions.Current.CheckPermissionStatusAsync( Permission.Location )) == PermissionStatus.Granted;
            if( !LocationAllowed ) {
                var results = await CrossPermissions.Current.RequestPermissionsAsync( Permission.Location );
                if(results.TryGetValue( Permission.Location, out var status ) )
                    LocationAllowed = status == PermissionStatus.Granted;
            }
        }
```

I followed instructions from the readme:

```
        protected override void OnCreate( Bundle bundle ) {
...
                CrossCurrentActivity.Current.Activity = this;


        public override void OnRequestPermissionsResult( int requestCode, string[] permissions, [GeneratedEnum] Permission[] grantResults ) {
            base.OnRequestPermissionsResult( requestCode, permissions, grantResults );
            PermissionsImplementation.Current.OnRequestPermissionsResult( requestCode, permissions, grantResults );
        }

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:installLocation="preferExternal" package="com.smartwebs.xp" android:versionCode="206" android:versionName="1.0">
...
	<uses-permission android:name="android.permission.ACCESS_MOCK_LOCATION" />
	<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
	<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
</manifest>
```

**Comment by las3r** [comment]
I have the exact same issue and stacktrace (with camera permission), when the permission is invoken (user takes a picture) the app crashes to the home screen.

**Comment by PaulVrugt** [comment]
this happens when you call RequestPermissionsAsync multiple times in quick succession. If you call the RequestPermissionsAsync method for the second time before the first one finishes, the taskcompletionsource used within the method is simply canceled. This causes the await to crash because of a canceled task.

I was able to reproduce it consequently in one of our apps. I worked around it by wrapping the permission checker in a method within the app, and use a SemaphoreSlim to avoid multiple requests to be done at the same time. It might be a good a idea to implement this in the plugin? Does @jamesmontemagno have any thoughts about this?

**Comment by Devvox93** [comment]
@PaulVrugt James apparently does not want to fix this issue. I've made 2 issues about this and they were both closed, not due to lack of me trying to explain the issue. Maybe you confirming the issue and mentioning your solution changes his mind. He could at least add your description to a "known issues" list.

**Comment by markdou812** [comment]
I am calling RequestPermissionsAsync one time with an array of permissions. I see the prompt to grant each permission and once that finishes the await never returns. If I call RequestPermissionsAsync again then I get the TaskCanceledException.

**Comment by rohitvipin** [comment]
I can recreate this still.

**Comment by josco007** [comment]
> this happens when you call RequestPermissionsAsync multiple times in quick succession. If you call the RequestPermissionsAsync method for the second time before the first one finishes, the taskcompletionsource used within the method is simply canceled. This causes the await to crash because of a canceled task.
> 
> I was able to reproduce it consequently in one of our apps. I worked around it by wrapping the permission checker in a method within the app, and use a SemaphoreSlim to avoid multiple requests to be done at the same time. It might be a good a idea to implement this in the plugin? Does @jamesmontemagno have any thoughts about this?


I have created a manager to be sure each permission is called once at time:


    public class DevicePermissionManager
    {


        private class RequestPermissionQueueItem
        {
            public Permission Permission { get; set; }
            public Action<Dictionary<Permission, PermissionStatus>> OnPermissionResultCallBack { get; set; }
        }

        public static DevicePermissionManager Instance = new DevicePermissionManager();

        private List<RequestPermissionQueueItem> permissionsToBeRequested = new List<RequestPermissionQueueItem>();
        private bool isBusy;
        private int currentPermissionRequest = -1;

        private DevicePermissionManager()
        {

        }

        private void ExecuteNextPendingPermissionRequests()
        {
            RequestPermissionAsync(permissionsToBeRequested[currentPermissionRequest].Permission, 
                permissionsToBeRequested[currentPermissionRequest].OnPermissionResultCallBack);
            
        }

        public async void RequestPermissionAsync(Permission permission, Action<Dictionary<Permission, PermissionStatus>> onPermissionResult)
        {

            var status = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Location);
            if (status == PermissionStatus.Granted)
            {
                Dictionary<Permission, PermissionStatus> result = new Dictionary<Permission, PermissionStatus>
                {
                    { permission, PermissionStatus.Granted }
                };
                onPermissionResult?.Invoke(result);
                return;
            }

           if (isBusy)
            {
                RequestPermissionQueueItem requestPermissionQueueItem = new RequestPermissionQueueItem {
                    Permission = permission,
                    OnPermissionResultCallBack = onPermissionResult
                };
                permissionsToBeRequested.Add(requestPermissionQueueItem);
                return;
            }

            isBusy = true;
            Dictionary<Permission, PermissionStatus> results = await CrossPermissions.Current.RequestPermissionsAsync(Permission.Location);
            onPermissionResult?.Invoke(results);
            isBusy = false;

            currentPermissionRequest++;
            if (currentPermissionRequest < permissionsToBeRequested.Count)
            {
                
                ExecuteNextPendingPermissionRequests();
                
            }
            else
            {
                currentPermissionRequest = -1;
                permissionsToBeRequested = new List<RequestPermissionQueueItem>();
            }
        }


    }


Usage:

      public static async void SetMyLocationEnabledAsync(Map map, bool enabled)
        {

            if (enabled)
            {
                var status = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Location);

                
                if (status != PermissionStatus.Granted)
                {


                    DevicePermissionManager.Instance.RequestPermissionAsync(Permission.Location, (result) =>
                    {
                        //Best practice to always check that the key exists
                        if (result.ContainsKey(Permission.Location))
                            status = result[Permission.Location];

                        if (status != PermissionStatus.Granted)
                        {
                            Debug.WriteLine("Could not enabled my location cause permission is desabled");
                            return;
                        }
                        else
                        {
                            map.MyLocationEnabled = enabled;
                        }

                    });

                    /*var results = await CrossPermissions.Current.RequestPermissionsAsync(Permission.Location);
                    //Best practice to always check that the key exists
                    if (results.ContainsKey(Permission.Location))
                        status = results[Permission.Location];

                    if (status != PermissionStatus.Granted)
                    {
                        Debug.WriteLine("Could not enabled my location cause permission is desabled");
                        return;
                    }
                    */


                    return;
                }
            }

            map.MyLocationEnabled = enabled;
        }

**Comment by JBamford1** [comment]
Hi, I would like to report that I'm getting this issue too.
I found a workaround that doesn't require a Manager, simply check if you have the permissions first, then request all the permissions in one request.

    var permissionsToRequest = new List<Plugin.Permissions.Abstractions.Permission>();
    var locationStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Plugin.Permissions.Abstractions.Permission.Location);
    if (locationStatus != PermissionStatus.Granted)
    {
        permissionsToRequest.Add(Plugin.Permissions.Abstractions.Permission.Location);
    }

    var storageStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Plugin.Permissions.Abstractions.Permission.Storage);
    if (storageStatus != PermissionStatus.Granted)
    {
        permissionsToRequest.Add(Plugin.Permissions.Abstractions.Permission.Storage);
    }
    var res = await CrossPermissions.Current.RequestPermissionsAsync(permissionsToRequest.ToArray());

**Comment by Srikanth540-L** [comment]
@PaulVrugt Can you please share the code snippet which you have implemeted using SemaphoreSlim to avoid the crash, we tried with same approach but we ended up on other crash caused by SemaphoreFullException, It would be a great help if you share the code snippet.
Thanks !!

**Comment by PaulVrugt** [comment]
@Srikanth540-L 

See below for our method to check permissions

        private static SemaphoreSlim _permissionSemphore = new SemaphoreSlim(1);

        async public static Task<Plugin.Permissions.Abstractions.PermissionStatus> CheckPermissions(Plugin.Permissions.Abstractions.Permission[] permissions,
                                                                                                    bool requestPermissionsIfNotGranted = true)
        {
            await _permissionSemphore.WaitAsync();

            try
            {
                    var permissionsToRequest = new List<Plugin.Permissions.Abstractions.Permission>();
                    foreach (var permission in permissions)
                    {
                        var result = await Plugin.Permissions.CrossPermissions.Current.CheckPermissionStatusAsync(permission);
                        if (result != Plugin.Permissions.Abstractions.PermissionStatus.Granted)
                        {
                            if (requestPermissionsIfNotGranted)
                                permissionsToRequest.Add(permission);
                            else
                                return Plugin.Permissions.Abstractions.PermissionStatus.Denied;
                        }
                    }

                    if (permissionsToRequest.Count > 0)
                    {
                        var results = await Plugin.Permissions.CrossPermissions.Current.RequestPermissionsAsync(permissionsToRequest.ToArray());

                        foreach (var permission in permissionsToRequest)
                        {
                            if (results.ContainsKey(permission))
                            {
                                if (results[permission] != Plugin.Permissions.Abstractions.PermissionStatus.Granted)
                                    return results[permission];
                            }
                        }
                    }

                    return Plugin.Permissions.Abstractions.PermissionStatus.Granted;
            }
            finally
            {
                _permissionSemphore.Release();
            }
        }

**Comment by Srikanth540-L** [comment]
@PaulVrugt  Thanks alot for quick response

**Comment by chrisfoulds** [comment]
Thanks guys, I just copied your solution
