### ISSUE TITLE
Permission Plugin always retuning as 'Granted' on older devices

### ISSUE THREAD

**Issue by damion-daly** [jamesmontemagno/PermissionsPlugin#86]
Hi James,
I've just installed your  permissions plugin (excellent stuff!)  and overridden the OnRequestPermissionsResult in my MainActivity as you suggest, but my call to check location permissions always returns granted.
This is debugging on an older physical device with Android 5.1 - API 22.
I've still to run it on 6.0 and above, but is there anything in particular I have to do in order to run on older devices?

cheers

(The code is pretty much as in your example:)

```
var status = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Location);
 if (status != PermissionStatus.Granted)
```

**Comment by jamesmontemagno** [comment]
If you run pre-6.0 they are always granted because you have them in your manifest.

**Comment by damion-daly** [comment]
Ah of course, thanks for answering
