### ISSUE TITLE
CheckPermissionStatusAsync method returning granted if select deny from permission popup.

### ISSUE THREAD

**Issue by shrutigoyal123** [jamesmontemagno/PermissionsPlugin#87]
Hello jamesmontemagno,

I'm using plugin.permission. In my project CheckPermissionStatusAsync method is giving denied if I have set denied from app setting. But in CheckPermissionStatusAsync method , I have selected deny option from popup then newstatus is giving granted which is not expected behaviour .
Expected Behaviour- It should give denied status. Please Help

**Comment by jamesmontemagno** [comment]
Please share sample code

**Comment by shrutigoyal123** [comment]
ViewModel Side-

var status = PermissionStatus.Unknown;
            status = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Camera);
            if (status != PermissionStatus.Granted)
            {
                status = await Utils.CheckPermissions(Permission.Camera);
            }
            if (status == PermissionStatus.Granted)
            {
                var status1 = PermissionStatus.Unknown;
                status1 = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Storage);
                if (status1 != PermissionStatus.Granted)
                {
                    status1 = await Utils.CheckPermissions(Permission.Storage);
                }
                if (status1 == PermissionStatus.Granted)
                {
                    var photo = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions() { });
                    //var photo = await CrossMedia.Current.PickPhotoAsync();
}

In Utils class-

public static async Task<PermissionStatus> CheckPermissions(Permission permission)
        {
            var permissionStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(permission);
            bool request = false;
            if (permissionStatus == PermissionStatus.Denied)
            {
                if (Device.RuntimePlatform == Device.iOS)
                {

                    var title = $"{permission} Permission";
                    var question = $"To use this feature the {permission} permission is required. Please go into Settings and turn on {permission} for the app.";
                    var positive = "Settings";
                    var negative = "Maybe Later";
                    var task = Application.Current?.MainPage?.DisplayAlert(title, question, positive, negative);
                    if (task == null)
                        return permissionStatus;

                    var result = await task;
                    if (result)
                    {
                        CrossPermissions.Current.OpenAppSettings();
                    }

                    return permissionStatus;
                }

                request = true;

            }

            if (request || permissionStatus != PermissionStatus.Granted)
            {
                var newStatus = await CrossPermissions.Current.RequestPermissionsAsync(permission);

                if (!newStatus.ContainsKey(permission))
                {
                    return permissionStatus;
                }

                permissionStatus = newStatus[permission];

                if (newStatus[permission] != PermissionStatus.Granted)
                {
                    permissionStatus = newStatus[permission];
                    var title = $"{permission} Permission";
                    var question = $"To use the feature the {permission} permission is required.";
                    var positive = "Settings";
                    var negative = "Maybe Later";
                    var task = Application.Current?.MainPage?.DisplayAlert(title, question, positive, negative);
                    if (task == null)
                        return permissionStatus;

                    var result = await task;
                    if (result)
                    {
                        CrossPermissions.Current.OpenAppSettings();
                    }
                    return permissionStatus;
                }
            }

            return permissionStatus;
        }
    }


In Manifest-

<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="2" android:versionName="2.0" package="com.company.project1">
	<uses-sdk android:minSdkVersion="15" />
	<uses-permission android:name="android.permission.CAMERA" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
	<application android:label="project" android:icon="@drawable/icon">
		<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
		<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver" android:exported="true" android:permission="com.google.android.c2dm.permission.SEND">
			<intent-filter>
				<action android:name="com.google.android.c2dm.intent.RECEIVE" />
				<action android:name="com.google.android.c2dm.intent.REGISTRATION" />
				<category android:name="${applicationId}" />
			</intent-filter>
		</receiver>
		<provider android:name="android.support.v4.content.FileProvider" android:authorities="com.company.project1.fileprovider" android:exported="false" android:grantUriPermissions="true">
			<meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/file_paths">
			</meta-data>
		</provider>
	</application>
</manifest>

I already created resource xml file or mainapplication.cs class as givien in readme.txt
I am testing on moto g3 

Steps to get issue-

1)build and run app
2)go in app from setting and turn off camera and storage permission
3)try to open camera
4)permission popup occurs and select deny from the popup
5) check new status value in debugger it is giving granted.

I'm using latest version of your library 2.2.1
