### ISSUE TITLE
Permission does not ask if "Turn off" from "Settings->Privacy Policy" on iOS / iPhone

### ISSUE THREAD

**Issue by softsan** [jamesmontemagno/PermissionsPlugin#88]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:2.2.1
Device Tested On: iPhone 6s / iOS 11
Simulator Tested On: iPhone 8/8Plus / iOS 11
Version of VS: 7.4.2 (build 12)
Version of Xamarin: Xamarin.Forms version 2.5.1.444934
Versions of other things you are using:

### Steps to reproduce the Behavior
After first time installation, it ask for each Permission  Camera, Contacts and microphone permission. But after that, if we remove permission(turn off) from Settings -> Privacy Policy -> app Name" on iPhone, it doesn't ask it again.  
### Expected Behavior
First install, it ask the permission, but after turning off  the permission from "Settings -> Privacy Policy -> app Name" on iPhone, it doesn't ask it again. It should ask the same.
### Actual Behavior
First install, it ask the permission, but after i remove the permission from "Settings -> Privacy Policy -> app Name" on iPhone, it doesn't ask it again.  
### Code snippet
```
public static class PermissionService
    {
        public static Task<bool> CheckAll(bool ask)
        {
            return Check(ask,
                Permission.Calendar, 
                Permission.Camera,
                Permission.Microphone,
                Permission.Contacts
                );
        }

        public static async Task<bool> Check(bool ask, params Permission[] permission)
        {
            bool state = true;

            for (int i = 0; i < permission.Length; i++)
            {
                var val = await Check(permission[i], ask);

                state = state && val;
            }

            return state;
        }

        public static async Task<bool> Check(Permission permission, bool ask = true)
        {
            try
            {
                var val = await CrossPermissions.Current.CheckPermissionStatusAsync(permission);

                if (val != PermissionStatus.Granted && ask)
                {
                    await CrossPermissions.Current.RequestPermissionsAsync(permission);
                    val = await CrossPermissions.Current.CheckPermissionStatusAsync(permission);
                }

                return val == PermissionStatus.Granted;
            }
            catch (Exception ex)
            {
                 Console.WriteLine("Error:" + ex.Message);
            }
            return false;
        }
    }
```
XAML:
```
<StackLayout Padding="20" VerticalOptions="FillAndExpand">
    
    <Button Text="Click for permission!" Clicked="OnPermission" />
        
    </StackLayout>
```
Xaml.cs
```
async void OnPermission(object sender, System.EventArgs e)
        {
            await PermissionService.CheckAll(true);
        }
```

### Screenshots
<img width="646" alt="screen shot 2018-04-05 at 11 36 10 pm" src="https://user-images.githubusercontent.com/7391319/38383461-2ff97ee2-392a-11e8-9c20-eac3d160371d.png">

**Comment by jamesmontemagno** [comment]
iOS only ever asks once. EVER that is all you get. Then you have to direct them to settings page for your app.

**Comment by caseyniemann** [comment]
@jamesmontemagno are you aware of any other tools that will force a user to be prompted for permissions with each update of the app.

**Comment by jamesmontemagno** [comment]
On iOS it isn't possible, only android, it is how the OS works.
