### ISSUE TITLE
RequestPermissionAsync does not return and just gets stuck regardless if the user allows or denies the permission

### ISSUE THREAD

**Issue by KaizerT** [jamesmontemagno/PermissionsPlugin#89]
## Bug Information

Version Number of Plugin: 2.2.1.0
Device Tested On: HTC One M9
Simulator Tested On: None
Version of VS:  2015
Version of Xamarin: 2.0.0.0
Versions of other things you are using: None

### Steps to reproduce the Behavior
Request permissions during boot up of app. User selects either allow or deny.
### Expected Behavior
Code continues depending on returned value of requestpermimssionasync
### Actual Behavior
RequestPermissionAsync never returns. No exceptions are thrown so Not sure what happened
### Code snippet
 `try
            {
                var status = await CrossPermissions.Current.CheckPermissionStatusAsync(Plugin.Permissions.Abstractions.Permission.Location);
                if (status != Plugin.Permissions.Abstractions.PermissionStatus.Granted)
                {
                    if (await CrossPermissions.Current.ShouldShowRequestPermissionRationaleAsync(Plugin.Permissions.Abstractions.Permission.Location))
                    {
                        await DisplayAlert("Need location", "Location is needed for the application", "OK");
                    }
                    var results = await CrossPermissions.Current.RequestPermissionsAsync(Plugin.Permissions.Abstractions.Permission.Location);
                    //Best practice to always check that the key exists
                    if (results.ContainsKey(Plugin.Permissions.Abstractions.Permission.Location))
                    {
                        status = results[Plugin.Permissions.Abstractions.Permission.Location];
                    }
                }
            }
            catch (Exception ex)
            {
                ex = ExceptionHelper.mGetInnermostException(ex);
                Device.BeginInvokeOnMainThread(new Action(() =>
                {
                    DisplayAlert("Error",ex.Message,"Ok");
                }));
            }`
### Screenshots
Just a blank screen

**Comment by jamesmontemagno** [comment]
https://github.com/jamesmontemagno/PermissionsPlugin#android-specific-in-your-baseactivity-or-mainactivity-for-xamarinforms-add-this-code

**Comment by KaizerT** [comment]
James, 

I have that set up you linked and still was getting the issue. I would like to reopen this issue since it was closed without confirmation

**Comment by TomBruyneel** [comment]
Experiencing the same issue, the call just never returns. I did go through the currentactivity setup

**Comment by mnesser** [comment]
It kinda works for me now.. Seemingly my issue where thread based.
In my OnStart/OnCreate I tried to execute the check and request the needed permissions in a thread locking operation, this did cause the reported issue. 
I had to split the functionality into a pure permissions check in my OnStart. And if the needed permissions where not available display a dialog notifying the user and execute the                 CrossPermissions on user dialog close event.

**Comment by tekr** [comment]
5 years later I've been having the same symptoms using a Samsung Galaxy S9+ on latest Xamarin. Thanks to @mnesser 's tip above it's now working after after moving the permissions check/grant from being done directly in MainActivity.OnStart() to instead doing RunOnUiThread(async () => { <permissions check/grant> }); inside OnStart().

Not clear why this behaves so differently, but it does.
