### ISSUE TITLE
iOS- Storage permission is always giving granted but in settings permission is never selected

### ISSUE THREAD

**Issue by shrutigoyal123** [jamesmontemagno/PermissionsPlugin#90]
## Bug Information

Version Number of Plugin:2.2.1
Device Tested On:iPhone 6s+, iOS 11
Versions of other things you are using:

### Steps to reproduce the Behavior
I am implementing below code but it never opens photo permission popup and always giving granted and I am also able to pick photo from gallery.

### Expected Behavior
It should open popup and after clicking 'allow' in popup, this should be allowed and then I able to pick photo from gallery.

### Actual Behavior
No permission popup opening

### Code snippet
ViewModel-
storageStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Storage);
                        if (storageStatus != PermissionStatus.Granted)
                        {
                            storageStatus = await Utils.CheckPermissions(Permission.Storage);
                        }

Setting screenshot-

![456f9d84-79db-4ed0-8ad3-04ead1bb7010](https://user-images.githubusercontent.com/37691929/38554318-c59df01e-3cdf-11e8-8f00-20853b0049ec.jpg)

info.plist

![screen shot 2018-04-10 at 4 55 43 pm](https://user-images.githubusercontent.com/37691929/38554401-1dba77cc-3ce0-11e8-8a14-6dc0f8d7b3a3.png)

**Comment by jamesmontemagno** [comment]
iOS doesn't have any special permissions for storage. https://github.com/jamesmontemagno/PermissionsPlugin/blob/master/src/Plugin.Permissions.iOS/PermissionsImplementation.cs#L56

**Comment by jamesmontemagno** [comment]
Also see: https://github.com/jamesmontemagno/PermissionsPlugin/blob/master/src/Plugin.Permissions.Abstractions/PermissionEnums.cs

**Comment by shrutigoyal123** [comment]
@jamesmontemagno 

Okay . If I am not wrong storage and photo permission is same. If I want to access gallery then I need photo permission and photo permission I can check photo permission with Permission.Storage. Right?
Then why it is not showing photo permission popup?
