### ISSUE TITLE
RequestPermissionAsync does not return and just gets stuck regardless if the user allows or denies the permission

### ISSUE THREAD

**Issue by KaizerT** [jamesmontemagno/PermissionsPlugin#92]
Version Number of Plugin: 2.2.1.0
Device Tested On: HTC One M9
Simulator Tested On: None
Version of VS: 2015
Version of Xamarin: 2.0.0.0
Versions of other things you are using: None

Steps to reproduce the Behavior
Request permissions during boot up of app. User selects either allow or deny. I already have this setting [https://github.com/jamesmontemagno/PermissionsPlugin#android-specific-in-your-baseactivity-or-mainactivity-for-xamarinforms-add-this-code](url)

Expected Behavior
Code continues depending on returned value of requestpermimssionasync

Actual Behavior
RequestPermissionAsync never returns. No exceptions are thrown so Not sure what happened

Code snippet
```
try
           {
               var status = await CrossPermissions.Current.CheckPermissionStatusAsync(Plugin.Permissions.Abstractions.Permission.Location);
               if (status != Plugin.Permissions.Abstractions.PermissionStatus.Granted)
               {
                   if (await CrossPermissions.Current.ShouldShowRequestPermissionRationaleAsync(Plugin.Permissions.Abstractions.Permission.Location))
                   {
                       await DisplayAlert("Need location", "Location is needed for the application", "OK");
                   }
                   var results = await CrossPermissions.Current.RequestPermissionsAsync(Plugin.Permissions.Abstractions.Permission.Location);
                   //Best practice to always check that the key exists
                   if (results.ContainsKey(Plugin.Permissions.Abstractions.Permission.Location))
                   {
                       status = results[Plugin.Permissions.Abstractions.Permission.Location];
                   }
               }
           }
           catch (Exception ex)
           {
               ex = ExceptionHelper.mGetInnermostException(ex);
               Device.BeginInvokeOnMainThread(new Action(() =>
               {
                   DisplayAlert("Error",ex.Message,"Ok");
               }));
           }
```

**Comment by RichDCs** [comment]
I've got the same bug, don't know what's happening, investigating

**Comment by RichDCs** [comment]
Found a solution, I had to override OnRequestPermissionsResult (like in the sample) in my Activity:
`public override void OnRequestPermissionsResult(int requestCode, string[] permissions, [GeneratedEnum] Permission[] grantResults)
        {
            PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }`

**Comment by RichDCs** [comment]
Well it works for me! :) After that callback is called, my asynchronous call continues.
Can you try with that signature?

**Comment by KaizerT** [comment]
Sure Rich, I'll try it out at home and update this thread. Thanks

**Comment by KaizerT** [comment]
I just tried it now and it still isn't returning when the permission is granted. the asynchronous call just get's stuck even with the signature. The ticket's been closed again without confirmation

**Comment by KaizerT** [comment]
@RichDCs @jamesmontemagno I don't know if you guys can see my update but I'm still experiencing issues even with the set up in the main activity. The permission just stays there. I'd appreciate a tip. Thank you.

**Comment by bizmonger** [comment]
I'm experiencing the same issue.
Even after the suggested update to the main activity class.

Were you ever able to resolve this @KaizerT @mnesser ?

**Comment by moellerbj** [comment]
Same issue here since month. Will it ever be fixed? At the moment the user has to kill the first startet app and restart it.

**Comment by abdul-wasey** [comment]
@KaizerT 
Same issue here..
control never came back after the execution of this line of code,,, 
```
var requestStatus = await CrossPermissions.Current.RequestPermissionAsync<T>();
```

**Comment by abdul-wasey** [comment]
> Hi @RichDCs
> 
> I've already got a setting like that from the sample:
> 
> ` public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Android.Content.PM.Permission[] grantResults) { base.OnRequestPermissionsResult(requestCode, permissions, grantResults); PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults); }`
> 
> Does the GeneratedEnum make it work?

Thanks @KaizerT  

> Found a solution, I had to override OnRequestPermissionsResult (like in the sample) in my Activity:
> `public override void OnRequestPermissionsResult(int requestCode, string[] permissions, [GeneratedEnum] Permission[] grantResults) { PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults); }`
> 
> Now the async method continues! :)

Yah it's also working for me now 
thanks
