### ISSUE TITLE
RequestPermissionsAsync never returns when permission is requested (and causes Task Cancelled exception)

### ISSUE THREAD

**Issue by Devvox93** [jamesmontemagno/PermissionsPlugin#95]
## Bug Information
Version Number of Plugin: **v2.2.1**
Device Tested On: **Samsung Galaxy A3, Android 7.0**
Simulator Tested On: **NA**
Version of VS: **15.6.6**
Version of Xamarin: **4.9.0.753**
Versions of other things you are using: **NA**

### Steps to reproduce the Behavior
`var permissionStatuses = CrossPermissions.Current.RequestPermissionsAsync(permission);`
// Check if permissionStatuses contains permission
// Get status into var
// Check if status is GRANTED
// Return true, or false if not
// (DENY the permission when prompted on the device)

### Expected Behavior
The var permissionStatuses is filled with the (new) status after requesting permission.

### Actual Behavior
The method `RequestPermissionsAsync` does not return and code after that is not executed.
When going to a different fragment and coming back, the same check permission is performed and a Task Cancelled exception is thrown.

### Code snippet
```
public static bool RequestPermissionAsync(Permission permission, string title, string reasonMsg, Activity activity)
        {
            if (CrossPermissions.Current.ShouldShowRequestPermissionRationaleAsync(permission).Result)
            {
                var alertDialog = new AlertDialog.Builder(activity);
                alertDialog.SetTitle(title);
                alertDialog.SetMessage(reasonMsg);
                alertDialog.SetPositiveButton("OK", (sender, args) =>
                {
                    try
                    {
                        CrossPermissions.Current.RequestPermissionsAsync(permission);
                        // Do the checks here and return true or false
                    } catch
                    {
                        var text = "Error requesting permissions";
                        Toast.MakeText(activity.ApplicationContext, text, ToastLength.Short);
                    }
                });
                alertDialog.Show();
            } else
            {
                CrossPermissions.Current.RequestPermissionsAsync(permission);
                // Do the checks here and return true or false
            }
        }
```

### Screenshots
No screenshot as I'm not building back to code that doesn't work (workaround is in place now).

**Comment by jamesmontemagno** [comment]
This code has a lot of issues. You are never awaiting on anything and calling .Result will lock your thread.

May I recommend: http://www.mergeconflict.fm/merge-conflict-44-i-love-callbacks

```csharp
 public static async Task<bool> RequestPermissionAsync(Plugin.Permissions.Abstractions.Permission permission, string title, string reasonMsg)
        {
            var showRationale = await CrossPermissions.Current.ShouldShowRequestPermissionRationaleAsync(permission);
            if (showRationale)
            {
                var alertDialog = new AlertDialog.Builder(Application.Context);
                alertDialog.SetTitle(title);
                alertDialog.SetMessage(reasonMsg);
                alertDialog.SetPositiveButton("OK", async (sender, args) =>
                {
                    await RequestPermission(permission);
                });
                alertDialog.Show();
                return false;//returning false here because you will need a task completion source to handle the alert dialog.
                //You should probably look at using https://github.com/aritchie/userdialogs
            }
            else
            {
                return await RequestPermission(permission);
            }
        }

        public static async Task<bool> RequestPermission(Plugin.Permissions.Abstractions.Permission permission)
        {
            try
            {
                var results = await CrossPermissions.Current.RequestPermissionsAsync(permission);
                var status = PermissionStatus.Unknown;
                //Best practice to always check that the key exists
                if (results.ContainsKey(permission))
                    status = results[permission];

                return status == PermissionStatus.Granted;
            }
            catch
            {
                
                var text = "Error requesting permissions";
                Toast.MakeText(Application.Context, text, ToastLength.Short).Show();
                return false;
            }
        }
```

**Comment by Devvox93** [comment]
@jamesmontemagno I provided the code snippet with comments on functionality as I didn't have the time to reproduce my old setup that failed, as I also mentioned below the Screenshot-header.
Of course I awaited the methods, returned a Task<bool> and used a TCS.

This was merely some context in which the issue occurred, so you could tackle the problem more easily.
The issue is described pretty clearly imo. If not here, then also in the (also closed) #94.

**Comment by jamesmontemagno** [comment]
I need an actual sample so I can test and fix it. Provided your code sample it works when I read it.

**Comment by jamesmontemagno** [comment]
How are the fragments get switched? prompting the request brings it to the foreground.

**Comment by Devvox93** [comment]
Perhaps that ^could be the issue..? I use MvvmCross for navigation.

**Comment by jamesmontemagno** [comment]
Did you set the "current" activity and set that up in your app?

**Comment by bidy** [comment]
MainActivity.cs in Android Project:
```
 protected override void OnCreate(Bundle bundle)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;
            SetTheme(Resource.Style.MainTheme);
            Plugin.CurrentActivity.CrossCurrentActivity.Current.Activity = this;
            base.OnCreate(bundle);

            Xamarin.Forms.Forms.Init(this, bundle);
...
        }
```

**Comment by Devvox93** [comment]
Additional information from my previous issue that was closed:
https://github.com/jamesmontemagno/PermissionsPlugin/blob/22a4851cdc066b7e753e21bbeaf0735264d231a7/src/Plugin.Permissions/Permissions.android.cs#L191

I copied the code from source so I could debug it and it could execute until there, but never returned.
If I look at the code, the TCS is not linked to the call to `ActivityCompat.RequestPermissions(activity, permissionsToRequest.ToArray(), permissioncode);` at all.
I think that is the source of these problems and it's why my and @bidy 's code after the call to `await CrossPermissions.Current.RequestPermissionsAsync` are never executed.

In my case I got an Exception, which is probably because of MvvmCross/my navigation handling, but the fact is that the mentioned line is where it goes wrong.
It just doesn't seem like logical code to me either. You're awaiting what, eternity?

**Comment by jamesmontemagno** [comment]
You have to understand what Android is doing under the hood here. When you call RequestPermissinos on ActivityCompat it fires off a system event. This triggers "OnRequestPermissionsResult" to be called which is where the TCS is handled... which is why you pass the events back to it.

My recommendation and what I will document is that you call permissions from your Activity, not Fragment as you should not be doing any navigation during permissions.

**Comment by Baunetr** [comment]
> Same bug here on Android API 25 emulator.
> 
> ```
> private async Task TakePhoto()
>         {
>             await CrossMedia.Current.Initialize();
>             var cameraStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Camera);
>             var storageStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Storage);
> 
>             if (cameraStatus != PermissionStatus.Granted || storageStatus != PermissionStatus.Granted)
>             {
>                 var results = await CrossPermissions.Current.RequestPermissionsAsync(Permission.Camera, Permission.Storage);
> 
> // *** this code never gets executed ***
>                 cameraStatus = results[Permission.Camera];
>                 storageStatus = results[Permission.Storage];
>             }
> ...
> ```

I was experiencing this exact issue on my project and found that I could fix the issue by doing the following. Hopefully, this is helpful to someone else. 

Sorry for the formatting issues I wasn't able to paste the whole function in but this covers the important parts. 





        //check permissions to see if we can use the camera
        PermissionStatus cameraStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Camera);
        PermissionStatus storageStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Storage);
        if (cameraStatus != PermissionStatus.Granted || storageStatus != PermissionStatus.Granted) {
          var results = await GetPhotoPermissions();
          // *** this code now gets executed ***
          if (results != null) {
            cameraStatus = results[Permission.Camera];
            storageStatus = results[Permission.Storage];
          }
        }

        } else {
          bool go = await DisplayAlert(Resx.AppResources.TitleAlertAccessDenied, Resx.AppResources.MessageAlertAccessDenied, Resx.AppResources.SettingsLinkLabel, Resx.AppResources.CancelTaskLabel);
          if (go) {
            CrossPermissions.Current.OpenAppSettings();
          }
        }

      } catch (Exception ex) {
        Crashes.TrackError(ex, properties);
      }
    }

    public async Task<Dictionary<Permission, PermissionStatus>> GetPhotoPermissions() {
      var properties = TelemetryHelper.InitTcProps(ClassName, nameof(GetPhotoPermissions));
      try {
        return await CrossPermissions.Current.RequestPermissionsAsync(new[] { Permission.Camera, Permission.Storage });
      } catch (Exception ex) {
        Crashes.TrackError(ex, properties);
        return null;
      }
    }`

**Comment by ohgabbey** [comment]
Hi! I tried using this code (see photo attachment) but it doesn't show a pop-up message asking for permission. :( Please help. Thank you.
![image](https://user-images.githubusercontent.com/25600521/65016904-fd814380-d957-11e9-916b-48b55e75c10f.png)

**Comment by Lelelo1** [comment]
I am also running into problem on Android only. Device api 25, emulator api 28:

I have the following code which starts a cameraview: 

```
public async void Start()
{
    if(await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Camera) != PermissionStatus.Granted)
    {
        Console.WriteLine("requesting....");
        await CrossPermissions.Current.RequestPermissionsAsync(Permission.Camera);
        // never gets here on Android.
    }
            
    if(await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Camera) == PermissionStatus.Granted)
    {
        Console.WriteLine("Got permission, starting");
        OnStart(this); // invoke delegate
    }
}
```

In `OnCreate` I have the following:

```
    ToolbarResource = Resource.Layout.Toolbar;
    Plugin.CurrentActivity.CrossCurrentActivity.Current.Init(this, savedInstanceState); // <---
    base.OnCreate(savedInstanceState);
    Xamarin.Essentials.Platform.Init(this, savedInstanceState);
    /* ... */
```

And I have:

```
public override void OnRequestPermissionsResult(int requestCode, string[] permissions, [GeneratedEnum] Android.Content.PM.Permission[] grantResults)
{
    Xamarin.Essentials.Platform.OnRequestPermissionsResult(requestCode, permissions, grantResults);
   base.OnRequestPermissionsResult(requestCode, permissions, grantResults);
}
```
... in my MainActivity.cs as well.

Which means the user as to tap twice to get into my camera view on Android.

**Comment by Lelelo1** [comment]
I had missed to add:

```
Plugin.Permissions.PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
```
in `OnRequestPermissionsResult`

**Comment by HimanshuN-Hexaware** [comment]
I found a good solution for this . Check it out here
https://stackoverflow.com/questions/50338025/xamarin-permissions-plugin-requestpermissionsasync-not-returning

**Comment by TechnikKTK** [comment]
Hi, again a good plugin, and even with Xamarin support.Essentials, but there is a suggestion you have in abstractions:
public enum Permission Status
{
Denied = 0,
Disabled = 1,
Granted = 2,
Restricted = 3,
Unknown = 4
}

and Xamarin:

public enum Permission Status
{
Unknown = 0,
Denied = 1,
Disabled = 2,
Granted = 3,
Restricted = 4
}


it is very inconvenient to use type casting when you have the status = granted, and in xamarin = disabled

**Comment by TechnikKTK** [comment]
> Привет, снова хороший плагин, и даже с поддержкой Xamarin.Essentials, но есть предложение, которое у вас есть в абстракциях: public enum Permission Status { Denied = 0, Disabled = 1, Granted = 2, Restricted = 3, Unknown = 4 }
> 
> и Xamarin:
> 
> public enum Статус разрешения { Неизвестно = 0, Отказано = 1, Отключено = 2, Предоставлено = 3, Ограничено = 4 }
> 
> очень неудобно использовать приведение типов, когда у вас есть статус = предоставлено, а в xamarin = отключено

Could you sync them in the future
