### ISSUE TITLE
RequestPermissionsAsync always returns denied for Permission.Photos if user has answered no on 1st request in iOS

### ISSUE THREAD

**Issue by mackayn** [jamesmontemagno/PermissionsPlugin#96]
## Bug Information

Version Number of Plugin: 2.2.1
Android Devices Tested On: Samsung S5 (6.0.1), Galaxy note 3 (7.0)
iOS Devices Tested On: iPad 5th gen (11.3), iPhone6 (11.3.1)
Simulator Tested On: None
Version of VS: 15.5.6 (Windows x64)
Version of Xamarin: Android SDK   8.2.0.16, Xamarin.Mac SDK   11.9.1.24 XCode 9.3
Versions of other things you are using: Xamarin Forms 2.5.1.444934 (PCL)

### Steps to reproduce the Behavior

Uninstall app from device
Power cycle device
Deploy app

### Expected Behavior

The code supplied should prompt the user each time you request the camera if access has been denied.

### Actual Behavior

The 1st call to HasCameraPermission works, after that, PermissionStatus.Denied is always returned and no permission prompt is shown. 

### Code snippet

```
        public async Task<bool> HasCameraPermission()
        {
			// Check permission
			var hasCameraPermission = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Camera);

			// Ask for permissions
			if (hasCameraPermission != PermissionStatus.Granted)
			{
				var results = await CrossPermissions.Current.RequestPermissionsAsync(Permission.Camera); // Only shows prompt once
				hasCameraPermission = results[Permission.Camera];
			}

			return Equals(hasCameraPermission, PermissionStatus.Granted);	
        }
```

Even calling the methods in PHPhotoLibrary via my own dependency service caused the same results so it's perhaps a lower level issue in mono.

**Comment by jamesmontemagno** [comment]
This is how iOS works. You only get 1 chance!
