### ISSUE TITLE
RequestPermissionsAsync is able to crash my app

### ISSUE THREAD

**Issue by SalvoAprile** [jamesmontemagno/PermissionsPlugin#97]
Hi Guys,

I'm devolping an app with Xamarin.Forms standard 2 (ver: 2.5.0.280555) with Permission plugin and media plugin.
When I try to take a photo, 2 permissions are requested with prompt (android 8.0), Camera and Storage but when I try to request a permission using a Permission Plugin the app crashes. I try both on emu (genymotion) and on Physical Device.

On genymotion the error is 
System.NullReferenceException: Object reference not set to an instance of an object

on Physical device the error is 
fatal signal 11 sigsegv code 2 

this is a manifest: 

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" android:versionName="1.0" package="com.companyname.Near2Me" android:installLocation="auto">
	<uses-sdk android:minSdkVersion="23" android:targetSdkVersion="25" />
	<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
	<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
	<uses-permission android:name="android.permission.BLUETOOTH" />
	<uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
	<application android:label="Near2Me.Android">
		<provider android:name="android.support.v4.content.FileProvider" android:authorities="com.companyname.Near2Me.fileprovider" android:exported="false" android:grantUriPermissions="true">
			<meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/file_paths"></meta-data>
		</provider>
	</application>
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
</manifest>

and assembly info

[assembly: UsesPermission(Android.Manifest.Permission.Internet)]
[assembly: UsesPermission(Android.Manifest.Permission.WriteExternalStorage)]
[assembly: UsesPermission(Android.Manifest.Permission.Flashlight)]
[assembly: UsesPermission(Android.Manifest.Permission.ReadPhoneState)]
[assembly: UsesFeature("android.hardware.camera", Required = false)]
[assembly: UsesFeature("android.hardware.camera.autofocus", Required = false)]
[assembly: UsesFeature("android.hardware.wifi", Required = false)]

I try to use Permission PLugin in other new simple app and run successfully.

NB If i open again the app, the media plugin run successfully and the photo is taken. The problem is in the permission plugin

Can you help me ?

**Comment by jamesmontemagno** [comment]
You didn't set the current activity plugin up.

**Comment by SalvoAprile** [comment]
Hi James, thanks for the respose. 

I believe that the current activity is set correctly. 
I create a MainApplication.cs in droid project with this code and I put package from nuget:

using System;
using Android.App;
using Android.OS;
using Android.Runtime;
using Plugin.CurrentActivity;

namespace MyApp.Droid
{
	//You can specify additional application information in this attribute
    [Application]
    public class MainApplication : Application, Application.IActivityLifecycleCallbacks
    {
        public MainApplication(IntPtr handle, JniHandleOwnership transer)
          :base(handle, transer)
        {
        }

        public override void OnCreate()
        {
            base.OnCreate();
            RegisterActivityLifecycleCallbacks(this);
            //A great place to initialize Xamarin.Insights and Dependency Services!
        }

        public override void OnTerminate()
        {
            base.OnTerminate();
            UnregisterActivityLifecycleCallbacks(this);
        }

        public void OnActivityCreated(Activity activity, Bundle savedInstanceState)
        {
            CrossCurrentActivity.Current.Activity = activity;
        }

        public void OnActivityDestroyed(Activity activity)
        {
        }

        public void OnActivityPaused(Activity activity)
        {
        }

        public void OnActivityResumed(Activity activity)
        {
            CrossCurrentActivity.Current.Activity = activity;
        }

        public void OnActivitySaveInstanceState(Activity activity, Bundle outState)
        {
        }

        public void OnActivityStarted(Activity activity)
        {
            CrossCurrentActivity.Current.Activity = activity;
        }

        public void OnActivityStopped(Activity activity)
        {
        }
    }
}

did I forget something ? 

Thanks in advance

**Comment by jamesmontemagno** [comment]
Can you give me a small sample app to reproduce?

**Comment by SalvoAprile** [comment]
Hi James, I attached the exampla app. The app crashes on Version 7.1 and 8.0 also on genymotion emulator but only when the method CrossPermissions.Current.RequestPermissionsAsync is called

Thanks

[App_James.zip](https://github.com/jamesmontemagno/PermissionsPlugin/files/1979668/App_James.zip)

**Comment by jamesmontemagno** [comment]
Your issue is:

global::ZXing.Net.Mobile.Forms.Android.PermissionsHandler.OnRequestPermissionsResult(requestCode, permissions, grantResults);
             
Change to:

ZXing.Net.Mobile.Android.PermissionsHandler.OnRequestPermissionsResult(requestCode, permissions, grantResults);


Also your check for: 
                storageStatus = results[Permission.Storage]; will throw an exception, you should ensure it is in the dictionary and request the permission.

**Comment by Redth** [comment]
Can you make sure to add:

```
MobileBarcodeScanner.Initialize (myApplicationClassInstance);
```

Somewhere in your calls to init all the things?
