### ISSUE TITLE
Linker error on iOS after update

### ISSUE THREAD

**Issue by Nevyn75** [jamesmontemagno/PermissionsPlugin#99]
Hi.

After updating VS, Xamarin and all pacakges, I'm no more able to build my solution on iOS. On Android it is ok.

I've tried cleaning bin and obj dirs.
I've tried removing and re-adding package.

Note: Into PCL and Android the update installed the version 3.0.0.8, into iOS project the version 2.2.1

MTOUCH: Error MT2002: Failed to resolve "Plugin.Permissions.Abstractions.PermissionStatus" reference from "Plugin.Permissions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" (MT2002)

# Bug Information
Version Number of Plugin: 2.2.1
Device Tested On: iPhone 6
Version of VS: 2017 for Mac version 7.4
Version of Xamarin: Xamarin.iOS 11.10

### Steps to reproduce the Behavior
Just clean up everything and re-build all after update

### Actual Behavior
MTOUCH: Error MT2002: Failed to resolve "Plugin.Permissions.Abstractions.PermissionStatus" reference from "Plugin.Permissions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" (MT2002)

### Code snippet
I'm using the same code written on examples.

Thank you and best regards.

**Comment by Nevyn75** [comment]
Fixed.

I just removed by hand any reference to version 2.2.1 (plugin.permissions and plugin.permissions.abstraction) form iOS project and loaded only plugin.permissions v3.0.0.8.

Now it compiles.

Best regards.

**Comment by krruzic** [comment]
@Nevyn75 I know this is closed but I'm having the exact same issue. What references and where?
